project:
  type: book
  output-dir: docs
  resources:
    - bilder/
    - datasett/
    - tidligere-eksamensoppgaver/
    - script-slides/
    - diverse/
  render:
    - index.qmd
    - 01-intro-til-r.qmd
    - 02-grunnleggende-statistikk.qmd
    - 03-hypotesetesting.qmd
    - 04-regresjon.qmd
    - 05-tidsrekker.qmd
    - 06-avansert-regresjon-og-maskinlaering.qmd
    - 07-dataøvinger.qmd
    - 08-seminaroppgaver.qmd
    - 10-Eksamensoppgaver.qmd

lang: nb

book:
  title: "MET4 – Empiriske Metoder"
  subtitle: "Høst 2026"
  author: "Geir Drage Berentsen, Håkon Otneim og Maren Holthe Hedne"
  description: "Hjemmesiden til kurset MET4 – Empiriske Metoder ved Norges Handelshøyskole."
  search: true
  favicon: bilder/icon/favicon.ico
  page-navigation: true
  page-footer:
    left: "MET4 – Empiriske Metoder, NHH"
    right:
      - text: "Håkon Otneim"
        href: "https://www.nhh.no/en/employees/faculty/hakon-otneim/"
      - text: "Geir Drage Berentsen"
        href: "https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/"
  chapters:
    - index.qmd
    - part: "Moduler"
      chapters:
        - 01-intro-til-r.qmd
        - 02-grunnleggende-statistikk.qmd
        - 03-hypotesetesting.qmd
        - 04-regresjon.qmd
        - 05-tidsrekker.qmd
        - 06-avansert-regresjon-og-maskinlaering.qmd
    - part: "Oppgaver og eksamen"
      chapters:
        - 07-dataøvinger.qmd
        - 08-seminaroppgaver.qmd
        - 10-Eksamensoppgaver.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    include-in-header: nhh-sidebar.html

execute:
  freeze: auto
