<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nb" xml:lang="nb"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Hjemmesiden til kurset MET4 – Empiriske Metoder ved Norges Handelshøyskole.">

<title>4&nbsp; Regresjon – MET4 – Empiriske Metoder</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-tidsrekker.html" rel="next">
<link href="./03-hypotesetesting.html" rel="prev">
<link href="./icon/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ec8eff129d6f50c8392963982e963180.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Ingen resultater",
    "search-matching-documents-text": "Samsvarende dokumenter",
    "search-copy-link-title": "Kopier link for å søke",
    "search-hide-matches-text": "Skjul ytterlige resultater",
    "search-more-match-text": "annet resultat i dette dokumentet",
    "search-more-matches-text": "andre resultater i dette dokumentet",
    "search-clear-button-title": "Tøm",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Avbryt",
    "search-submit-button-title": "Send inn",
    "search-label": "Søk"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Slå av eller på sidebarnavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-intro-til-r.html">Moduler</a></li><li class="breadcrumb-item"><a href="./04-regresjon.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresjon</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Slå av eller på sidebarnavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Søk" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MET4 – Empiriske Metoder</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Søk"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Innledning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Moduler</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Slå på delen">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro-til-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduksjon til R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-grunnleggende-statistikk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grunnleggende statistikk</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-hypotesetesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hypotesetesting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regresjon.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresjon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-tidsrekker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tidsrekker</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-avansert-regresjon-og-maskinlaering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Avansert regresjon og maskinlæring</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Oppgaver og eksamen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Slå på delen">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-dataøvinger.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dataøvinger</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-seminaroppgaver.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Seminaroppgaver</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Eksamensoppgaver.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Eksamensoppgaver</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innholdsfortegnelse</h2>
   
  <ul>
  <li><a href="#enkel-regresjon" id="toc-enkel-regresjon" class="nav-link active" data-scroll-target="#enkel-regresjon"><span class="header-section-number">4.1</span> Enkel regresjon</a>
  <ul class="collapse">
  <li><a href="#videoforelesninger" id="toc-videoforelesninger" class="nav-link" data-scroll-target="#videoforelesninger">Videoforelesninger</a></li>
  <li><a href="#kommentarer" id="toc-kommentarer" class="nav-link" data-scroll-target="#kommentarer"><span class="header-section-number">4.1.1</span> Kommentarer</a></li>
  </ul></li>
  <li><a href="#multippel-regresjon" id="toc-multippel-regresjon" class="nav-link" data-scroll-target="#multippel-regresjon"><span class="header-section-number">4.2</span> Multippel regresjon</a>
  <ul class="collapse">
  <li><a href="#videoforelesninger-1" id="toc-videoforelesninger-1" class="nav-link" data-scroll-target="#videoforelesninger-1">Videoforelesninger</a></li>
  <li><a href="#kommentarer-1" id="toc-kommentarer-1" class="nav-link" data-scroll-target="#kommentarer-1"><span class="header-section-number">4.2.1</span> Kommentarer</a></li>
  </ul></li>
  <li><a href="#modellbygging" id="toc-modellbygging" class="nav-link" data-scroll-target="#modellbygging"><span class="header-section-number">4.3</span> Modellbygging</a>
  <ul class="collapse">
  <li><a href="#videoforelesninger-2" id="toc-videoforelesninger-2" class="nav-link" data-scroll-target="#videoforelesninger-2">Videoforelesninger</a></li>
  <li><a href="#kommentarer-2" id="toc-kommentarer-2" class="nav-link" data-scroll-target="#kommentarer-2"><span class="header-section-number">4.3.1</span> Kommentarer</a></li>
  </ul></li>
  <li><a href="#oppgaver" id="toc-oppgaver" class="nav-link" data-scroll-target="#oppgaver"><span class="header-section-number">4.4</span> Oppgaver</a>
  <ul class="collapse">
  <li><a href="#regresjon-med-en-forklaringsvariabel" id="toc-regresjon-med-en-forklaringsvariabel" class="nav-link" data-scroll-target="#regresjon-med-en-forklaringsvariabel"><span class="header-section-number">4.4.1</span> Regresjon med en forklaringsvariabel</a></li>
  <li><a href="#multippel-regresjon-og-modellbygging" id="toc-multippel-regresjon-og-modellbygging" class="nav-link" data-scroll-target="#multippel-regresjon-og-modellbygging"><span class="header-section-number">4.4.2</span> Multippel regresjon og modellbygging</a></li>
  </ul></li>
  <li><a href="#sec-relevante-r-regresjon" id="toc-sec-relevante-r-regresjon" class="nav-link" data-scroll-target="#sec-relevante-r-regresjon"><span class="header-section-number">4.5</span> Relevante R-kommandoer</a>
  <ul class="collapse">
  <li><a href="#tilpasse-en-lineær-regresjonsmodell" id="toc-tilpasse-en-lineær-regresjonsmodell" class="nav-link" data-scroll-target="#tilpasse-en-lineær-regresjonsmodell">Tilpasse en lineær regresjonsmodell</a></li>
  <li><a href="#prediksjoner-med-konfidens--og-prediksjonsintervall" id="toc-prediksjoner-med-konfidens--og-prediksjonsintervall" class="nav-link" data-scroll-target="#prediksjoner-med-konfidens--og-prediksjonsintervall">Prediksjoner, med konfidens- og prediksjonsintervall</a></li>
  <li><a href="#lage-residualplott" id="toc-lage-residualplott" class="nav-link" data-scroll-target="#lage-residualplott">Lage residualplott</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-intro-til-r.html">Moduler</a></li><li class="breadcrumb-item"><a href="./04-regresjon.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresjon</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresjon</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>I forrige modul fokuserte vi på <em>binære</em> spørsmål av typen “Er det en forskjell mellom disse to populasjonene, eller ikke?”, “Er disse kjennetegnene uavhengige, eller ikke?”, og så videre. I denne modulen skal vi prøve å gå et steg lenger og tillate mer interessante spørsmål. I stedet for bare å spørre om en eller annen effekt er til stede (eller ikke), så vil vi heller finne ut hvor stor denne effekten er, hvilken retning den går, og kanskje om vi kan bruke kunnskapen vi får om statistiske sammenhenger til å si noe fornuftig om hva som vil skje for noe som vi enda ikke har observert. Da er det regresjon som gjelder, og mer spesifikt for vår del: <em>lineær regresjon</em>.</p>
<p>Regresjon er et hovedtema i MET4. Vi innfører en <em>statistisk modell</em> som i sin enkleste form sier at en <em>forklaringsvariabel</em> <span class="math inline">\(X\)</span> henger sammen med en responsvariabel <span class="math inline">\(Y\)</span> på en helt bestemt måte, nemlig gjennom ligningen</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \epsilon.\]</span></p>
<p>Ligningen over sier at det er en <em>lineær</em> sammenheng mellom <span class="math inline">\(X\)</span> og <span class="math inline">\(Y\)</span>, men at det i tillegg kommer en uforutsigbar støyvariabel <span class="math inline">\(\epsilon\)</span> som gjør at vi ikke vil kunne observere den lineære sammenhengen direkte. Det vi derimot kan gjøre, er å bruke de observerte <span class="math inline">\(X\)</span>er og <span class="math inline">\(Y\)</span>er til å finne ut hvilke verdier av <span class="math inline">\(\beta_0\)</span> og <span class="math inline">\(\beta_1\)</span> som passer <em>best</em>. Til det bruker vi minste kvadraters metode, som beskrevet i videoforelesningene i denne modulen.</p>
<p>Vi deler arbeidet med regresjon inn i tre deler. I den første (og største) delen går vi grundig gjennom ulike sider vi den enkle lineære regresjonsmodellen over. I den andre delen ser vi på <em>multippel regresjon</em> som er en utvidelse av enkel regresjon der vi tillater flere forklaringsvariabler på høyre side av likhetstegnet, og i den tredje delen ser vi på ulike praktiske aspekter ved regresjonsmodellering og modellbygging.</p>
<p>I videoforelesningene går vi gjennom noen slides, og vi skriver et R-skript. Du kan laste disse ned ved å klikke på lenkene under:</p>
<p><a href="script-slides/regresjon/regresjon-slides.html">Slides til “Regresjon”</a></p>
<p><a href="script-slides/regresjon/regresjon-script.R">R-script til “Regresjon”</a></p>
<p><strong>TIPS:</strong> Hvis du ønsker å laste ned lysbildene som PDF trykker du på linken over, velger “Skriv ut”, og så skriver du ut som PDF. Før du gjør det bør du scrolle gjennom alle sidene slik at ligningene vises korrekt.</p>
<section id="enkel-regresjon" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="enkel-regresjon"><span class="header-section-number">4.1</span> Enkel regresjon</h2>
<section id="videoforelesninger" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="videoforelesninger">Videoforelesninger</h3>
<div style="padding:75% 0 0 0;position:relative;">
<iframe src="https://vimeo.com/showcase/7781447/embed" allowfullscreen="" frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;">
</iframe>
</div>
</section>
<section id="kommentarer" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="kommentarer"><span class="header-section-number">4.1.1</span> Kommentarer</h3>
<p>Vi har sett på en del figurer som illustrerer noen pedagogiske poenger, og lærebokens kapittel <strong>16</strong> går detaljert til verks når de beskriver de ulike læringsmomentene:</p>
<p>I kapittel <strong>16.1</strong> kan vi lese mer om den statistiske modellen som vi kaller enkel regresjon. I kapittel <strong>16.2</strong> introduseres minste kvadraters metode for å estimere regresjonskoeffisientene ved hjelp av data. De viser til og med hvordan det kan gjøres manuelt ved hjelp av bildatasettet, men det er selvsagt kun for å illustrere hvodan formlene ser ut. Vi estimerer ved hjelp av R, og vi har sett i videoforelesningen hvordan vi gjør det ved hjelp av <code>lm()</code>-funksjonen.</p>
<p>Det som gjør regresjon til et <em>statistisk</em> problem er feilleddet <span class="math inline">\(\epsilon\)</span>. Vi tenker oss at for en gitt verdi av <span class="math inline">\(X\)</span>, så vil «naturen» regne ut verdien av <span class="math inline">\(Y\)</span> ved å regne ut den lineære sammenhengen <span class="math inline">\(Y = \beta_0 + \beta_1 X\)</span>, og så legge til støyvariabelen <span class="math inline">\(\epsilon\)</span> som <em>trekkes</em> fra en sannsynlighetsfordeling. Vi kan ikke observere direkte hvilke <span class="math inline">\(\epsilon\)</span> som «naturen» har «trukket» (for da ville vi med en gang kunne regnet oss frem til verdiene av <span class="math inline">\(\beta_0\)</span> og <span class="math inline">\(\beta_1\)</span>). For gitte estimater av regresjonskoeffisientene <span class="math inline">\(\widehat \beta_0\)</span> og <span class="math inline">\(\widehat \beta_1\)</span> (som vi kan finne f.eks. ved hjelp av minste kvadraters metode), så kan vi regne ut de <em>observerte residualene</em></p>
<p><span class="math display">\[\widehat\epsilon_i = Y_i - \widehat Y_i = Y_i - (\widehat \beta_0 + \widehat \beta_1 X_i).\]</span></p>
<p>Ved å analysere residualene kan vi si mer om f.eks</p>
<ol type="1">
<li>Er det egentlig en lineær sammenheng mellom <span class="math inline">\(X\)</span> og <span class="math inline">\(Y\)</span>? Hvis det er mønstre og sammenhenger i de observerte residualene, tyder det på at den enkle lineære modellen <em>ikke</em> fanger opp hele sammenhengen mellom <span class="math inline">\(X\)</span> og <span class="math inline">\(Y\)</span>.</li>
<li>Vi kan gå mer spesifikt til verks: nøyaktig <em>hvilke</em> antakelser om residualene er ser ut til å være brutt? I senere økonometrikurs vil dere kunne lære mer om hvordan vi håndterer de ulike problemene.</li>
<li>Hvor stor er variansen til <span class="math inline">\(\epsilon\)</span>? Det brukes videre til å sette opp den viktige signifikanstesten for om stigningstallet i regresjonen er forskjellig fra null.</li>
</ol>
<p>Alt dette behandles grudig i bokens kapittel <strong>16.3–16.6</strong>. Her bør teksten leses godt. Kode til bileksempelet finnes i scriptet som følger med videoforelesningene.</p>
<p>Når det gjelder enkel regresjon kan du sjekke om du har fått med deg det vesentligste ved å diskutere følgende spørsmål:</p>
<ol type="1">
<li>Hva er responsvariabelen og hva er forklaringsvariabelen i enkel regresjon?</li>
<li>Hva er fortolkningen av de to regresjonskoeffisientene?</li>
<li>Hvilket prinsipp er det vi legger til grunn når vi skal bestemme (estimere) verdien av koeffisientene ved hjelp av data?</li>
<li>Skriv opp formlene for koeffisientestimatene. Kan du gi en intuitiv fortolkning av disse? Er de rimelige?</li>
<li>Kan du ved hjelp av formelen for <span class="math inline">\(\widehat\beta_1\)</span> utlede sammenhengen mellom <em>stigningstallet</em> <span class="math inline">\(\beta_1\)</span> og korrelasjonskoeffisienten* mellom <span class="math inline">\(X\)</span> og <span class="math inline">\(Y\)</span>?</li>
<li>Hvilken rolle spiller feilleddet (<span class="math inline">\(\epsilon\)</span>)?</li>
<li>Skriv opp de 4 + 1 forutsetningene. Når må den siste være oppfylt? Når kan vi klare oss uten?</li>
<li>Hva er testobservatoren når vi tester H<span class="math inline">\(_0: \beta_1 = 0\)</span>?</li>
<li>Kan du holde styr på de fire standardavvikene vi har jobbet med i denne forelesningen?</li>
<li>Hva mener vi med å diagnostisere en regresjonsmodell?</li>
<li>Hva er <span class="math inline">\(R^2\)</span>, og hva måler den?</li>
<li>Hva sier <span class="math inline">\(R^2\)</span> <em>ikke</em> noe om?</li>
</ol>
<p>Her er noen grunnleggende ferdigheter fra kapittel 16. Klarer du dette?</p>
<ol type="1">
<li>Bruke til å tilpasse en enkel regresjonsmodell for et datasett?</li>
<li>Bruke til å skrive ut oversiktlige regresjonstabeller?</li>
<li>Tolke en regresjonsutskrift?</li>
<li>Hente ut relevant informasjon etter en slik tilpasning?</li>
<li>Bruke informasjon fra regresjonsutskriften til å regne ut antall stjerner for hånd?</li>
<li>Lage diagnoseplott i ?</li>
<li>Diagnistisere en modell?</li>
<li>Identifisere innflytelsesrike observasjoner?</li>
</ol>
</section>
</section>
<section id="multippel-regresjon" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="multippel-regresjon"><span class="header-section-number">4.2</span> Multippel regresjon</h2>
<section id="videoforelesninger-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="videoforelesninger-1">Videoforelesninger</h3>
<div style="padding:75.14% 0 0 0;position:relative;">
<iframe src="https://vimeo.com/showcase/7793207/embed" allowfullscreen="" frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;">
</iframe>
</div>
</section>
<section id="kommentarer-1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="kommentarer-1"><span class="header-section-number">4.2.1</span> Kommentarer</h3>
<p>I kapittel <strong>17</strong> utvides regresjonsbegrepet til <em>multippel</em> regresjon, som i prasis betyr at vi kan ha flere enn en forklaringsvariable:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1X_1 + \cdots \beta_kX_k + \epsilon,\]</span> men utover dette er alle detaljene vi har snakket om de samme. For eksempel:</p>
<ul>
<li>Tolkningen av regresjonskoeffisienten: En endring på en enhet i forklaringsvariabelen <span class="math inline">\(X_j\)</span> henger sammen med <span class="math inline">\(\beta_j\)</span> enhets endring i responsvariabelen <span class="math inline">\(Y\)</span> (merk at jeg ikke brukker begrepet “fører til”, vi kan ikke uten videre fortolke sammenhengen som kausal!).</li>
<li>Analysen av residualene <span class="math inline">\(\widehat \epsilon_i = Y_i - \widehat Y_i\)</span> er den samme og har samme formål 1–3 som over.</li>
<li><span class="math inline">\(R^2\)</span> har samme fortolkning.</li>
<li>R-kommandoen er den samme, vi bare sette pluss mellom forklaringsvariablene, f.eks <code>reg &lt;- lm(Y ~ X1 + ... + Xk, data = x)</code></li>
</ul>
<p>I tillegg innfører vi noen nye begreper:</p>
<p><strong>Justert</strong> <span class="math inline">\(R^2\)</span>: Vi viste i forelesningen at vi vil alltid klare å øke <span class="math inline">\(R^2\)</span> ved å legge til forklaringsvariable, selv om de ikke har noe med problemet å gjøre. Derfor innførte vi en <em>justert</em> <span class="math inline">\(R^2\)</span> som tar høyde for nettopp dette, ved å bli større bare dersom den aktuelle forklaringsvariebelen faktisk forklarer en reell mengde av variasjonen i responsvariabelen. Se avsnitt <strong>17-2f</strong> i læreboken.</p>
<p><strong>Multikolinearitet</strong>: Dersom en forklaringsvariabel er sterkt korrelert med en eller flere andre forklaringsvariabler har vi multikolinearitet. Det blir naturlig nok et problem å skille effekter fra hverandre når de i realiteten er helt eller nesten like. Ekstremtilfellet er <em>perfekt multikolinearitet</em> der en variabel er en eksakt lineær funksjon av en eller flere andre variable. Det typiske tilfellet er at vi har to kolonner der vi måler det samme fenomenet, men med to ulike enheter, f.eks. <strong>cm</strong> og <strong>m</strong>. Selvsagt kan vi ikke klare å identifisere en <em>separat</em> og <em>uavhengig</em> effekt av <span class="math inline">\(X\)</span> på <span class="math inline">\(Y\)</span> om vi skifter måleenhet, og vi vil få en feilmelding dersom vi prøver på det. Det er ekvivalent med å dele på null (every time you divide by zero, God kills a kitten!). Løsning: fjern en av kolonnene fra regresjonsanalysen.</p>
<p>Verre er det om to variable måler <em>nesten</em> det samme, men ikke helt, som i skoledataeksempelet der vi kunne bruke både innbyggertall og antall femteklassinger i kommunen som forklaringsvariabler. De henger tett sammen, men selvsagt ikke eksakt, og det virker rart å kunne knytte separate efekter til disse to variablene. I dette tilfellet får vi likevel ikke feilmeldinger, men konsekvensen kan fort bli at standardavvikene (usikkerheten!) til koeffisientestimatene eksploderer, og at ingen av variablene blir signifikant forskjellige fra null, selv det det faktisk er en sterk sammenheng mellom kommunestørrelse og prøveresultat (husk at testobservatoren: <span class="math inline">\(t = \widehat \beta_k/\sigma_{\beta_k}\)</span> blir liten når nevneren blir stor).</p>
<p><strong>F-test for multiple sammenligninger</strong>: Dette henger nøye sammen med <em>variansanalyse (analysis of variance, ANOVA)</em>, som nå er tatt ut av pensum i kurset. For å forstå dette kan vi sette opp et eksempel, med to forklaringsvariabler: <span class="math display">\[Y = \beta_0 + \beta_1X_1 + \beta_2X_2.\]</span> Etter å ha brukt miste kvadraters metode for å estimere de tre koeffisientene er vi kanskje interessert i å vurdere den statsistiske signifikansene til de to stigningstallene separat. Da tester vi de to nullhypotesene <span class="math inline">\(\beta_1 = 0\)</span> og <span class="math inline">\(\beta_2 = 0\)</span>, som vi i praksis gjør ved å se på hvor mange stjerner de får i regresjonsutskriften. Men sett at ingen av koeffisientene er signifikant forskjellige fra null, kan vi da slutte at vi ikke kan forkaste hypotesen <span class="math inline">\(\beta_1 = \beta_2 = 0\)</span>, dvs at <em>begge</em> koeffisientene er lik null, og at ingen av forklaringsvariablene forklarer variasjon i <span class="math inline">\(Y\)</span>? <strong>NEI</strong>, det kan vi ikke. Vi kan for eksempel lett tenke oss at vi på grunn av multikolinearitet ikke får separate forkastninger av de to nullhypotesene, men at ved å fjerne en variabel, så blir den andre signifikant.</p>
<p>For å virkelig forstå dette problemet kan du godt lese starten på kapittel <strong>14.1</strong> samt kapittel <strong>14.2</strong> om multiple sammenligninger (som strengt tatt ikke er pensum), men essensen er altså:</p>
<p><span class="math display">\[\textrm{Å forkaste H}_0: \beta_1 = 0 \textrm{ og H}_0: \beta_2 = 0 \textrm{ er ikke det samme som å forkaste H}_0: \beta_1 = \beta_2 = 0!\]</span></p>
<p>For å gjennomføre den siste testen må vi sette opp en egen testobservator, som viser seg å være <span class="math inline">\(F\)</span>-fordelt. Læreboken lister opp noen detaljer i avsnitt <strong>17-2f</strong>, og essensen er at vi setter opp en brøk på formen <span class="math display">\[F = \frac{\textrm{Variasjon i } Y \textrm{ som fanges opp av regresjonsmodellen med } X_1 \textrm{ og }X_2}{\textrm{Variasjon i } Y \textrm{ som fanges opp av regresjonsmodellen uten } X_1 \textrm{ og }X_2}.\]</span> Dersom denne brøken viser seg å være stor (som definert av signifikansnivå og frihetsgrader, se lærebok), forkaster vi nullhypotesen om at begge koeffisientene begge kan være lik null. I en generell multippel regresjon med <span class="math inline">\(k\)</span> forklaringsvariable rapporterer R <code>F-statistic:</code> etc, med verdien av <span class="math inline">\(F\)</span>-observatoren i testen for <span class="math display">\[H_0: \beta_1 = \cdots = \beta_k = 0,\]</span> og dersom den oppgitte <span class="math inline">\(p\)</span>-verdien er mindre enn f.&nbsp;eks. 5%, kan vi slutte at ikke alle koeffisientene kan være null samtidig (selv om ingen av koeffisientene i seg selv nødvendigvis er signifikant forskjellig fra null).</p>
<p>Som en såkalt <em>fun fact</em> kan vi nevne at det er enkelt å teste for signifikansen til <em>grupper</em> av variable på denne måten, f.eks hvis det er noen variable som måler lignende ting (si <span class="math inline">\(X_2, X_4\)</span> og <span class="math inline">\(X_5\)</span>). I R kan du estimere to modeller, en modell som <em>inkluderer</em> variablene (f.eks. <code>reg_stor</code>) og en modell der du tar bort de aktuelle variablene (f.eks. <code>reg_liten</code>). Du kan da kjøre kommandoen <code>anova(reg_stor, reg_liten)</code> for å teste <span class="math display">\[H_0: \beta_2 = \beta_4 = \beta_5 = 0.\]</span></p>
<blockquote class="blockquote">
<p><strong>Kritikk av læreboken:</strong> Læreboken har en tabell på s. 701 som viser sammenhengen mellom ulike statistiske størrelser som vi kan regne ut for en regresjonsmodell. <span class="math inline">\(R^2\)</span> kjenner vi som forklaringsgraden, <span class="math inline">\(s_{\epsilon}\)</span> er standardavviket til residualene, <span class="math inline">\(F\)</span> er testobservatoren for modellgyldighet som vi definerte uformelt over, og som er definert formelt nederst på s. 700, mens SSE (Sum of Squares Error) henger nøye sammen med standardavviket, som vi også kan se på s. 700. På disse sidene ser vi mange ligninger som viser hvordan disse størrelsene formelt henger sammen, og i tabellen på s. 701 ser vi blant annet at dersom SSE er liten, er også <span class="math inline">\(s_{\epsilon}\)</span> liten, <span class="math inline">\(R^2\)</span> er nær null, og <span class="math inline">\(F\)</span>-observatoren er stor. Det er greit nok, <strong>men</strong> de har en ekstra kolonne som slår fast at regresjonsmodellen er <em>good</em>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Her menes det <strong>ikke</strong> at regresjonsmodellen er <em>god</em> i den forstand at vi skal reagere med glede eller lettelse (slik noen gjerne gjør), men at variasjonen i datamaterialet i stor grad lar seg forklare av modellen vår. I et tenkt eksempel der den sanne sammenhengen mellom <span class="math inline">\(Y\)</span> og <span class="math inline">\(X\)</span> er gitt ved <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>, men der <span class="math inline">\(\beta_1\)</span> er forholdsvis liten og <span class="math inline">\(s_{\epsilon}\)</span> er relativt stor, vil f.eks. <span class="math inline">\(R^2\)</span> bli <em>liten</em>, selv om den enkle lineære regresjonsmodellen repsesenterer sannheten og av alle tenkende mennesker må sies å være <em>god</em>.</p>
</blockquote>
<blockquote class="blockquote">
<p>Det er desverre mange lærebøker som blander disse to fortolkningene, ikke gjør det!</p>
</blockquote>
<p>Her er enda noen grunnleggende begreper. Har du fått med deg dette?</p>
<ol type="1">
<li>Hva mener vi med at en observasjon er innflytelsesrik?</li>
<li>Hva er grunnen til at vi trenger <em>justert</em> <span class="math inline">\(R^2\)</span> med flere forklaringsvariable?</li>
<li>Hva er forskjellen på <em>perfekt</em> og <em>tilnærmet</em> multikolinearitet i lineær regresjon? Hva blir konsekvensen i hvert av tilfellene?</li>
<li>Kan du gi en praktisk og intuitiv forklaring på hvorfor multikolinearitet nødvendigvis må være et problem?</li>
<li>Hva er forskjellen på statistisk og økonomisk signifikans? Kan du sette opp konkrete eksempler der vi kan estimere statistisk signifikante, men ikke økonomisk signifikante effekter i multippel regresjon? Hva med den motsatte situasjonen, økonomisk signifikant, men ikke statistisk signifikant?</li>
</ol>
<p>Grunnleggende ferdigheter: Klarer du dette?</p>
<ol type="1">
<li>Bruke R til å tilpasse en multippel regresjonsmodell for et datasett?</li>
<li>Bruke R til å finne særlig innflytelsesrike observasjoner?</li>
<li>Tolke en multippel regresjonsutskrift?</li>
</ol>
</section>
</section>
<section id="modellbygging" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="modellbygging"><span class="header-section-number">4.3</span> Modellbygging</h2>
<section id="videoforelesninger-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="videoforelesninger-2">Videoforelesninger</h3>
<div style="padding:75.21% 0 0 0;position:relative;">
<iframe src="https://vimeo.com/showcase/7793253/embed" allowfullscreen="" frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;">
</iframe>
</div>
</section>
<section id="kommentarer-2" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="kommentarer-2"><span class="header-section-number">4.3.1</span> Kommentarer</h3>
<p>Kapittel <strong>18</strong> dekker de grunnleggende begrepene innen modellbygging. I kap. <strong>18.1</strong> snakkes det om polynomiske modeller, i kap. <strong>18.2</strong> behandles dummyvariabler. Kapittel <strong>18.3</strong> og <strong>18.4</strong> handler om hvordan vi i praksis kan jobbe for å velge ut variable i en gitt situasjon. Forelesningene dekker i grunn greit det vi skal få med oss her. Som en sjekk om du har fått med deg det vesentlige, kan du svare på følgende spørsmål:</p>
<ol type="1">
<li>Vi har lært tre typer log-transformasjoner. Hva blir fortolkningen av koeffisientene for hver av disse?</li>
<li>Kan du nevne tre gode grunner til at log-transformasjoner er nyttige?</li>
<li>Hvorfor sier vi at følgende modell er lineær? <span class="math inline">\(Y = \beta_0 + \beta_1X + \beta_1X^2 + \epsilon\)</span></li>
<li>Vil vi ikke få problemer med multikolinearitet i modellen over?</li>
<li>Nevn en veldig god grunn til at vi må være ytterst forsiktig med polynomtransformasjoner.</li>
<li>Hva er en dummyvariabel?</li>
<li>Hva er fortolkningen av regresjonskoeffisienten til en dummyvariabel?</li>
<li>Hva er fortolkningen av regresjonskoeffisienten til et interaksjonsledd mellom målevariabelen <span class="math inline">\(X\)</span> og dummyvariabelen <span class="math inline">\(D\)</span>?</li>
<li>Et utrolig viktig poeng, men bruk tid til å tenke over og formulere et svar: Hvorfor er det viktig å tenke på <em>multippel testing</em> i sammenheng med <em>variabelutvelgelse</em>?</li>
</ol>
<p>Grunnleggende ferdigheter: Klarer du dette?</p>
<ol type="1">
<li>Bruke logtransformasjoner i R?</li>
<li>Bruke poynomtransformasjner i R?</li>
<li>Sette opp en fornuftig regresjonsmodell ved å ta utgangspunkt i et datasett og et analyseformål, og argumentere godt for dine valg? <strong>Denne ferdigheten har blitt testet på hver eneste hjemmeeksamen i manns minne!</strong></li>
</ol>
</section>
</section>
<section id="oppgaver" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="oppgaver"><span class="header-section-number">4.4</span> Oppgaver</h2>
<section id="regresjon-med-en-forklaringsvariabel" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="regresjon-med-en-forklaringsvariabel"><span class="header-section-number">4.4.1</span> Regresjon med en forklaringsvariabel</h3>
<section id="oppgave-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-1">Oppgave 1</h4>
<p>Forskere har brukt statistikk til å undersøke om TV-titting er forbundet med overvekt. De har samlet inn data fra 15 10-åringer om antall timer TV-titting per uke og antall kilo overvekt hos barnet (rapportert som differanse fra normalvekt). De innsamlede dataene er oppsummert i tabellen:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">TV_titting</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Overvekt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">42</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="even">
<td style="text-align: center;">35</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">28</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="even">
<td style="text-align: center;">34</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">37</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="even">
<td style="text-align: center;">38</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">32</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">33</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">18</td>
<td style="text-align: center;">-7</td>
</tr>
<tr class="even">
<td style="text-align: center;">28</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">36</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">29</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">29</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">34</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">18</td>
<td style="text-align: center;">-5</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>Bruk R til å lage et spredningsplott av resultatene. Hva tror du om forholdet mellom de to variablene utfra figuren?</p></li>
<li><p>Sett opp regresjonsuttrykket for å undersøke om overvekt er forbundet med TV-titting. La overvekt være responsvariabelen. Hva er betydningen av hver parameter i uttrykket?</p></li>
<li><p>Bruk R til å estimere parameterne. Hva kan koeffisientene fortelle deg om forholdet mellom overvekt og TV-titting?</p></li>
<li><p>Beregn et 95 % konfidensintervall for <span class="math inline">\(\beta_1\)</span>. Hint: Bruk ‘summary()’ på regresjonsmodellen for å finne <span class="math inline">\(S(\hat{\beta}_1)\)</span> som da gitt i kolonnen “Std. Error”.</p></li>
<li><p>Bruk R til å beregne et 95 % prediksjonsintervall for overvekt i kilo for et barn som ser på TV 30 timer i uken. Hva forteller intervallet deg?</p></li>
<li><p>Bruk R til å beregne et 95 % konfidensintervall for gjennomsnittlig overvekt for barn som ser 30 timer på TV i uken. Hvordan er tolkningen av dette intervallet forskjellig fra det i oppgave d?</p></li>
<li><p>Hva er forventet overvekt for barn som ser 0 timer på TV i uken utfra modellen? Hva kan være problematisk ved å gjøre denne type analyser av en regresjonsmodell?</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<div>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df_tv <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">TV_titting =</span> <span class="fu">c</span>(<span class="dv">42</span>, <span class="dv">35</span>, <span class="dv">28</span>, <span class="dv">34</span>, <span class="dv">37</span>, <span class="dv">38</span>, <span class="dv">32</span>, <span class="dv">33</span>, <span class="dv">18</span>, <span class="dv">28</span>, <span class="dv">36</span>, <span class="dv">29</span>, <span class="dv">29</span>, <span class="dv">34</span>, <span class="dv">18</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Overvekt =</span> <span class="fu">c</span>(<span class="dv">17</span>,  <span class="dv">5</span>, <span class="sc">-</span><span class="dv">1</span>,  <span class="dv">0</span>, <span class="dv">13</span>, <span class="dv">15</span>,  <span class="dv">5</span>,  <span class="dv">7</span>, <span class="sc">-</span><span class="dv">7</span>,  <span class="dv">7</span>,  <span class="dv">6</span>,  <span class="dv">7</span>,  <span class="dv">4</span>, <span class="dv">15</span>, <span class="sc">-</span><span class="dv">5</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_tv<span class="sc">$</span>TV_titting, df_tv<span class="sc">$</span>Overvekt, <span class="at">type =</span> <span class="st">"p"</span>, <span class="at">xlab=</span><span class="st">"TV-titting"</span>, <span class="at">ylab=</span><span class="st">"Overvekt"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Plottet viser en ganske tydelig trend om at TV-titting og overvekt er relaterte. Dette kan vi undersøke nærmere.</p>
</blockquote>
<ol start="2" type="a">
<li></li>
</ol>
<blockquote class="blockquote">
<p>Vi setter overvekt som responsvariabel og TV-titting som forklaringsvariabel. Uttrykket blir da:</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math display">\[\begin{equation}
  \text{Overvekt} = \beta_0 + \beta_1 \text{TV-titting} + \epsilon
\end{equation}\]</span></p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li><p>Ser vi bort fra dataene ville <span class="math inline">\(\beta_0\)</span> være forventet overvekt for personer som ikke ser på tv. Av spredningsplottet ser det derimot ut som at vi ikke har data ved 0 TV-titting og det er derfor ikke fornuftig med en direkte tolkning av denne parameteren.</p></li>
<li><p>Under antagelsen om at regresjonsmodellen er gyldig forteller <span class="math inline">\(\beta_1\)</span> hvor mye vi forventer at overvekten øker dersom man øker TV-tittingen med 1 time.</p></li>
</ul>
</blockquote>
<ol start="3" type="a">
<li></li>
</ol>
<blockquote class="blockquote">
<p>Vi estimerer en regresjonsmodell fra dataene og skriver ut tabellen med resultatene:</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(Overvekt <span class="sc">~</span> TV_titting, df_tv)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Overvekt ~ TV_titting, data = df_tv)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.1917 -2.6147  0.2795  2.6785  6.8083 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22.2124     5.1359  -4.325 0.000824 ***
TV_titting    0.8942     0.1602   5.583 8.88e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.026 on 13 degrees of freedom
Multiple R-squared:  0.7057,    Adjusted R-squared:  0.683 
F-statistic: 31.17 on 1 and 13 DF,  p-value: 8.88e-05</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For en finere utskrift kan du bruke følgende:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(stargazer)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer(reg, type="text")</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote class="blockquote">
<p>Det er tydelig sigifikans for at hver av parameterne er ulik null. For <span class="math inline">\(\beta_1\)</span> betyr dette at trenden vi observerte i spredningplottet var signifikant. Videre kan vi tolke det positive fortegnet til <span class="math inline">\(\beta_1\)</span> som at flere timer TV-titting er relatert med økt overvekt.</p>
</blockquote>
<blockquote class="blockquote">
<p>Merk at vi <em>ikke</em> kan si utfra dataene at mer TV-titting <em>fører til</em> overvekt. En mer riktig tolkning er å si at de forekommer samtidig i populasjonen. (Dersom vi ønsket å finne ut av kausaliteten måtte man på et tilfeldig utvalg av barn satt noen til å se mye på TV og noen til å se mindre på TV, og deretter undersøkt om dette resulterte i statistisk signifikant høyere overvekt hos en av gruppene. Dette krysser imidlertid noen etiske grenser om å påføre barn overvekt, dersom hypotesen er sann.)</p>
</blockquote>
<blockquote class="blockquote">
<ol start="4" type="a">
<li></li>
</ol>
<p>Fra R utskriften ser vi at <span class="math inline">\(S(\hat{\beta}_1)=0.1602\)</span>. Videre er <span class="math inline">\(t_{0.025, 13} = 2.16\)</span>. Et 95 % konfidensintervall for <span class="math inline">\(\beta_1\)</span> er da gitt ved:</p>
</blockquote>
<p><span class="math display">\[\left[\hat{\beta}_1 - t_{\alpha/2, n - 2}S(\hat{\beta}_1),  \hat{\beta}_1 + t_{\alpha/2, n - 2}S(\hat{\beta}_1)\right]\\
=\left[0.8942 - 2.16\times0.1602,  0.8942 + 2.16\times0.1602\right]\\
=\left[0.5481, 1.2402\right]\]</span> e)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>reg.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">TV_titting =</span> <span class="fu">c</span>(<span class="dv">30</span>)), <span class="at">interval =</span> <span class="st">"predict"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>reg.pred</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit       lwr      upr
1 4.614735 -4.380262 13.60973</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer(reg.pred, type="text")</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote class="blockquote">
<p>Dersom vi trekker et nytt barn som ser 30 timer på TV per uke, vil barnet i 95 % av tilfellene være innenfor prediksjonsintervallet dersom vi hadde gjentatt dette mange ganger.</p>
</blockquote>
<ol start="6" type="a">
<li></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reg.conf <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">TV_titting =</span> <span class="fu">c</span>(<span class="dv">30</span>)), <span class="at">interval =</span> <span class="st">"confidence"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg.conf</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 4.614735 2.317582 6.911888</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#evt </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(stargazer)</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer(reg.conf, type="text")</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote class="blockquote">
<p>Konfidensintervallet viser hvor <em>gjennomsnittet</em> av målinger på <em>et nytt sett</em> med barn som ser 30 timer på TV per uke vil ligge i 95 % av nye eksperimenter.</p>
</blockquote>
<ol start="7" type="a">
<li></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>reg.zero <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">TV_titting =</span> <span class="fu">c</span>(<span class="dv">0</span>)), <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>reg.zero</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        fit       lwr      upr
1 -22.21237 -36.30997 -8.11477</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># evt</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(stargazer) </span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># stargazer(reg.zero, type="text")</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote class="blockquote">
<p>Beste gjetning er at barn som ser 0 timer på TV i uken er 22.2 kg under normalvekt (!). Et kjapt søk viser at barn på 10 år veier mellom 25.5 og 39 kg. Det høres urimelig ut at veldig lite TV-titting har sammenheng med ekstrem underernæring blant den samme populasjonen av barn som ser rundt 30 timer på TV i uken.</p>
<p>Det er flere ting som kan gå galt når man gjør en slik analyse av en modell:</p>
<ul>
<li><p>Modellen kan være gal. Vi antar et lineær forhold mellom TV-titting og overvekt, noe som ikke trenger å være riktig ved 0 timer TV-titting.</p></li>
<li><p>Datasettet dekker ikke den gruppen barn som ser 0 timer på TV, så med mindre modellen er helt riktig (noe den sjelden er) vil den ikke kunne generalisere så langt utenfor området vi estimerte parameterne på.</p></li>
<li><p>Med mindre forholdet mellom TV-titting og overvekt er kausalt, kan det være at sammenhengen som er observert mellom dem i dataene ikke vil være det samme langt utenfor det aktuelle data-området.</p></li>
</ul>
</blockquote>
</div>
</details>
</section>
<section id="oppgave-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-2">Oppgave 2</h4>
<p>Vi skal undersøke om alder har sammenheng med hvor lang tid man bruker på et puslespill. Vi har data fra et tilfeldig utvalg av 210 voksne personer om alder og tid brukt på oppgaven. Uttrykk alder som <span class="math inline">\(X\)</span> og tid i minutter som <span class="math inline">\(Y\)</span>. Følgende deskriptive statistikker er beregnet for datasettet: <span class="math inline">\(s_{xy}= 8,   s_x^2, = 110,   s_y^2 = 42, \bar{x} = 40,   \bar{y} = 20\)</span> hvor <span class="math inline">\(\bar{x},\bar{y}\)</span> er gjennomsnittene.</p>
<ol type="a">
<li><p>Sett opp regresjonsuttrykket for sammenhengen mellom <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span> og støy <span class="math inline">\(\epsilon\)</span>. Hva er antagelsen for sammenhengen mellom X og <span class="math inline">\(\epsilon\)</span>?</p></li>
<li><p>Hva er uttrykket for beste gjetning/prediksjon <span class="math inline">\(\hat{Y}_i\)</span> gitt en verdi av forklaringsvariabelen <span class="math inline">\(X_i\)</span> for regresjonsmodellen du har satt opp? Hva er uttrykket for residualene?</p></li>
<li><p>Vis at hva uttrykket for regresjonsparameterne blir når de estimeres med minste kvadraters metode. Regn ut minste kvadraters estimat av parameterne.</p></li>
</ol>
<!-- d. Gi en tolkning av koeffisientene.

e. Er det nok evidens til at vi kan hevde at det er en sammenheng mellom alder og tid? Bruk 95 % signifikansnivå. 

f. Estimer et 90 % konfidensintervall av gjennomsnittlig tid brukt på oppgaven for en 50-åring. -->
<details>
<summary>
Løsning
</summary>
<div>
<ol type="a">
<li>Regresjonsuttrykket er <span class="math display">\[\begin{equation}
Y = \beta_0 + \beta_1 X + \epsilon
\end{equation}\]</span></li>
</ol>
<p>Vi antar at forklaringsvariabelen <span class="math inline">\(X\)</span> er uavhenging støyen <span class="math inline">\(\epsilon\)</span>. Dermed vil også kovariansen være null, <span class="math display">\[\begin{equation}
  \text{Cov}(X, \epsilon) = 0.
\end{equation}\]</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p>Beste gjetning er forvetningen betinget på utfallet av forklaringsvariabelen <span class="math inline">\(X\)</span>: <span class="math display">\[\begin{align}
  \hat{Y}_i &amp;= E[Y|X = X_i] = E[\beta_0 + \beta_1 X + \epsilon|X = X_i] \\
  &amp;= \beta_0 + \beta_1 X_i + E[\epsilon|X = X_i] \\
  &amp;= \beta_0 + \beta_1 X_i + E[\epsilon] \\
  &amp;= \beta_0 + \beta_1 X_i
\end{align}\]</span></p>
<p>Residualene er forskjellen mellom data og prediksjon</p>
<p><span class="math display">\[\begin{equation}
  r_i = \hat{Y}_i - Y_i
\end{equation}\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>Minste kvadraters metode minimerer summen av residualene kvadrert, så <span class="math display">\[\begin{align}
  SSE &amp;= \sum_{i} r_i^2 \\
  &amp;= \sum_{i} (\beta_0 + \beta_1 X_i - Y_i)^2.
\end{align}\]</span></p>
<p>Minimér ved å sette den deriverte for hver parameter til null: <span class="math display">\[\begin{align}
  \frac{dSSE}{d\beta_0} &amp;= \sum_{i} 2 (\beta_0 + \beta_1 X_i - Y_i) \overset{!}{=} 0 \\
  \implies \quad \beta_0 &amp;+ \beta_1 \frac{\sum_{i} X_i}{N} = \frac{\sum_{i} Y_i}{N} \\
  \implies \quad \beta_0 &amp;= \frac{\sum_{i} Y_i}{N} -  \beta_1 \frac{\sum_{i} X_i}{N},
\end{align}\]</span> og <span class="math display">\[\begin{align}
  \frac{dSSE}{d\beta_1} &amp;= \sum_{i} 2 (\beta_0 + \beta_1 X_i - Y_i)X_i \\
  &amp;= 2 \beta_0 \sum_{i} X_i + 2 \beta_1 \sum_{i} X_i^2 - 2\sum_{i} X_i Y_i \overset{!}{=} 0 \\
  &amp;\implies \quad \beta_0 \frac{\sum_{i} X_i}{N}  + \frac{\sum_{i} X_i^2}{N}  = \frac{\sum_{i} X_i Y_i}{N} .
\end{align}\]</span></p>
<p>Satt inn for <span class="math inline">\(\beta_0\)</span> blir det</p>
<p><span class="math display">\[\begin{align}
  \left ( \frac{\sum_{i} Y_i}{N} -  \beta_1 \frac{\sum_{i} X_i}{N} \right ) \frac{\sum_{i} X_i}{N}  + \beta_1\frac{\sum_{i} X_i^2}{N}  &amp;= \frac{\sum_{i} X_i Y_i}{N} \\
  \beta_1 \left ( \frac{\sum_{i} X_i^2}{N} -  \left ( \frac{\sum_{i} X_i}{N} \right )^2 \right ) &amp;= \frac{\sum_{i} X_i Y_i}{N} - \frac{\sum_{i} X_i}{N}\frac{\sum_{i} Y_i}{N} \\
  \beta_1 S_X^2 &amp;= S_{XY} \\
  \beta_1=\frac{S_{XY}}{S_X^2}
\end{align}\]</span></p>
<p>Da blir</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">/</span> <span class="dv">110</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>beta_1</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07272727</code></pre>
</div>
</div>
<p>og</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">-</span> beta_1 <span class="sc">*</span> <span class="dv">40</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>beta_0</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.09091</code></pre>
</div>
</div>
</div>
</details>
<!-- #### (Oppgave 1) {-}

Begrepet regresjon ble for første gang brukt i 1885 av Sir Francis Galton i analysen av forholdet mellom høyden til barn og deres foreldre. Han formulerte da ‘loven om universell regresjon’, som sier at “each peculiarity in a man is shared by his kinsmen, but on average in a less degree”. Dette kan oversettes til noe slikt som at en ekstrem egenskap hos en person er felles hos slektningen, men vanligvis av mindre ekstrem grad. Tenk deg en uvanlig høy far. Sønnen hans vil som oftest være høy han også, men ikke like høy. På samme måte kan vi tenke oss en uvanlig høy sønn, hvor faren sannsynligvis også er høy, men nærmere gjennomsnittet enn sønnen. Dette er betydningen av «regression towards the mean». 
I 1903 gjorde to statistikere, K. Pearson og A. Lee et tilfeldig utvalg av 1708 far-sønn par for å undersøke Galtons lov. Regresjonsuttrykket ble beregnet til å være følgende:

$$(\text{Sønns høyde}) = 33.73 + 0.516 (\text{Fars høyde})$$
(Pearson og Lee er briter, og har målt høyden i tommer.)

a. Hva er betydningen av koeffisientene? 
b. Hva forteller regresjonsuttrykket om høyden til sønner av høye fedre?
c. Hva forteller regresjonsuttrykket om høyden til sønner av lave fedre?
Husk: koeffisientene tilsvarer tallverdiene i regresjonsuttrykket.  

<details>
<summary>Løsning</summary>

a. Helningskoeffisienten forteller oss at for hver ekstra tomme av far høyde vil sønnens høyde gjennomsnittlig øke med 0.516 tommer. Konstantleddet gir her ingen spesiell innsikt, ettersom vi aldri vil få konstantleddet «alene» (det eksisterer ingen fedre som måler 0 tommer). 

b. Sønnen vil gjennomsnittlig være lavere enn sin far.

c. Sønnen vil gjennomsnittlig være høyere enn sin far. 

</details> -->
</section>
<section id="oppgave-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-3">Oppgave 3</h4>
<p>Figurene nedenfor viser residualene (feilleddene) vi får ut fra et par ulike modeller. Ser plottene ut til å tilfredsstille kravene for enkel regresjon? Hvis ikke, hva ser ut til å være galt for hver av figurene? Hvordan kan man håndtere brudd på betingelsene i de ulike situasjonene?</p>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/res1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/res2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/res3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="a">
<li></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/res4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<details>
<summary>
Løsning
</summary>
<blockquote class="blockquote">
<ol type="a">
<li><p>Her ser støyleddet ut som det har konstant varians og forventing lik null. Det betyr at antagelsene er oppfylt.</p></li>
<li><p>Støyen er symmetrisk om null, men kan se ut som den øker. Altså er det brudd på antagelsen om konstant varians. Økningen ser ut til å være jevn, og en log-transformasjon kunne i dette tilfellet vært til hjelp.</p></li>
<li><p>Her ser det ut som at vi har perioder med høy varians etterfulgt av perioder med lavere varians. Vi skal ikke se så mye nærmere på hvordan dette kan håndteres i MET4, men man kan komme over det i senere kurs.</p></li>
<li><p>Her ser det ut som at støyen har en relasjon i tid, og at høye/lave verdier henger sammen med høye/laver verdier. Det er ikke åpenbart at det er dette som foregår, og vi burde undersøkt det nærmere. Senere i kurset skal vi håndtere dette ved bruk av tidsrekkemodeller.</p></li>
</ol>
<p>Merk at det ikke alltid er lett å se direkte fra figurene hva som er galt. Riktig bruk av statistiske tester og diagnoseplott kan hjelpe med å oppdage brudd på betingelsene. Figurene i denne oppgaven er generert ved simulering, vi kan derfor vite akkurat hva som er galt. For virkelige data vil kunne være vanskeligere å tolke fordi det ikke nødvendigvis er én ting som er galt om gangen. Man må også være på vakt for overtolkning av det som egentlig er tilfeldigheter.</p>
</blockquote>
</details>
</section>
<section id="oppgave-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-4">Oppgave 4</h4>
<p>I en analyse skal en økonom teste om å ta høyere utdanning fører til at arbeidstakere får høyere lønn i arbeidslivet. Hun kjører følgende regresjon, som tester sammenhengen mellom (log av) lønn fem år etter endt utdanning og antall år med utdanning, på individnivå:</p>
<p><span class="math display">\[ ln(\text{lønn}_i) = \beta_0+\beta_1\text{antall år med utdanning}_i+\epsilon_i \]</span></p>
<ol type="a">
<li><p>Er det grunn til å være bekymret for utelatt variabelskjevhet her? I hvilken retning påvirker den i så fall koeffisienten <span class="math inline">\(\beta_1\)</span>?</p></li>
<li><p>Økonomen argumenterer for at <span class="math inline">\(\beta_1\)</span> måler hvor mye høyere lønn en arbeidstaker får, dersom den tar ett års ekstra utdanning. Er dette en rimelig tolkning?</p></li>
<li><p>Hvordan ville du tolket <span class="math inline">\(\beta_1\)</span>?</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote class="blockquote">
<p>Dette er ment som en refleksjonsoppgave, og har ikke nødvendigvis én fasit. Under er noen momenter det kan være naturlig å trekke frem.</p>
<ol type="a">
<li><p>Det kan tenkes at det er forskjell i karakteristikkene på personer som tar høyere utdanning. De for eksempel være mer akademisk/analytisk anlagte, eller ha foreldre med bedre økonomi. Dette er også faktorer som bidrar til at lønnen kan bli høyere. Det er altså utelatte variabler her som er positivt korrelert med både forklaringsvariabelen (lengde på utdanning) og utfallsvariabelen (lønn), og som dermed trekker <span class="math inline">\(\beta_1\)</span> opp.</p></li>
<li><p>Nei, dette er ikke en rimelig tolkning. Eksogenitetsantakelsen er brutt når vi har utelatte variabler, og her fanger koeffisienten opp mer enn bare effekten av ett års ekstra utdanning på arbeidstakerens lønn.</p></li>
<li><p>Koeffisienten <span class="math inline">\(\beta_1\)</span> kan tolkes som at ett års ekstra utdanning er <em>assosiert med</em> $_1 $ % høyere lønn. Alternativt kan man for eksempel si at arbeidstakere med ett år lengre utdanning <em>i gjennomsnitt</em> har <span class="math inline">\(\beta_1\)</span> % høyere lønn enn de som ett år kortere utdanning. Merk at vi her tolker <span class="math inline">\(\beta_1\)</span> som prosent fordi vi har tatt logaritmen av utfallsvariabelen, og dermed får en (tilnærmet) prosentvis endring.</p></li>
</ol>
</blockquote>
</details>
</section>
</section>
<section id="multippel-regresjon-og-modellbygging" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="multippel-regresjon-og-modellbygging"><span class="header-section-number">4.4.2</span> Multippel regresjon og modellbygging</h3>
<section id="oppgave-1-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-1-1">Oppgave 1</h4>
<p>Denne oppgaven skal gi et forhold til hvordan teorien funker i praksis. Vi skal simulere data fra konstruerte modeller gjøre analyser på dem. Fordelen med å begynne her er at man får er forhold til hvordan statistikk kan og bør tolkes utfra teorien. Med virkelige data vil antagelsene som ligger til grunn for modellene stort sett være brutt, i større eller mindre grad, og kjernen i god statistisk analyse er å vite hva man kan og ikke kan gjøre likevel. God kjennskap til hvordan det burde funke i teorien er en viktig byggestein for statistisk forståelse.</p>
<p>Vi generer opp data som skal brukes til å estimere en model. <code>rnorm</code> trekker tall fra en standard normalfordeling. <code>mutate()</code> legger til nye kolonner i dataframe-en basert på allerede eksisterende kolonner. <code>set.seed()</code> setter startpunktet for pseudotilfeldige tall, og om du setter samme seed får du de samme tilfeldige tallene som vi har brukt.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>df_mdl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">2</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">2</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">eps =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>) </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="dv">2</span> <span class="sc">*</span> x1 <span class="sc">+</span> (<span class="sc">-</span><span class="dv">1</span>) <span class="sc">*</span> x2 <span class="sc">+</span> eps</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol type="a">
<li><p>Hva er de eksakte parameterne i modellen som passer til dataene vi har generert, og hva er fordelingen til hver av forklaringsvariablene og støy-leddet? Er betingelsen om uavhengig feilledd oppfylt?</p></li>
<li><p>Generér opp dataene selv og estimer parameterne basert på dataene. Tolk estimatene.</p></li>
<li><p>Lag 95 % konfidens- og prediksjonsintervaller for en prediksjon hvor <span class="math inline">\(X_1=1, X_2=1\)</span> basert på estimatene dine.</p></li>
<li><p>Hva er eksakt prediksjonsintervall basert på modellen vi har generert data fra? Ser dine prediksjonsintervaller rimelige ut utfra dette? Hvorfor er de ikke eksakt like?</p></li>
<li><p>Stemmer konfidensintervallet overens med modellen? Tolk konfidensintervallet basert på at vi kan generere opp nye data (med et annet seed).</p></li>
<li><p>Hva er P-verdien i F-test for at vi har en signifikant sammenheng mellom responsvariabelen og forklaringsvariablene?</p></li>
</ol>
<!-- f. Hvor få datapunkter måtte vi ha simulert opp før F-testen ikke kunne sagt at det er en sammenheng? -->
<details>
<summary>
Løsning
</summary>
<blockquote class="blockquote">
<ol type="a">
<li><p>Fordelingen til forklaringsvariablene er <span class="math display">\[\begin{align}
  X_1, X_2 \sim N(0, 2)
\end{align}\]</span> fordi vi har trukket dem fra en normalfordeling med forventning 0 og standardavvik 2. Videre er fordelingen til støyleddet en standard normalfordeling <span class="math inline">\(\epsilon\sim N(0,1)\)</span>. Betingelsen om uavhengig feilledd er oppfylt siden vi ikke har brukt feilleddet til å generere forklaringsvariablene. Det er responsvariabelen, men den skal altså være avhengig av støyleddet. Modellen tar formen <span class="math display">\[\begin{align}
  Y = 2 X_1 - X_2 + \epsilon,\quad \epsilon \sim N(0, 1),
\end{align}\]</span> hvor parameterne er eksakt fordi vi har laget dataene selv.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> df_mdl)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                                 y             
-----------------------------------------------
x1                           1.986***          
                              (0.053)          
                                               
x2                           -1.091***         
                              (0.048)          
                                               
Constant                      -0.055           
                              (0.096)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.958           
Adjusted R2                    0.957           
Residual Std. Error       0.956 (df = 97)      
F Statistic          1,094.997*** (df = 2; 97) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Vi ser at estimatene av koeffisientene er signifikante, og at sanne verdier er innenfor konfidensintervallet for hver av dem. Det er ikke et konstantledd i modellen vår, noe som stemmer overens med at den ikke er signifikant forskjellig fra null i regresjonsmodellen.</p>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>new_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="dv">1</span>, <span class="at">x2 =</span> <span class="dv">1</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reg_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata =</span> new_df, <span class="at">interval =</span> <span class="st">"predict"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>reg_conf <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata =</span> new_df, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Prediksjonsintervall
====================
   fit   lwr    upr 
--------------------
1 0.840 -1.073 2.752
--------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Konfidensintervall
===================
   fit   lwr   upr 
-------------------
1 0.840 0.600 1.080
-------------------</code></pre>
</div>
</div>
<ol start="4" type="a">
<li><p>Eksakt prediksjonsintervall for modellen som genererte dataene er <span class="math display">\[\begin{align}
  \bar{Y}|X_1,X_2 \pm \alpha_{0.025} \sigma_{\epsilon} &amp;= 2 \cdot 1 - 1 \cdot 1 \pm 1.96 \cdot 1 \\
  &amp;= 1 \pm 1.96 \\
  &amp;= [-0.96, 2.96].
\end{align}\]</span> Estimert prediksjonsintervall er bredere enn det estimerte intervallet. Dette kommer av usikkerhet knyttet til estimatene av forventning og standardfeil. Det er benyttet T-test i estimatet av prediksjonsintervallet for å ta hensyn til denne usikkerheten. Man burde ikke få smalere prediksjonsintervaller enn det som faktisk er “sant” med mindre noen av modellantagelsene er usann. Merk at når vi generer opp data selv vet vi sannheten, det gjør vi ikke for virkelige data.</p></li>
<li><p>Vi burde få at <span class="math inline">\(\bar{Y}|X_1,X_2 = 1\)</span> er innenfor konfidensintervallet, noe ser ut til å være oppfylt. Tolkningen er at dersom vi kjører analysen på mange ulike datasett vil <span class="math inline">\(\bar{Y}|X_1,X_2 = 1\)</span> havne innenfor konfidensintervallet i 95 % av tilfellene. Dette kan du prøve selv, bare pass på at du ikke setter seed-et før du generer opp et nytt datasett.</p></li>
<li><p>Svaret gis i regresjonstabellen</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                                 y             
-----------------------------------------------
x1                           1.986***          
                              (0.053)          
                                               
x2                           -1.091***         
                              (0.048)          
                                               
Constant                      -0.055           
                              (0.096)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.958           
Adjusted R2                    0.957           
Residual Std. Error       0.956 (df = 97)      
F Statistic          1,094.997*** (df = 2; 97) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>F-statistikken er angitt som <span class="math inline">\(1094.997\)</span> med frihetsgrader <span class="math inline">\(2, 97\)</span>. P-verdien regnes som</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(<span class="fl">1094.997</span>, <span class="dv">2</span>, <span class="dv">97</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.716911e-67</code></pre>
</div>
</div>
som er veldig liten. Altså bekrefter analysen at det er sammenheng mellom forklaringsvariablene og responsvariabelen. Hva ville du tenkt var galt om vi ikke fikk denne konklusjonen fra F-testen, gitt den modellen vi har brukt til å generere dataene? Hint: Det er faktisk en reell sammenheng her.
</blockquote>
</details>
</section>
<section id="oppgave-2-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="oppgave-2-1">Oppgave 2</h4>
<p>Denne oppgaven følger samme premiss som oppgave 1, men handler om kolinearitet. Last ned datasettene <a href="genererte_datasett/colinearity_1.RData">1</a> og <a href="genererte_datasett/colinearity_2.RData">2</a>, hvor y er responsvariabel og forklaringsvariable er navngitt x.</p>
<p>Disse dataene er lagret som .RData filer. For å laste inn dataene i R laster du filene over ned i en mappe, setter mappestien til denne mappen og kjører følgende R-kommandoer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"colinearity_1.RData"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"colinearity_2.RData"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>Finn kolinearitet</p></li>
<li><p>Hva må man passe dersom man skal lage en regresjonsmodell for responsen Y?</p></li>
</ul>
<details>
<summary>
Løsning
</summary>
<blockquote class="blockquote">
<ol type="1">
<li></li>
</ol>
<p>Vi kan begynne med å plotte forholdet mellom de ulike variablene:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(y <span class="sc">~</span> ., <span class="at">data =</span> df_colin1)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(df_colin1), <span class="at">method =</span> <span class="st">"number"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Her ser det ut som vi har et forhold mellom <span class="math inline">\((X_2, X_3)\)</span>. Videre ser det ut som at alle tre forklaringsvariable har en sammenheng med responsvariablen <span class="math inline">\(Y\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>reg_colin1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> df_colin1)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg_colin1, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                                 y             
-----------------------------------------------
x1                           1.348***          
                              (0.053)          
                                               
x2                           -0.695***         
                              (0.064)          
                                               
x3                           -0.208**          
                              (0.102)          
                                               
Constant                      -0.095           
                              (0.097)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.916           
Adjusted R2                    0.913           
Residual Std. Error       0.960 (df = 96)      
F Statistic           346.946*** (df = 3; 96)  
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><span class="math inline">\(X_1\)</span> og <span class="math inline">\(X_2\)</span> kommer ut som signifikante, og <span class="math inline">\(X_3\)</span> ved lavere signifikansnivå.</p>
<p>Vi kan sjekke variance inflation factor (VIF)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(reg_colin1)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x1       x2       x3 
1.018945 1.785963 1.774712 </code></pre>
</div>
</div>
<p>som oppgir at estimeringen i seg selv ikke burde være noe problem.</p>
<p><strong>Kommentarer:</strong></p>
<p>Det reelle forholdet mellom variablene i dette eksempelet er <span class="math display">\[\begin{align}
  X_1 &amp;\sim N(0, 2) \\  
  X_2 &amp;\sim N(0, 2) \\  
  X_3 &amp;= 0.5 X_2 + \epsilon_3 \quad \epsilon_3 \sim N(0,1)  \\
  Y &amp;= 1.3 X_1 - 0.8 X_2 + \epsilon, \quad \epsilon \sim N(0,1),
\end{align}\]</span> og vi kan tenke oss at dette representerer det kausale forholdet mellom variablene. Siden vi har generert dataene kan vi si det.</p>
<p>Det er videre interessant å merke seg i dette eksempelet at <span class="math inline">\(X_3\)</span> kommer ut med en signifikant koeffisient selv om den rent kausalt ikke har noen sammenheng med <span class="math inline">\(Y\)</span>. <span class="math inline">\(X_3\)</span> er kun relatert til <span class="math inline">\(X_2\)</span>.</p>
<p>Dersom man ønsker å gjøre prediksjon kan det være forklaringskraft i <span class="math inline">\(X_3\)</span> for å gjøre prediksjon av <span class="math inline">\(Y\)</span>, men i så tilfelle antas det at forholdet mellom <span class="math inline">\((X_2, X_3)\)</span> også vedvarer i fremtiden. Dersom man skal gjøre inferens om en tenkt kausal sammenheng er det mulig å gå på en blemme i et tilfelle som dette.</p>
<p>Hvis man ønsker å forklare noe og det er sammenheng mellom to forklaringsvariable kan det fra økonomisk prespektiv være interessant å spørre seg om man bryr seg om <span class="math inline">\(X_3\)</span> i det hele tatt og skal ta den ut. Kanksje <span class="math inline">\(X_3\)</span> er vanskelig å samle inn data om eller den åpenbart ikke har sammenheng med Y. Om den åpenbart ikke skal ha sammenheng med <span class="math inline">\(Y\)</span> kan støyleddet <span class="math inline">\(\epsilon_3\)</span> også skape unødig støy i prediksjonene.</p>
<ol start="2" type="1">
<li></li>
</ol>
<p>Plott forholdet mellom de ulike variablene:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(y <span class="sc">~</span> ., <span class="at">data =</span> df_colin2)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(df_colin2), <span class="at">method =</span> <span class="st">"number"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresjon_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Her ser vi et tydelig forhold mellom parene <span class="math inline">\((X_3, X_4)\)</span>, <span class="math inline">\((X_4, X_5)\)</span>, <span class="math inline">\((X_3, X_5)\)</span> og <span class="math inline">\((X_2, X_5)\)</span>. Ellers ser det kun ut som det er et tydelig forhold mellom <span class="math inline">\(Y\)</span> og <span class="math inline">\(X_1, X_2\)</span>. Med så mange forhold kan det være snakk om multikolinearitet, som ikke er så lett å se utfra 2D-plott.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>reg_colin2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> df_colin2)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg_colin2, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                                 y             
-----------------------------------------------
x1                           2.049***          
                              (0.053)          
                                               
x2                           -1.179***         
                              (0.111)          
                                               
x3                            -0.198*          
                              (0.114)          
                                               
x4                            0.101**          
                              (0.050)          
                                               
x5                             0.092           
                              (0.097)          
                                               
Constant                      -0.018           
                              (0.095)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.963           
Adjusted R2                    0.961           
Residual Std. Error       0.932 (df = 94)      
F Statistic           486.175*** (df = 5; 94)  
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Vi ser på VIF for om det kan være problemer med estimering grunnet kolinearitet</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(<span class="fu">vif</span>(reg_colin2), <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">title =</span> <span class="st">"VIF"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
VIF
=============================
x1     x2    x3    x4    x5  
-----------------------------
1.062 5.731 5.517 1.662 7.769
-----------------------------</code></pre>
</div>
</div>
<p>hvor vi ser at <span class="math inline">\(X_5\)</span> nærmer seg problematisk område for å få en overdreven varians i estimatene.</p>
<p>Dersom målet er å estimere sammenheng mellom alle forklaringsvariable og <span class="math inline">\(Y\)</span> vil dette kunne gå gjennom siden VIF ikke er altfor høy. Hvis det derimot er snakk om modellbygging bør man tenke gjennom om noen av variablene ikke er så viktige og bør tas ut.</p>
<p><strong>Kommentarer:</strong></p>
<p>Det reelle forholdet mellom variablene i dette eksempelet er <span class="math display">\[\begin{align}
  X_1 &amp;\sim N(0, 2) \\  
  X_2 &amp;\sim N(0, 2) \\  
  X_3 &amp;\sim N(0, 2) \\
  X_4 &amp;= X_3 + \epsilon_4, \quad \epsilon_4 \sim N(0,2) \\
  X_5 &amp;= X_2 + X_3 + \epsilon_5, \quad \epsilon_5 \sim N(0,1) \\
  Y &amp;= 2 X_1 - X_2 + \epsilon, \quad \epsilon \sim N(0,1)
\end{align}\]</span></p>
<p>Her kan vi igjen merke oss at variablene <span class="math inline">\(X_3, X_4, X_5\)</span> kommer inn i regresjonsmodellen med noen koeffisienter som er svakt signifikante. I dette tilfellet trenger ikke dette ha så mye å si. Likevel, ettersom det ikke er noen direkte sammenheng mellom <span class="math inline">\(X_3, X_4, X_5\)</span> ville det vært ideelt å ikke ha dem med i regresjonsmodellen for å unngå feilestimering av koeffisientene til <span class="math inline">\(X_1\)</span> og <span class="math inline">\(X_2\)</span>. Fra anvendt statistikk perspektiv bør man tenke gjennom om det gir mening at <span class="math inline">\(X_3, X_4, X_5\)</span> forklarer <span class="math inline">\(Y\)</span>.</p>
</blockquote>
</details>
<!-- Generér gjerne opp dataene selv og analyser dem mens du svarer på oppgavene. -->
<!-- a. Er det uavhengige feilledd her? -->
<!-- b. Er det kolinearitet mellom forklaringsvariablene her? Om så, er den enkel eller har vi multikolinearitet? -->
<!-- c. Hva har svarene på oppgaven før å si for estimat av koeffisientene for modellen for Y? -->
<!-- <details> -->
<!-- <summary>Løsning</summary> -->
<!-- </details> -->
<!-- #### Oppgave 3 -->
<!-- I denne oppgaven skal vi se hva som kan gå galt dersom man leter etter signifikans i store datasett. Vi starter med å simulere en responsvariabel og en  -->
<!-- (Trekk tilfeldige tall og analyser det...) -->
<!-- (Dette er kjent som P-hacking. Det er *veldig* dårlig praksis, men har en tendens til å snike seg inn i analyser på mer eller mindre subtile vis. Det finnes store mengder forskning hvor P-hacking forekommer, bevisst eller ubevisst. De mindre subtile måtene dette skjer på heter juks. -->
<!-- Out-of-sample validering og testing  -->
<!-- ) -->
<!-- #### Oppgave 4 -->
<!-- (Legg til i enkel regresjon at man kan komme frem til det samme ved Cov-regning.) -->
<!-- Vi så i oppgave ... at minste kvadraters metode brukes til parameter-estimering. I multivariat regresjon får vi enda flere ligninger enn vi så for enkel regresjon, dermed bruker man lineæralgebra. -->
<!-- Vis at man kan regne minste kvadraters estimat ved kovarians. -->
<!-- En matrise lar seg invertere dersom den er kvadratisk og har lineært uavhengige kolonner. På matrisenotasjon blir kovarians regnet som $X^TX / N$.  -->
<!-- Dersom man har multikolinearitet er det kolonner i kovariansmatrisen som er sterkt lineært avhengige. Hvorfor blir det problematisk å  -->
<!-- <detail><summary>Løsning</summary> -->
<!-- </detail> -->
<!-- ### Case-studie med datasett -->
<!-- Her skal vi gå gjennom en analyse på et ofte brukt datasett: Boston Housing Data. Deloppgavene er satt opp for å gi litt drahjelp, sammenlignet med det som ellers kunne vært utgangspunktet for en hjemmeeksamen. -->
<!-- 
#### (Oppgave 1) {.unnumbered}

Studenten Rita Stata har som mål å gjennomføre et kurs i statistikk med minst mulig arbeid. Hun ligger foreløpig ikke så bra an, men ønsker å finne ut hva slags karakter hun forvente til slutt. Karakteren er basert på følgende beregning:
Karakter = 20 % (Assignment) + 30 % (Midterm test) + 50 % (Final exam)
Karakteren er et tall hvor 0 er lavest mulig og 100 er høyest mulig. 
Det er bare tre uker til eksamen, og på ‘assignment’ og ‘midterm test’ fikk Rita henholdvis 12/20 og 14/30 poeng. 
Rita samlet inn data over karakterer, og score på ‘midterm test’ og ‘assignment’ hos 30 tidligere studenter. Hun brukte deretter en statistikkprogramvare til å beregne et regresjonsuttrykk. Statistikkprogramvaren leverte følgende oppsummering:
 
![](bilder/4_regresjon/tbl_1.png){width=40em}

a. Hva er regresjonsuttrykket?

b. Hva er standardfeilen til målingen? Hva mener vi med standardfeil?

c. Hva er forklaringsgraden (bestemmelseskoeffisienten)? Hva forteller verdien oss?

d. Test validiteten av modellen. Dette gjøres ved hjelp av F-testen. 

e. Gi en tolkning av koeffisientene i modellen. 

f. Kan Rita anta at score på ‘assignment’ har et lineært forhold med karakter i statistikk?

g. Kan Rita anta at score på ‘midterm test’ har et lineært forhold med karakter i statistikk?

Husk: vi kaller ofte et regresjonsuttrykk for «modell». Dette er fordi regresjonsuttrykket i praksis fungerer som en modell, i dette tilfellet en modell som beregner karakter i statistikk. 

<details>
<summary>Løsning</summary>

</details>

#### (Oppgave 2) {.unnumbered}
Et stort konsulentselskap i USA prøver å lage et system for å avgjøre hvilke søkere til internship som skal bli innkalt til intervju. Søkerne har bare gått ett år på universitetet, så de ønsker å bruke en modell til å predikere hvilke karakterer de vil få på bachelorgraden. De tror at karakterene fra High School og SAT Score er de viktigste variablene for å avgjøre hvilke karakterer søkeren vil få på universitetet. De tror også at søkere som har deltatt i utenomfaglige aktiviteter har større sannsynlighet for å få gode karakterer. For å undersøke dette velger de et tilfeldig utvalg av 100 ansatte som har hatt suksess i selskapet og finner følgende informasjon om de ansatte:
Karakterer fra universitetet (0-12) 
Karakterer fra High School (0-12)
SAT Score (400-1600)
Antall timer brukt på utenomfaglige aktiviteter per uke 
Under finner du en utskrift av regresjon med disse variablene:

![](bilder/4_regresjon/tbl_2.png){width=40em}
 
a. Hva er regresjonsutrykket til modellen? Hva er den avhengige (Y) og de uavhengige variablene (X)?  

b. Hva er forklaringsgraden til modellen? Tolk verdien. 

c. Test validiteten til modellen ved å beskrive F-testen og resultatet av testen.

d. Bestem hvilke av de uavhengige variablene som er lineære i modellen ved å tolke t-statistikken og p-verdien til hver av koeffisientene. 

e. Hva er den predikerte karakteren på universitetet til en søker som har High School GPA 10, SAT score 1200 og arbeider 2 timer i gjennomsnitt med utenomfaglige aktiviteter i uken. Merk: selv om noen av koeffisientene ikke er statistisk signifikante så kan man gjøre prediksjoner med modellen. Ved prediksjon er vi mest opptatt av at forklaringsgraden er høy.

f. Hva er den predikerte karakteren på universitetet til en søker som har High School GPA 8, SAT score 1100 og arbeider 10 timer i gjennomsnitt med utenomfaglige aktiviteter i uken. 

g. Kausalitet og korrelasjon er et viktig tema i dette faget. Viser denne modellen en kausal sammenheng mellom karakterer på High School og karakterer på universitetet? 

<details>
<summary>Løsning</summary>

</details>

#### (Oppgave 3) {.unnumbered}

Vi undersøker om forutsetningene for OLS holder for modellen ovenfor. 

- Hvilke forutsetninger kan vi undersøke ved å studere de to diagrammene nedenfor? 

![](bilder/4_regresjon/hist_3.png){width=30em}

![](bilder/4_regresjon/res_vs_pred_3.png){width=30em}

- Vil du si at de aktuelle forutsetningene holder?

<details>
<summary>Løsning</summary>

</details>

#### (Oppgave 4) {.unnumbered}

- Hvordan tolker du diagrammene nedenfor?

- Holder forutsetningene for OLS?

a. 
![](bilder/4_regresjon/hist_4a.png){width=30em}
b. 
![](bilder/4_regresjon/res_vs_pred_4b.png){width=30em}
c.
![](bilder/4_regresjon/hist_4c.png){width=30em}

![](bilder/4_regresjon/res_vs_pred_4d.png){width=30em}

<details>
<summary>Løsning</summary>

a. Histogrammet er bjelle-formet og det kan se ut som at det er en normalfordeling.

b. Plottet viser tegn til heteroskedastisitet. Forutsetningen er ikke oppfylt. 

c. Histogrammet er skjevfordelt og forutsetningen om normalfordeling holder ikke.

d. Plottet viser tegn til heteroskedastisitet. Forutsetningen er ikke oppfylt.

</details>

#### (Oppgave 5) {.unnumbered}

a. Hva er konsekvensen av brudd på forutsetningen om konstant varians?

b. Hva er konsekvensen av brudd på forutsetningen om normalfordelte feilledd? 


<details>
<summary>Løsning</summary>



</details>

#### (Oppgave 6) {.unnumbered}

Et transportselskap ønsker å analysere hvordan ulike variabler påvirker hvor lang tid det tar å laste av lastebilene deres. I modellutskriften under vises resultatet av en modell hvor avhengig variabel er antall minutt det tar å laste av en lastebil. De uavhengige variablene er antall bokser og vekten på lasten. I tillegg ønsker transportselskapet å finne ut om tidspunktet på dagen påvirker hvor lang tid det tar å laste av bilene. De deler døgnet inn i tre: I1 = morgenen, I2 = tidlig ettermiddag og I3 = sen ettermiddag.
 
![](bilder/4_regresjon/tbl_6.png){width=40em}
 
a. Gi en kortfattet fortolkning av regresjonsutskriften over.

b. Det er mistanke om multikollinearitet i modellen. Hvilke to variabler tror du kan samvariere? 

c. Hvorfor er ikke l3 i regresjonsutskriften? 

d. Hva kan vi si om betydningen av tidspunktet på dagen og hvor lang tid det tar å laste av lastebilene? 

e. Tegn regresjonslinjen til modellen. 

<details>
<summary>Løsning</summary>

</details> -->
</section>
</section>
</section>
<section id="sec-relevante-r-regresjon" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-relevante-r-regresjon"><span class="header-section-number">4.5</span> Relevante R-kommandoer</h2>
<p>Under følger en liste over hvilke oppgaver du skal klare i R fra denne modulen. Vår policy er at R-kommandoene under er <em>tilstrekkelige</em> for å løse oppgavene i datalabber og eksamen i MET4. Det er med andre ord ikke nødvendig å lære seg teknikker utover det som er listet opp eksplisitt i listen under. Eventuelle nye teknikker som trengs for å løse en bestemt oppgave vil bli oppgitt og forklart dersom det er nødvendig. Det antas i tillegg at du kan den grunnleggende R-syntaksen som er dekket under [Introduksjon til R].</p>
<section id="tilpasse-en-lineær-regresjonsmodell" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="tilpasse-en-lineær-regresjonsmodell">Tilpasse en lineær regresjonsmodell</h3>
<p>Her er et lekedatasett med tre forklaringsvariabler <code>x1</code>, <code>x2</code> og <code>x3</code>, samt en responsvariabel <code>y</code>: <a href="datasett/data-reg.xlsx">data-reg.xsls</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Last inn data</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data-reg.xlsx"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Syntaksen for å tilpasse en lineær regresjonsmodell med responsvariabel y og</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># forklaringsvariabler x1, x2, x3 i datasettet df er som følger:</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> df)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Dersom vi vil ha med interaksjonsledded mellom x1 og x3 kan vi skrive</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># kommandoen under. Da vil også x1 og x3 automatisk bli med som variabler i</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># tillegg til interaksjonsledde x1*x3.</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2<span class="sc">*</span>x3, <span class="at">data =</span> df)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Log transformasjoner kan vi skrive rett inn i formelen</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(y) <span class="sc">~</span> x1 <span class="sc">+</span> <span class="fu">log</span>(x2) <span class="sc">+</span> x3, <span class="at">data =</span> df)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Andre transformasjoner, som for eksempel dersom vi ønsker å ta med</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a><span class="co"># andregradsleddet x1^2, er greiest å få til dersom vi først lager en ny kolonne</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="co"># med kvadratene til x1, og så lager til regresjonen på vanlig måte:</span></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>df_ny <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">x1_kvadrat =</span> x1<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x1_kvadrat<span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> df_ny)</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Vi kan skrive ut et sammendrag for regresjonsmodellen ved hjelp av summary():</span></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Pakken stargazer inneholder en funksjon for å lage pene regresjonstabeller:</span></span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg1, reg2, <span class="at">type =</span> <span class="st">"text"</span>)</span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Man kan endre type-argumentet til "html", og sette out-argumentet til et</span></span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a><span class="co"># filnavn hvis du vil skrive ut tabellen til en fil.</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="prediksjoner-med-konfidens--og-prediksjonsintervall" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="prediksjoner-med-konfidens--og-prediksjonsintervall">Prediksjoner, med konfidens- og prediksjonsintervall</h3>
<p>La oss si at vi ønsker å predikere verdien av responsvariabelen for følgende verdier av forklaringsvariablene:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">x1</th>
<th style="text-align: right;">x2</th>
<th style="text-align: right;">x3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">30</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Da må vi først samle verdiene av forklaringsvariablene i en data frame; det kan vi enten gjøre direkte i R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>ny_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>), <span class="at">x2 =</span> <span class="fu">c</span>(<span class="dv">95</span>, <span class="dv">96</span>, <span class="dv">100</span>), <span class="at">x3 =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Et alternativ kan være å lage til et regneark i Excel, og så lese det inn ved hjelp av <code>read_excel()</code>. <strong>Det er viktig at variabelnavnene i det nye datasettet er eksakt de samme som forklaringsvariablene i datasettet du brukte til å estimere regresjonsmodellen!</strong> Vi kan lage prediksjon med 95% konfidensintervall ved hjelp av <code>predict()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>prediksjoner <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg1, </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">newdata =</span> ny_data, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">interval =</span> <span class="st">"confidence"</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Resultatet blir en ny data frame med kolonnene <code>fit</code> (prediksjoner), samt <code>lwr</code> og <code>upr</code>, som inneholder nedre og øvre grense i konfidensintervallet henholdsvis. Du kan endre til prediksjonsintervaller ved å bytte ut <code>"confidence"</code> med <code>"prediction"</code> (eventuelt <code>"none"</code> hvis du ikke ønsker noe intervall).</p>
</section>
<section id="lage-residualplott" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="lage-residualplott">Lage residualplott</h3>
<p>Vi må kunne lage følgende residualplott i R, her demonstrert med regresjonsmodellen <code>reg1</code> som vi laget over:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Henter ut residualer og predikerte verdier fra modellen, og setter de inn som </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># kolonner i en dataframe:</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>residualer <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">residualer =</span> reg1<span class="sc">$</span>residuals,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">predikert =</span> reg1<span class="sc">$</span>fitted.values)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Spredningsplott, residualer mot predikerte verdier</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residualer, <span class="fu">aes</span>(<span class="at">x =</span> predikert, <span class="at">y =</span> residualer)) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Autokorrelasjonsplott</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(reg1<span class="sc">$</span>residuals)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram for å sjekke normalantakelsen</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residualer, <span class="fu">aes</span>(<span class="at">x =</span> residualer)) <span class="sc">+</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-plott, observasjonene ligger langs en rett linje hvis de er normalfordelte</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(residualer, <span class="fu">aes</span>(<span class="at">sample =</span> residualer)) <span class="sc">+</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Regner ut og plotter Cooks avstand:</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>infl <span class="ot">&lt;-</span> <span class="fu">influence.measures</span>(reg1)</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Lager enkelt plott av Cooks avstand</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>cooks_avstand <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">obs =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df),</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cook =</span> infl<span class="sc">$</span>infmat[, <span class="st">"cook.d"</span>],</span>
<span id="cb44-28"><a href="#cb44-28" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cook_infl =</span> infl<span class="sc">$</span>is.inf[, <span class="st">"cook.d"</span>])</span>
<span id="cb44-29"><a href="#cb44-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cooks_avstand, <span class="fu">aes</span>(<span class="at">x =</span> obs, <span class="at">y =</span> cook)) <span class="sc">+</span></span>
<span id="cb44-31"><a href="#cb44-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Alle plottene over kan justeres og pyntes, for eksempel ved å gjøre endringer som i <a href="#r-plotting">R-videoen om plotting</a>. Se også forelesningsscriptet for flere tips om presentasjon av residualplott.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-hypotesetesting.html" class="pagination-link" aria-label="Hypotesetesting">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hypotesetesting</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-tidsrekker.html" class="pagination-link" aria-label="Tidsrekker">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tidsrekker</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MET4 – Empiriske Metoder, NHH</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">
<p>Håkon Otneim</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">
<p>Geir Drage Berentsen</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>