<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nb" xml:lang="nb"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Hjemmesiden til kurset MET4 – Empiriske Metoder ved Norges Handelshøyskole.">

<title>7&nbsp; Dataøvinger – MET4 – Empiriske Metoder</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-seminaroppgaver.html" rel="next">
<link href="./06-avansert-regresjon-og-maskinlaering.html" rel="prev">
<link href="./icon/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ec8eff129d6f50c8392963982e963180.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Ingen resultater",
    "search-matching-documents-text": "Samsvarende dokumenter",
    "search-copy-link-title": "Kopier link for å søke",
    "search-hide-matches-text": "Skjul ytterlige resultater",
    "search-more-match-text": "annet resultat i dette dokumentet",
    "search-more-matches-text": "andre resultater i dette dokumentet",
    "search-clear-button-title": "Tøm",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Avbryt",
    "search-submit-button-title": "Send inn",
    "search-label": "Søk"
  }
}</script>
<script>
document.addEventListener("DOMContentLoaded", function () {
  var title = document.querySelector(".sidebar-title");
  if (title && !document.getElementById("nhh-sidebar-logo")) {
    var base = document.querySelector('meta[name="quarto:offset"]');
    var prefix = base ? base.getAttribute("content") : "";
    var link = document.createElement("a");
    link.href = "https://www.nhh.no/";
    link.id = "nhh-sidebar-logo";
    link.style.display = "block";
    link.style.margin = "0.6rem 0 0.2rem 0";
    var img = document.createElement("img");
    img.src = prefix + "bilder/nhh.png";
    img.alt = "Norges Handelshøyskole";
    img.style.maxWidth = "180px";
    img.style.width = "100%";
    link.appendChild(img);
    title.parentNode.insertBefore(link, title.nextSibling);
  }
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Slå av eller på sidebarnavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-dataøvinger.html">Oppgaver og eksamen</a></li><li class="breadcrumb-item"><a href="./07-dataøvinger.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dataøvinger</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Slå av eller på sidebarnavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Søk" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">MET4 – Empiriske Metoder</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Søk"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Innledning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Moduler</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Slå på delen">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro-til-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduksjon til R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-grunnleggende-statistikk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grunnleggende statistikk</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-hypotesetesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Hypotesetesting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regresjon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresjon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-tidsrekker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Tidsrekker</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-avansert-regresjon-og-maskinlaering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Avansert regresjon og maskinlæring</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Oppgaver og eksamen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Slå på delen">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-dataøvinger.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dataøvinger</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-seminaroppgaver.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Seminaroppgaver</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-Eksamensoppgaver.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Eksamensoppgaver</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innholdsfortegnelse</h2>
   
  <ul>
  <li><a href="#dataøving-1---grunnleggende-statistikk" id="toc-dataøving-1---grunnleggende-statistikk" class="nav-link active" data-scroll-target="#dataøving-1---grunnleggende-statistikk"><span class="header-section-number">7.1</span> Dataøving 1 - Grunnleggende statistikk</a></li>
  <li><a href="#dataøving-2" id="toc-dataøving-2" class="nav-link" data-scroll-target="#dataøving-2"><span class="header-section-number">7.2</span> Dataøving 2</a>
  <ul class="collapse">
  <li><a href="#interaktiv-øvelse" id="toc-interaktiv-øvelse" class="nav-link" data-scroll-target="#interaktiv-øvelse"><span class="header-section-number">7.2.1</span> Interaktiv øvelse</a></li>
  <li><a href="#data-til-dataøvelsen" id="toc-data-til-dataøvelsen" class="nav-link" data-scroll-target="#data-til-dataøvelsen"><span class="header-section-number">7.2.2</span> Data til dataøvelsen</a></li>
  <li><a href="#oppgaver-til-øvingen" id="toc-oppgaver-til-øvingen" class="nav-link" data-scroll-target="#oppgaver-til-øvingen"><span class="header-section-number">7.2.3</span> Oppgaver til øvingen:</a></li>
  </ul></li>
  <li><a href="#dataøving-3" id="toc-dataøving-3" class="nav-link" data-scroll-target="#dataøving-3"><span class="header-section-number">7.3</span> Dataøving 3</a>
  <ul class="collapse">
  <li><a href="#oppgave-1-interaktiv-øvelse" id="toc-oppgave-1-interaktiv-øvelse" class="nav-link" data-scroll-target="#oppgave-1-interaktiv-øvelse"><span class="header-section-number">7.3.1</span> Oppgave 1: Interaktiv øvelse</a></li>
  <li><a href="#oppgave-2-regresjonsanalyse" id="toc-oppgave-2-regresjonsanalyse" class="nav-link" data-scroll-target="#oppgave-2-regresjonsanalyse"><span class="header-section-number">7.3.2</span> Oppgave 2: Regresjonsanalyse</a></li>
  </ul></li>
  <li><a href="#dataøving-4" id="toc-dataøving-4" class="nav-link" data-scroll-target="#dataøving-4"><span class="header-section-number">7.4</span> Dataøving 4</a>
  <ul class="collapse">
  <li><a href="#oppgave-1-last-inn-og-se-på-datasettet" id="toc-oppgave-1-last-inn-og-se-på-datasettet" class="nav-link" data-scroll-target="#oppgave-1-last-inn-og-se-på-datasettet"><span class="header-section-number">7.4.1</span> Oppgave 1: Last inn og se på datasettet</a></li>
  <li><a href="#oppgave-2-gjem-bort-den-siste-dagen-slik-at-vi-kan-sjekke-prediksjonene-våre" id="toc-oppgave-2-gjem-bort-den-siste-dagen-slik-at-vi-kan-sjekke-prediksjonene-våre" class="nav-link" data-scroll-target="#oppgave-2-gjem-bort-den-siste-dagen-slik-at-vi-kan-sjekke-prediksjonene-våre"><span class="header-section-number">7.4.2</span> Oppgave 2: Gjem bort den siste dagen slik at vi kan sjekke prediksjonene våre</a></li>
  <li><a href="#oppgave-3-hent-ut-sesong-og-trend" id="toc-oppgave-3-hent-ut-sesong-og-trend" class="nav-link" data-scroll-target="#oppgave-3-hent-ut-sesong-og-trend"><span class="header-section-number">7.4.3</span> Oppgave 3: Hent ut sesong og trend</a></li>
  <li><a href="#oppgave-4-prediker-treningstidsrekken-24-steg-frem-og-visualiser-resultatene." id="toc-oppgave-4-prediker-treningstidsrekken-24-steg-frem-og-visualiser-resultatene." class="nav-link" data-scroll-target="#oppgave-4-prediker-treningstidsrekken-24-steg-frem-og-visualiser-resultatene."><span class="header-section-number">7.4.4</span> Oppgave 4: Prediker treningstidsrekken 24 steg frem og visualiser resultatene.</a></li>
  <li><a href="#oppgave-5-sammenlign-prediksjonene-med-de-faktiske-observasjonene" id="toc-oppgave-5-sammenlign-prediksjonene-med-de-faktiske-observasjonene" class="nav-link" data-scroll-target="#oppgave-5-sammenlign-prediksjonene-med-de-faktiske-observasjonene"><span class="header-section-number">7.4.5</span> Oppgave 5: Sammenlign prediksjonene med de faktiske observasjonene</a></li>
  <li><a href="#oppgave-6-lag-prediksjoner-for-neste-dag" id="toc-oppgave-6-lag-prediksjoner-for-neste-dag" class="nav-link" data-scroll-target="#oppgave-6-lag-prediksjoner-for-neste-dag"><span class="header-section-number">7.4.6</span> Oppgave 6: Lag prediksjoner for neste dag</a></li>
  <li><a href="#oppgave-7-lagre-prediksjonene-i-en-excel-fil." id="toc-oppgave-7-lagre-prediksjonene-i-en-excel-fil." class="nav-link" data-scroll-target="#oppgave-7-lagre-prediksjonene-i-en-excel-fil."><span class="header-section-number">7.4.7</span> Oppgave 7: Lagre prediksjonene i en excel-fil.</a></li>
  <li><a href="#oppgave-8-gjør-det-samme-for-no5" id="toc-oppgave-8-gjør-det-samme-for-no5" class="nav-link" data-scroll-target="#oppgave-8-gjør-det-samme-for-no5"><span class="header-section-number">7.4.8</span> Oppgave 8: Gjør det samme for <code>no5</code></a></li>
  </ul></li>
  <li><a href="#dataøving-5" id="toc-dataøving-5" class="nav-link" data-scroll-target="#dataøving-5"><span class="header-section-number">7.5</span> Dataøving 5</a>
  <ul class="collapse">
  <li><a href="#oppgave-1-interaktiv-øvelse-1" id="toc-oppgave-1-interaktiv-øvelse-1" class="nav-link" data-scroll-target="#oppgave-1-interaktiv-øvelse-1"><span class="header-section-number">7.5.1</span> Oppgave 1: Interaktiv øvelse</a></li>
  <li><a href="#oppgave-2---maskinlæring-logistisk-regresjon-og-k-nærmeste-naboer" id="toc-oppgave-2---maskinlæring-logistisk-regresjon-og-k-nærmeste-naboer" class="nav-link" data-scroll-target="#oppgave-2---maskinlæring-logistisk-regresjon-og-k-nærmeste-naboer"><span class="header-section-number">7.5.2</span> Oppgave 2 - Maskinlæring: Logistisk regresjon og k nærmeste naboer</a></li>
  <li><a href="#oppgave-3-paneldata-iskaffe-og-varme-dager" id="toc-oppgave-3-paneldata-iskaffe-og-varme-dager" class="nav-link" data-scroll-target="#oppgave-3-paneldata-iskaffe-og-varme-dager"><span class="header-section-number">7.5.3</span> Oppgave 3 – Paneldata: Iskaffe og varme dager</a></li>
  <li><a href="#oppgave-4-kausal-identifikasjon-ølskatt-og-trafikkdødsfall" id="toc-oppgave-4-kausal-identifikasjon-ølskatt-og-trafikkdødsfall" class="nav-link" data-scroll-target="#oppgave-4-kausal-identifikasjon-ølskatt-og-trafikkdødsfall"><span class="header-section-number">7.5.4</span> Oppgave 4 – Kausal identifikasjon: Ølskatt og trafikkdødsfall</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-dataøvinger.html">Oppgaver og eksamen</a></li><li class="breadcrumb-item"><a href="./07-dataøvinger.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dataøvinger</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Dataøvinger</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Her finner du dataøvingene som skal gjennomføres i MET4. Se tidsplanen til kurset for en oversikt over når de ulike øvingene skal gjøres og hvilke uker studentassistentene gjennomfører øvingene på datasal.</p>
<section id="dataøving-1---grunnleggende-statistikk" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="dataøving-1---grunnleggende-statistikk"><span class="header-section-number">7.1</span> Dataøving 1 - Grunnleggende statistikk</h2>
<p>I denne dataøvingen skal du lese inn et datasett i R og lage enkel deskriptiv statistikk. Vi forutsetter at du har vært gjennom [Introduksjon til R], som dekker installasjon av R og RStudio og det grunnleggende om å jobbe i R.</p>
<p>Dataene kommer fra <a href="https://journals.sagepub.com/doi/10.1177/0956797619829688">et amerikansk forsøk</a> hvor man ville undersøke påstanden om at voldelige dataspill fører til voldelig adferd ved la to grupper spille hvert sitt dataspill. I det “voldelige” dataspillet var oppdraget å <em>skyte</em> og <em>drepe</em> et romvesen, mens i den ikke-voldelige varianten skulle man <em>finne</em> og <em>redde</em> romvesenet fra fare. Utover det var spillene helt likt utformet, og i etterkant av en spilleøkt ble deltakernes aggresjonsnivå målt på en skala fra 1 til 9 ved hjelp av en standard psykologisk test. Dette datasettet ble brukt i eksamensoppgaven vårsemesteret 2019.</p>
<p><strong>Oppgave 1.</strong> <a href="datasett/violence.xlsx">Last ned filen violence.xlsx</a>. Denne filen lagrer du fortrinnsvis i en egen mappe der du ønsker at filer fra denne øvingen skal ligge. Åpne så <strong>RStudio</strong>, velg <code>File -&gt; New File -&gt; R Script</code> for å åpne et nytt Rscript. Lagre så scriptet ditt i samme mappen som du har lagt datasettet, slik at du nå har en mappe som ser ut som figuren under:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/mappe.JPG" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Når vi skal lese inn data, lagre figurer og andre ting har R en standard ‘mappesti’ (working directory) den leter/lagrer i. Du kan se hva denne stien peker på ved å skrive <code>getwd()</code> i konsollen. Du skal nå spesifisere denne mappestien til mappen du har opprettet. Dette gjør du raskest ved å velge <code>Session -&gt; Set Working Directory -&gt; To Source File Location</code>. Neste gang du skal jobbe med dette prosjektet kan du åpne <strong>RStudio</strong> ved å dobbeltklikke på <code>dataøving1.R</code>, og mappestien skal da settes automatisk til riktig mappe.</p>
<p>Lag gjerne en liten overskrift ved hjelp av kommentartegnet <code>#</code> slik at .R filen din ser omtrent slik ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/rstudio3.JPG" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Oppgave 2.</strong> Du skal nå lese inn excel filen du lagret i over i R. Selv om det finnes mange funksjoner som allerede er innebygget i R, må man noen ganger installere ekstra ‘pakker’ for å få tilgang til spesielle funksjoner. For å lese inn en excel fil trenger du nettopp en slik ikke standard funksjon. Denne finnes i pakken <code>readxl</code>. Selve installeringen kan du gjøre direkte i konsollen med å skrive (hvis du ikke har gjort det allerede, for eksempel da du gikk gjennom <a href="#pakker">forelesningsvideoen om R-pakker</a>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"readxl"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Pakken legger seg da i en bibliotekmappe der R er installert. For å gi R beskjed om å laste inn funksjonene til pakken du nettopp installerte bruker du funksjonen <code>library()</code>. Du har nå tilgang til en funksjon kalt <code>read_excel()</code> som du kan bruke til å lese inn excel filen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># MET4 - Dataøving 1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># les inn data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>violence <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"violence.xlsx"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.3.3</code></pre>
</div>
</div>
<p>Marker linjene du nettopp skrev i R-skriptet ditt og trykk <strong>Ctrl + Enter</strong> (<strong>Cmd + Enter</strong>), for å opprette objektet <code>violence</code> som inneholder datasettet. Funksjonen <code>ls()</code> lister opp alle objekter som har blitt definert. Du kan prøve selv å skrive følgende i konsollen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "pandoc_dir"      "quarto_bin_path" "violence"       </code></pre>
</div>
</div>
<p>Du ser at det har kommet et nytt objekt som heter <code>violence</code>. En tilsvarende oversikt finner du i vinduet øverst til høyre i RStudio (se <a href="01-intro-til-r.html#fig-rstudio1" class="quarto-xref">Figur&nbsp;<span>1.1</span></a>) hvor du også kan klikke på objektet for å se nærmere på det.</p>
<p><strong>Oppgave 3.</strong> Ta en titt på strukturen til datasettet du nettopp leste inn. Når du gjør slike små utforskninger kan du gjerne jobbe direkte i konsollen, og det du gjør i dette punktet trenger nødvendigvis ikke være med i .R-filen din. Gå til konsollen og bruk funksjoner som <code>class</code>, <code>dim</code>, <code>names</code>, <code>head</code> og <code>str</code> for å utforske strukturen på dataene. Vi ser at det er 5 variabler:</p>
<ul>
<li><code>id</code> er bare et tall som identifiserer forsøkspersonen.</li>
<li><code>aggression_level</code> er aggresjonsnivået som ble målt rett etter at forsøkspersonen hadde spilt en viss tid.</li>
<li><code>violent_treatment</code> er varianten av dataspillet som forsøkspersonen ble utsatt for; enten <code>Violent</code> eller <code>Less Violent</code>.</li>
<li><code>difficulty_treatment</code> er vanskelighetsgraden av spillet, som enten var <code>Easy</code> eller <code>Hard</code>. En mulig forklaring på aggressiv adferd er at vanskelige spill fører til høyere stressnivå, som igjen kan føre til aggressivitet.</li>
<li><code>experienced_violence</code> er svaret til forsøkspersonen på spørsmålet om vedkommende <em>oppfattet</em> spillet som <code>Violent</code> eller <code>Less Violent</code>. Forsøkspersonene visste ikke selv hva forsøket gikk ut på, eller at det var flere varianter av det samme spillet.</li>
</ul>
<p><strong>Oppgave 4.</strong></p>
<p>Vi skal se nærmere på om aggresjonsnivået er forskjellig i de to gruppene. Da må vi trekke ut de aktuelle tallene fra datasettet. Vi ønsker å velge ut <em>to vektorer</em> for å gjøre denne sammenligningen: en vektor som inneholder aggresjonsnivået til gruppen som har spilt det voldelige dataspillet, og en vektor som inneholder aggresjonsnivået til gruppen som har spilt det ikke-voldelige dataspillet.</p>
<p>La disse to vektorene få navn <code>voldelig</code> og <code>ikke_voldelig</code>, og lag dem ved å skrive følgende kodelinjer (se <a href="#pipe">video om pipe-operatoren og enkel datavask</a> for en forklaring av disse funksjonene. Den siste linjen, <code>pull</code>, gjør en dataframe med én kolonne om til en vektor) :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Laster inn dplyr-pakken</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vektorer med aggresjonsnivå til gruppen som har spilt voldelig/ikke-voldelig spill </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>voldelig <span class="ot">&lt;-</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  violence <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(violent_treatment <span class="sc">==</span> <span class="st">"Violent"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aggression_level) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  pull</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>ikke_voldelig <span class="ot">&lt;-</span> </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  violence <span class="sc">%&gt;%</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(violent_treatment <span class="sc">==</span> <span class="st">"Less Violent"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aggression_level) <span class="sc">%&gt;%</span> </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  pull</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sjekk nå at dette har fungert ved å skrive <code>voldelig</code> og <code>ikke_voldelig</code> inn i konsollen for å se at det faktisk er vektorer som inneholder tallene 1 til 9. Bruk også noen minutter til å prøve å forstå hva kodelinjene over faktisk gjør.</p>
<p>(<strong>NB!</strong> Pass på at du skriver <code>Violent</code> og <code>Less Violent</code> helt riktig med store og små bokstaver, ellers vil det ikke fungere!)</p>
<p><strong>Oppgave 5.</strong> I eksamensoppgaven fra 2019 får vi oppgitt deskriptiv statistikk over aggresjonsnivået for de to gruppene i følgende tabell:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/descriptive.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
<p>Bruk funksjoner som <code>min()</code>, <code>max()</code>, <code>median()</code>, <code>mean()</code>, <code>length()</code> og <code>summary()</code> til å finne ut om tallene stemmer (Du vil se at datasettet ditt inneholder noen færre observasjoner enn det som er oppgitt i tabellen, som gjør at tallene er litt forskjellige).</p>
<p><strong>Oppgave 6.</strong> Vi skal nå lage et histogram av aggresjonsnivået, med ett histogram for hver av de to gruppene. Et svært viktig punkt er følgende:</p>
<p><strong><code>ggplot</code>-funksjonen skal alltid ha hele datasettet (en data frame) som argument!!</strong></p>
<p>Det betyr at vi <em>ikke</em> skal bruke de to vektorene <code>voldelig</code> og <code>ikke_voldelig</code> som vi lagde over, men hele datasettet <code>violence</code>. Variabelen som inneholder aggresjonsnivået er <code>aggression_level</code>, så det er den vi bruker som <span class="math inline">\(x\)</span>-argument. Vi husker å laste inn <code>ggplot2</code>-pakken først, og gjør et første forsøk:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(violence, <span class="fu">aes</span>(<span class="at">x =</span> aggression_level)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">9</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nesten! Det eneste problemet er at vi har ett histogram for alle observasjonene, mens det vi egentlig ønsket var å lage et histogram for hver av gruppene. Dette er såre enkelt i <code>ggplot2</code>. Det eneste vi trenger å gjøre er å identifisere den variabelen i datasettet som angir gruppetilhørighet (sjekk variabeloversikten over, svaret er <code>violent_treatment</code>), og så plusse på en funksjon som heter <code>facet_wrap()</code> som vist under.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(violence, <span class="fu">aes</span>(<span class="at">x =</span> aggression_level)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> violent_treatment)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dersom vi i stedet ønsker et skalert histogram kan vi spesifisere <code>y</code>-argumentet på følgende vis:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(violence, <span class="fu">aes</span>(<span class="at">x =</span> aggression_level, <span class="at">y =</span> <span class="fu">after_stat</span>(density))) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> violent_treatment)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Oppgave 7.</strong> Når man skal sammenligne sentrum og spredning i to grupper er et boxplott et ypperlig alternativ og vi kan da bruke funksjonen <code>boxplot()</code> i “base R”, eller funksjonen <code>geom_boxplot()</code> hvis vi heller ønsker å benytte <code>ggplot2</code>. Vi holder oss til det siste alternativet her, og ser at kodelinjene ligner på det vi laget over.</p>
<p>Dersom vi ønsker å lage et enkelt boxplot av en variabel for å sammenligne spredingen i to eller flere grupper kan vi skrive</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(a, <span class="fu">aes</span>(<span class="at">x =</span> b, <span class="at">y =</span> c)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Her må du selv erstatte bokstavene a, b og c i henhold til følgende regel:</p>
<ul>
<li><code>a</code> er navnet på datasettet.</li>
<li><code>b</code> er variabelen som inneholder gruppeinndelingen.</li>
<li><code>c</code> er variabelen som inneholder målingene.</li>
</ul>
<p>De ferdige kodelinjene skal være med i .R-skriptet ditt. For å se boxplottet kan du som vanlig kjøre kommandoene med å trykke <strong>Ctrl + Enter</strong>. Ser det ut til å være noe forskjell på sentrum og spredning i de to gruppene?</p>
<p><strong>Bonusoppgave.</strong> Bytt ut <code>geom_boxplot()</code> over med <code>geom_jitter()</code> og <code>geom_violin()</code>. Hva viser disse plottene?</p>
</section>
<section id="dataøving-2" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="dataøving-2"><span class="header-section-number">7.2</span> Dataøving 2</h2>
<section id="interaktiv-øvelse" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="interaktiv-øvelse"><span class="header-section-number">7.2.1</span> Interaktiv øvelse</h3>
<p>Før vi tar fatt på dataanalysen begynner vi med litt R-trening i swirl. Har du allerede installert pakken <code>swirl</code> (skriv <code>install.packages("swirl")</code> i konsoll hvis ikke) starter du opp swirl med å skrive følgende i konsollen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(swirl)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">swirl</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du vil i starten bli bedt om å skrive inn ditt navn. Hvis du bruker samme navn som tidligere får du kanskje tilbud om å starte opp igjen der du slapp, men da kan du bare velge det nederste valget ‘No.&nbsp;Let me start something new’. Du velger så alternativet ‘R Programming’ hvor du får se alle modulene dette kurset inneholder. I denne øvingen skal du prøve deg på modul 6 <strong>‘Subsetting Vectors’</strong> og modul 8 <strong>‘Logic’</strong>.</p>
<p>Husk at det helt til høyre vil står hvor langt du har kommet i prosent. Står du helt fast med et punkt kan du skrive <code>skip()</code> for å hoppe over dette punktet. Når du har fullført en modul blir du spurt om du vil motta ‘credit’ for å ha fullført modulen. Her kan du svare nei. Ønsker du å avbryte underveis skriver du <code>bye()</code>. Skriver du inn det samme navnet når du eventuelt starter swirl igjen kan du fortsette der du slapp. Husk å avslutt swirl () før du begynner på neste del av datalabben. Lykke til!</p>
</section>
<section id="data-til-dataøvelsen" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="data-til-dataøvelsen"><span class="header-section-number">7.2.2</span> Data til dataøvelsen</h3>
<p>I denne dataøvelsen skal vi ved hjelp av R gjennomføre en del av testene som vi har lært i praksis. Vi skal gjøre både ett- og to-utvalgs tester, og vi skal bruke <span class="math inline">\(\chi^2\)</span>-testen</p>
<p>Vi skal jobbe med tre ulike datasett i denne øvingen, og alle sammen kan lastes ned ved å klikke på lenkene under:</p>
<ul>
<li><a href="datasett/testdata.xls"><code>testdata.xls</code></a></li>
<li><a href="datasett/violence.xlsx"><code>violence.xlsx</code></a></li>
<li><a href="datasett/roubik_2002_coffe_yield.xlsx"><code>roubik_2002_coffee_yield.xlsx</code></a></li>
</ul>
<p>Last ned disse filene og legg dem i en mappe på datamaskinen din. Åpne så <strong>RStudio</strong>, velg <code>File -&gt; New File -&gt; R Script</code> for å åpne et nytt Rscript, og lag gjerne en liten overskrift ved hjelp av kommentartegnet <code>#</code>. Lagre så scriptet ditt i samme mappen som du har lagt datasettene, slik at du nå har en mappe som ser ut som figuren under:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/mappe2.png" class="img-fluid figure-img" width="381"></p>
</figure>
</div>
</div>
</div>
<p>Det neste du må gjøre er å sørge for at du har satt opp riktig mappesti (working directory) i <strong>RStudio</strong>, og det gjør du raskest ved å velge <code>Session -&gt; Set Working Directory -&gt; To Source File Location</code>. Neste gang du skal jobbe med dette prosjektet kan du åpne <strong>RStudio</strong> ved å dobbeltklikke på <code>dataøving2.R</code>, og mappestien skal da settes automatisk til riktig mappe. I alle tilfeller skal vinduet ditt se omtrent slik ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/rstudio2.png" class="img-fluid figure-img" width="210"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="oppgaver-til-øvingen" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="oppgaver-til-øvingen"><span class="header-section-number">7.2.3</span> Oppgaver til øvingen:</h3>
<section id="oppgave-1" class="level4" data-number="7.2.3.1">
<h4 data-number="7.2.3.1" class="anchored" data-anchor-id="oppgave-1"><span class="header-section-number">7.2.3.1</span> Oppgave 1</h4>
<p>Costa Rica er en stor kaffeprodusent med moderne produksjon. Kaffeprodusentene har over lengre tid benyttet en standardisert miks av sprøytemidler som skal ta knekken på ugress og skadelige insekter, men uten å skade avlingen eller miljøet ellers.</p>
<p>En liten kaffeplantasje i Costa Rica har begynt å eksperimentere med en ny kombinasjon av sprøytemidler som skal være like effektiv mot ugress, men samtidig enda mer skånsom mot kaffeplantene, slik at avlingen blir større. Innehaveren av plantasjen ønsker å sette opp et eksperiment for å undersøke denne påstanden. Han velger ut 25 tilfeldige jordlapper fordelt på hele eiendommen der han bruker de nye sprøytemidlene gjennom en hel sesong.</p>
<p>Lang erfaring har vist at avlingen ved bruk av gammel metode er normalfordelt med forventning <span class="math inline">\(\mu = 100\)</span> og standardavvik <span class="math inline">\(\sigma = 10\)</span>, der vi har brukt en standardisert enhet for mengde avling per arealenhet. Hjelp bonden, ved å løse følgende oppgaver:</p>
<p><strong>Oppgave 1.1:</strong> Les inn datasettet <code>testdatasdata.xsl</code> i <strong>RStudio</strong> og se på de første par radene. Det kan du gjøre ved å kjøre følgende kodelinjer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)                                 <span class="co"># Pakke for å lese excel-filer</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"testdata.xls"</span>)              <span class="co"># Leser inn datasettet</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>data                                            <span class="co"># Ser på datasettet</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 × 4
      X1    X2    A1    A2
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 122.  121.      1     1
 2 101.  105       1     1
 3 114.  108       1     1
 4 103    99.1     1     0
 5  97.6  96.2     0     0
 6  85.9  95.4     0     0
 7  93.5 101.      0     1
 8  92    97       0     0
 9  98.8 106.      0     1
10  99.9 100.      0     1
# ℹ 15 more rows</code></pre>
</div>
</div>
<p>Det er kolonnen <code>X2</code> som inneholder de observerte avlingene på de 25 forsøksseksjonene.</p>
<p><strong>Oppgave 1.2:</strong> Er forventet avling ved bruk av den nye metoden <em>større</em> enn forventet avling ved bruk av den gamle metoden? <em>Hint: Forelesningsnotatene/scriptet inneholder koden du trenger for å løse denne og neste oppgave. Du kan også se på <a href="#relevante-r-testing">oversikten over relevante R-kommandoer</a> for det du trenger.</em></p>
<p><strong>Oppgave 1.3:</strong> Det er viktig for kaffebonden at avlingen ikke varierer for mye mellom de ulike delene av farmen. En viktig måleparameter for denne type produksjon er derfor variansen. Kan vi slå fast at variansen til avlingen har forandret seg etter omlegging til ny metode?</p>
<p><strong>Oppgave 1.4:</strong> Kaffebonden er skeptisk til påstanden om at forventet avling med den gamle metoden er <span class="math inline">\(\mu = 100\)</span>, og mener at det vil variere med for eksempel jordsmonn. For å ta høyde for dette gjennomførte han året i forveien tilsvarende målinger på de samme jordlappene, med med gammel sprøytemetode. Disse målingene finner du i kolonne <code>X1</code> i datasettet. Test om avlingene er forskjellige, både med og uten paring av observasjonene. Kommenter resultatet.</p>
</section>
<section id="oppgave-2" class="level4" data-number="7.2.3.2">
<h4 data-number="7.2.3.2" class="anchored" data-anchor-id="oppgave-2"><span class="header-section-number">7.2.3.2</span> Oppgave 2</h4>
<p>Vi skal i denne oppgaven se på oppgave <strong>1a</strong> og <strong>1b</strong> som ble gitt på skoleeksamen i MET4 vårsemesteret 2019. Dette er det samme datasettet som vi så på i forrige dataøving. I <a href="https://journals.sagepub.com/doi/10.1177/0956797619829688">et amerikansk forsøk</a> ville man undersøke påstanden om at voldelige dataspill fører til voldelig adferd ved la to grupper spille hvert sitt dataspill. I det “voldelige” dataspillet var oppdraget å <em>skyte</em> og <em>drepe</em> et romvesen, mens i den ikke-voldelige varianten skulle man <em>finne</em> og <em>redde</em> romvesenet fra fare. Utover det var spillene helt likt utformet, og i etterkant av en spilleøkt ble deltakernes aggresjonsnivå målt på en skala fra 1 til 9 ved hjelp av en standard psykologisk test.</p>
<p>I denne oppgaven skal vi i hovedsak finne ut om gruppen som spilte de voldelige dataspillet hadde signifikant høyere aggresjonsnivå enn kontrollgruppen.</p>
<p><strong>Oppgave 2.1:</strong> Les inn datasettet <code>violence.xslx</code> på samme måte som i forrige dataøving. Hvis du allerede har kjørt <code>library(readxl)</code> trenger du ikke gjøre det igjen med mindre du har startet <strong>RStudio</strong> på nytt. Gi datasettet et passende navn, f.eks</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>violence <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"violence.xlsx"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vi skal altså teste om aggresjonsnivået er forskjellig i de to gruppene. Da må vi trekke ut de aktuelle tallene fra datasettet. Som vi husker fra forelesningsnotatene trenger vi <em>to vektorer</em> for å gjøre en to-utvags <span class="math inline">\(t\)</span>-test: en vektor som inneholder aggresjonsnivået til gruppen som har spilt det voldelige dataspillet, og en vektor som inneholder aggresjonsnivået til gruppen som har spilt det ikke-voldelige dataspillet.</p>
<p>La disse to vektorene få navn <code>voldelig</code> og <code>ikke_voldelig</code>, og lag dem ved å skrive følgende kodelinjer (samme som forrige dataøving):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>voldelig <span class="ot">&lt;-</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  violence <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(violent_treatment <span class="sc">==</span> <span class="st">"Violent"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aggression_level) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  pull</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>ikke_voldelig <span class="ot">&lt;-</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  violence <span class="sc">%&gt;%</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(violent_treatment <span class="sc">==</span> <span class="st">"Less Violent"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(aggression_level) <span class="sc">%&gt;%</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  pull</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Oppgave 2.2:</strong> Vi er nå klare til å gjøre en to-utvalgs <span class="math inline">\(t\)</span>-test for om aggresjonsnivået er det samme i de to gruppene. Prøv å gjøre det nå, men vær bevisst på hvilke valg du gjør underveis, og som du mater inn i <code>t.test()</code>-funksjonen, f.eks:</p>
<ul>
<li>Antar du lik varians i de to gruppene? Hvorfor/Hvorfor ikke?</li>
<li>Bruker du ensidig eller tosidig test? Hvorfor?</li>
</ul>
<p><strong>Oppgave 2.3:</strong> En avgjørende detalj i studien som vi ser på i denne oppgaven er at forskerne også spurte forsøkspersonene hvorvidt de selv syntes spillet de spilte var voldelig. For å kunne trekke noen som helst lærdom fra et slikt forsøk er det viktig at den voldelige spillvarianten faktisk blir oppfattet som voldelig og vice versa. Vi ønsker dermed å undersøke nullhypotesen om at variablene <code>violence_tratment</code> og <code>experienced_violence</code> er uavhengige av hverandre. Den hypotesen er vi nødt til å forkaste for at forsøket skal være gyldig: hvis det ikke er noen sammenheng mellom opplevd og faktisk voldelighet er forsøket helt klart ugyldig.</p>
<p>Første steg er å lage et nytt datasett der vi bare ta med oss de to kolonnene vi er interessert i. Kall det hva du vil, f.eks. <code>violence_redusert</code>. Vi bruker <code>select()</code>-funksjonen til å velge ut variablene vi trenger, se <a href="#pipe">video om datavask</a> dersom du trenger å repetere denne funksjonen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>violence_redusert <span class="ot">&lt;-</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  violence <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(violent_treatment, experienced_violence)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Skriv <code>violence_redusert</code> i konsollen for å bekrefte at du har valgt ut de korrekte kolonnene.</p>
<p>Vi fortsetter som i videoforelesningen og lager en krysstabell for disse variablene</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>krysstabell <span class="ot">&lt;-</span> <span class="fu">table</span>(violence_redusert) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>krysstabell</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 experienced_violence
violent_treatment Less Violent Violent
     Less Violent          114       9
     Violent                33      93</code></pre>
</div>
</div>
<p><strong>Oppgave 2.4:</strong> Heldigvis ser det ut til at det er en klar sammenheng mellom faktisk og opplevd voldelighet ved at de fleste forsøkspersonene havner på diagonalen i krysstabellen. Bruk funksjonen <code>chisq.test()</code> på samme måte som i forelesningen til å formelt teste nullhypotesen om uavhengighet.</p>
</section>
<section id="oppgave-3" class="level4" data-number="7.2.3.3">
<h4 data-number="7.2.3.3" class="anchored" data-anchor-id="oppgave-3"><span class="header-section-number">7.2.3.3</span> Oppgave 3</h4>
<p>Vi skal i denne oppgaven returnere til kaffeproduksjon. Vi skal gjøre statistiske tester i R som i de tidligere oppgavene i denne øvingen, men vanskelighetsgraden går opp fordi vi også må tenke nøye over hvordan vi anvender metodene korrekt i en gitt kontekst.</p>
<p>I 2002 publiserte det prestisjetunge tidsskriftet <em>Nature</em> en kort artikkel skrevet av David W. Roubik<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, som handler om den kjente kaffebønnen <em>Arabica</em>. Arabicabønnen kommer opprinnelig fra Afrika, og er en selvpollinerende plante. Det vil si at den ikke er avhengig av insekter for å formere seg, og man trodde lenge at den heller ikke hadde noen fordeler av insektspollinering.</p>
<p>For å undersøke denne påstanden samlet Roubik inn historiske data over arabicaavlinger fra hele verden. Han delte verdens kaffeproduserende land inn i to kategorier: <em>Old world</em> som omfatter afrikanske og asiatiske land, og <em>New world</em> som omfatter land i Latin-Amerika. Han registrerte videre <em>gjennomsnittlig årlig avling</em> (målt i kg/hektar) i to perioder: 1961–80 og 1981–2001.</p>
<p>Nøkkelen til analysen er at den afrikanske honningbien var en viktig pollinator i Afrika og Asia både i den første og andre perioden, men knapt eksisterte i Amerika før 1980. Etter 1980, derimot, økte utbredelsen av denne bien i Amerika, og ble fort naturalisert. Kan vi sette denne utviklingen i sammenheng med økt kaffeavling i Latin-Amerika etter 1980, og dermed skrote teorien om at kaffeplanter ikke drar nytte av insektspollinering?</p>
<p><strong>Oppgave 3.1:</strong> For å undersøke dette kan vi bruke datasettet som Roubik brukte, som finnes i filen <code>roubik_2002_coffe_yield.xlsx</code>. Last datasettet inn i R på vanlig måte, og se på det:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>yield <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"roubik_2002_coffe_yield.xlsx"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>yield</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28 × 4
   world country     yield_61_to_80 yield_81_to_01
   &lt;chr&gt; &lt;chr&gt;                &lt;dbl&gt;          &lt;dbl&gt;
 1 new   Costa_Rica            9139          14620
 2 new   Bolivia               7686           8767
 3 new   El_Salvador           9996           8729
 4 new   Guatemala             5488           8231
 5 new   Colombia              5920           7740
 6 new   Honduras              4096           7264
 7 new   Nicaragua             4566           6408
 8 new   Brazil                4965           6283
 9 new   Peru                  5487           5740
10 new   Mexico                5227           5116
# ℹ 18 more rows</code></pre>
</div>
</div>
<p>Vi ser at det er fire kolonner i datasettet:</p>
<ul>
<li><code>world</code> angir om det er snakk om <em>New world</em> (<code>new</code>) eller <em>Old world</em> (<code>old</code>).</li>
<li><code>country</code> angir navnet på landet.</li>
<li><code>yield_61_to_80</code> angir avlingen i perioden 1961–80.</li>
<li><code>yield_81_to_01</code> angir avlingen i perioden 1981–2001.</li>
</ul>
<p><strong>Oppgave 3.2:</strong> Kall den første tidsperioden <code>p1</code> og den andre tidsperioden <code>p2</code>. Lag så <em>fire</em> vektorer, en for hver kombinasjon av <code>world</code> og tidsperiode ved å bruke samme teknikk som i oppgave <strong>2.2</strong> over. Når du er ferdig, skal du ha laget følgende vektorer:</p>
<ul>
<li><code>new_p1</code>: inneholder avling for alle land med <code>world == new</code> i første periode.</li>
<li><code>new_p2</code>: inneholder avling for alle land med <code>world == new</code> i andre periode.</li>
<li><code>old_p1</code>: inneholder avling for alle land med <code>world == old</code> i første periode.</li>
<li><code>old_p2</code>: inneholder avling for alle land med <code>world == old</code> i andre periode.</li>
</ul>
<p>Her må du bruke både <code>filter()</code> og <code>select()</code>, og du må avslutte med en <code>pull</code> for å oversette en en-kolonnes dataframe til en vektor.</p>
<p>Dersom du har gjort det riktig, ser vektorene slik ut når du er ferdig:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>new_p1</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 9139 7686 9996 5488 5920 4096 4566 4965 5487 5227 2347 3089 1938</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>new_p2</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 14620  8767  8729  8231  7740  7264  6408  6283  5740  5116  4124  3240
[13]  2789</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>old_p1</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  4251 10522  3509 10028  5667 17064  5904  4001  6604  4738  5716  3824
[13]  3525  3393  3213</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>old_p2</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 13380 11561  9652  9593  8797  7869  7354  7288  6055  5432  5394  3576
[13]  3141  2391  2136</code></pre>
</div>
</div>
<p><strong>Oppgave 3.3:</strong> Bruk en paret <span class="math inline">\(t\)</span>-test til å finne ut om kaffeavlingen i den gamle verden er signifikant forskjellig i de to tidsperiodene.</p>
<p><strong>Oppgave 3.4:</strong> Bruk en paret <span class="math inline">\(t\)</span>-test til å finne ut om kaffeavlingen i den nye verden er signifikant forskjellig i de to tidsperiodene.</p>
<p><strong>Oppgave 3.5 (Diskusjonsopgave):</strong> Dersom du har gjort de to foregående oppgavene riktig vil du se at den gjennomsnittlige kaffeavlingen ikke har endret seg signifikant i den gamle verden, mens økningen i den nye verden er klart statistisk signifikant. Vi har brukt parrede <span class="math inline">\(t\)</span>-tester, slik at vi “kontrollerer for” eventuelle landeffekter (denne terminologien blir skal vi bruke mer når vi skal jobbe med regresjon).</p>
<p>Roubik omtaler funnet som følger:</p>
<blockquote class="blockquote">
<p><em>A substantial increase in Latin American coffee yield partly coincided with the establishment of African honeybees in those countries, although there was no such change in the Old World, where honeybees originated […]. This comparison underlines a possible cause-and-effect relationship between the presence of social bees and cofee yield.</em></p>
</blockquote>
<p>Dette er intet mindre enn en <strong>kortslutning</strong>, på minst to forskjellige måter. Hvorfor? Diskuter med dine medstudenter. Kan det gjennomføres en enkel test som gir et bedre bilde av situasjonen?</p>
<!-- ### BONUS: En alternativ teknikk for datamanipulering (Gjør bare om du har overskudd til det!) -->
<!-- Se på denne kodelinjen: -->
<!-- ```{r, eval = FALSE} -->
<!-- voldelig <- violence$aggression_level[violence$violent_treatment == "Violent"] -->
<!-- ``` -->
<!-- Vi skrev denne linjen for å hente ut noen bestemte verdier fra et bestemt datasett. Det er kanskje ikke så lett å se hva kodelinjen gjør ved å bare kaste et raskt blikk på den, og det er spesielt to grunner til det: -->
<!-- - den er lang, og -->
<!-- - du må lese den delvis "innenfra og ut" (alstå, begynne innerst i parantesene) og delvis fra høyre mot venstre. -->
<!-- Spesielt det siste punktet er kontraintuitivt, siden det er motsatt av slik vi vanligvis leser. Mye arbeid i R går ut på å manipulere datasett på ulike vis (hente ut kolonner og rader, lage nye kolonner), og derfor er det utviklet noen alternative verktøy for å gjøre slike jobber mye mer effektivt. Vi vil i dette avsnittet gi en kort og meget grunleggende innføring i slike teknikker. Merk at dette ikke er *pensum* i klassisk forstand. Det viktigste er at jobben blir gjort korrekt. Hvordan du gjør det er i så måte underordnet. -->
<!-- For å gjennomføre øvelsen under må du installere og laste inn en ny pakke: `dplyr`: -->
<!-- ```{r, eval = FALSE} -->
<!-- install.packages("dplyr") -->
<!-- library(dplyr) -->
<!-- ``` -->
<!-- ```{r, message = FALSE, echo = FALSE, warning = FALSE} -->
<!-- library(dplyr) -->
<!-- ``` -->
<!-- #### KONSEPT 1: Pipe-operatoren `%>%` {-} -->
<!-- Tenk deg at vi skal regne ut logaritmen til kvadratroten av 2. Vi må da anvende to funksjoner i riktig rekkefølge. Vi kan alltids bruke en mellomregning: -->
<!-- ```{r} -->
<!-- kvadratroten_til_2 <- sqrt(2) -->
<!-- log(kvadratroten_til_2) -->
<!-- ``` -->
<!-- Eventuelt kjører vi alt sammen i en linje: -->
<!-- ```{r} -->
<!-- log(sqrt(2)) -->
<!-- ``` -->
<!-- Nå er ikke den siste linjen spesielt lang, men den er som sagt ikke helt intuitiv. Grunnen er at hvis vi skal lese høyt hva den gjør, så må vi begynne innerst i parantesene: "Vi starter med tallet 2, så tar vi kvadratroten, så tar vi logaritmen..." -->
<!-- I `dplyr`-pakken finnes en såkalt pipe-operator som gjør at vi kan skrive dette som kode i den rekkefølgen ting skal skje. Eksempelet over skrives slik: -->
<!-- ```{r} -->
<!-- 2 %>% sqrt %>% log -->
<!-- ``` -->
<!-- Det som skjer er at R leser linjen fra venstre, og ved hver "pipe/`%>%`" sendes det som står på venstre side inn som argument i funksjonen på høyre side. Når du leser kode, kan denne operatoren uttales som **så** (**then** på engelsk): **Først** har vi tallet 2, **så** tar vi kvadratroten, **så** tar vi logaritmen. -->
<!-- Tenk når vi har en sekvens av 10 eller 20 eller 50 steg (ikke uvanlig i den virkelige verden), hvor mye enklere det blir å kode på denne måten fremfor å ha 10, 20 eller 50 nivå med paranteser! -->
<!-- **Tips:** Hurtigtasten for `%>%` i RStudio er `Ctrl - Shift - M` (Bytt ut **Ctrl** med **Cmd** på Mac). -->
<!-- #### KONSEPT 2: Datamanipuleringsfunksjoner i `dplyr` {-} -->
<!-- I `dplyr` finnes det noen meget praktiske funksjoner som vi kan bruke til å manipulere datasatt i R. La oss ta utgangspunkt i datasettet `violence` og prøve å skrive om den aktuell kodelinjen over ved hjelp av pipe-operatoren. I klartekst skal vi gjøre følgende operasjoner: -->
<!-- 1. Starte med datasettet `violence` -->
<!-- 2. Plukke ut alle radene som har verdi `"Violent"` i kolonnen `violent_treatment`. -->
<!-- 3. Plukke ut kolonnen `aggression_level` -->
<!-- For å velge ut bestemte rader kan vi bruke funksjonen `filter()`. Ved hjelp av pipe-operatoren kan vi skrive steg 1 og 2 som -->
<!-- ```{r} -->
<!-- violence %>% filter(violent_treatment == "Violent") -->
<!-- ``` -->
<!-- Nå ser vi at vi bare har 126 rader igjen, og det er nettopp de radene som i kolonnen `violent_treatment` har verdi `"Violent"`. Det neste steget er å velge ut kolonnen `aggression_level`. Det gjør vi ved å bruke funksjonen `select()`, og hele sekvensen ser da slik ut (linjeskift gjør det enda mer lesbart): -->
<!-- ```{r} -->
<!-- violence %>%  -->
<!--   filter(violent_treatment == "Violent") %>%  -->
<!--   select(aggression_level) -->
<!-- ``` -->
<!-- Man kan velge flere kolonner ved å sette komma mellom kolonnenavn, og man kan i stedet velge *bort* kolonner ved å sette minustegn foran kolonnenavnet, f.eks: -->
<!-- ```{r, eval = FALSE} -->
<!-- violence %>% select(id, aggression_level) -->
<!-- violence %>% select(-id) -->
<!-- ``` -->
<!-- Nå har det seg slik at vi gjerne ønsker å hente ut den aktuelle kolonnen som en *vektor*. Det gjør vi enkelt ved å slenge på en `pull` på slutten av en pipe-sekvens. Til slutt må vi passe på å lagre vektoren med riktig navn, slik at vi får: -->
<!-- ```{r} -->
<!-- voldelig <- violence %>%  -->
<!--   filter(violent_treatment == "Violent") %>%  -->
<!--   select(aggression_level) %>%  -->
<!--   pull -->
<!-- ``` -->
<!-- Denne koden er ekvivalent med den som startet dette avsnittet i øvingen. Den er derimot mye enklere å lese, og *veldig* mye enklere å utvide til å inkludere flere operasjoner. -->
<!-- La oss se på enda en funksjon som vil være svært nyttig for oss senere. Vi kan bruke `mutate()` til å *lage nye kolonner*. La oss for eksempel si at vi vil lagre kvadratet av `aggression_level` eller summen av `aggression_level` og `id` som egne kolonner (som selvsagt er helt meningsløst i dette tilfellet, kun et eksempel). Det kan vi gjøre slik: -->
<!-- ```{r, eval = FALSE} -->
<!-- violence %>%  -->
<!--   mutate(ny1 = aggression_level^2)  -->
<!-- ``` -->
<!-- eller -->
<!-- ```{r, eval = FALSE} -->
<!-- violence %>%  -->
<!--   mutate(ny2 = id + aggression_level) -->
<!-- ``` -->
<!-- Her er `ny1` og `ny2` navn på de nye kolonnene, som vi kan velge selv. -->
<!-- **Oppgave:** Gjenta **Oppgave 3.2**, men ved å bruke teknikkene i dette avsnittet. -->
<!-- #### Interaktiv øving i `dplyr` {-} -->
<!-- Hvis du ønsker å trene mer på dette så finnes det en interaktiv modul i `swirl` som omhandler datamanipulasjon ved hjelp av `dplyr`. Hvis du ikke har gjort det alledede, skriv `install.packages("swirl")` i konsoll. Start du opp `swirl` med å skrive følgende: -->
<!-- ```{r, eval = F} -->
<!-- library(swirl) -->
<!-- install_course("Getting_and_Cleaning_Data ") # legger til nytt kursmateriale -->
<!-- swirl() -->
<!-- ``` -->
<!-- Du vil i starten bli bedt om å skrive inn ditt navn og så følger litt info om hvordan swirl fungerer. Du blir så bedt om å velge kurs. Her skal du først velge alternativet 'Getting and Cleaning Data'. Du får så se alle modulene dette kurset inneholder. I denne øvingen skal du prøve deg på modul 1 **'Manipulating Data with dplyr'**.  -->
</section>
</section>
</section>
<section id="dataøving-3" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="dataøving-3"><span class="header-section-number">7.3</span> Dataøving 3</h2>
<section id="oppgave-1-interaktiv-øvelse" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="oppgave-1-interaktiv-øvelse"><span class="header-section-number">7.3.1</span> Oppgave 1: Interaktiv øvelse</h3>
<p>Før vi tar fatt på dataanalysen begynner vi som vanlig med litt R-trening i swirl. Har du allerede installert pakken swirl (skriv <code>install.packages("swirl")</code> i konsoll hvis ikke) starter du opp swirl med å skrive følgende i konsollen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(swirl)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install_course</span>(<span class="st">"Regression_Models"</span>) <span class="co"># legger til nytt kursmateriale om regresjon</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">swirl</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du vil i starten bli bedt om å skrive inn ditt navn. Hvis du bruker samme navn som tidligere får du kanskje tilbud om å starte opp igjen der du slapp, men da kan du bare velge det nederste valget ‘No.&nbsp;Let me start something new’. Du velger så alternativet ‘Regression Models’ hvor du får se alle modulene dette kurset inneholder. I denne øvingen skal du prøve deg på modul modul 1 <strong>‘Introduction’</strong>. Her vil du lære litt om hvordan du kan bruke R til å gjøre en regresjonsanalyse ved hjelp av et treningsdatasett. Noen av kommandoene som gjennomgås i denne modulen vil komme til nytte senere i datalabben.</p>
<p>Husk at det helt til høyre vil står hvor langt du har kommet i prosent. Står du helt fast med et punkt kan du skrive <code>skip()</code> for å hoppe over dette punktet. Når du har fullført en modul blir du spurt om du vil motta ‘credit’ for å ha fullført modulen. Her kan du svare nei. Ønsker du å avbryte underveis skriver du <code>bye()</code>. Skriver du inn det samme navnet når du eventuelt starter swirl igjen kan du fortsette der du slapp. Husk å avslutt swirl (<code>esc</code>) før du begynner på del to av øvingen. Lykke til!</p>
</section>
<section id="oppgave-2-regresjonsanalyse" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="oppgave-2-regresjonsanalyse"><span class="header-section-number">7.3.2</span> Oppgave 2: Regresjonsanalyse</h3>
<p>Et rock-and-roll museum åpnet i Atlanta i 1990. Museet lå i en sentral del av byen i nærheten av mange ulike butikker. Mot slutten av juli måned i 1992 startet en stor brann i en av disse butikkene som ødela hele kvartalet, inkludert museet. Heldigvis var museet forsikret, både mot selve brannskadene, og mot tapte billettinntekter i gjennoppbyggingsperioden.</p>
<p>Vanligvis vil et forsikringsselskap beregne erstatningsbeløpet under antakelsen om at besøkstallene i gjenoppbyggingsperioden ville vært på samme nivå som besøkstallene i tiden før brannen. I dette tilfellet mente derimot eierne av museet at besøkstallene var <em>økende</em>, slik at de reelt sett hadde krav på et større erstatningsbeløp. Argumentet var basert på besøkstallene til en fornøyelsespark like ved. Fornøyelsesparken åpnet i desember 1991, slik at museet og parken opererte sammen i de siste fire ukene av 1991, og de første 28 ukene i 1992 før brannen ødela museet.</p>
<p>Museet åpnet igjen i april 1995, men var da betydelig større enn det var opprinnelig. Data for besøkstall for museet og fornøyelsesparken finner vi i regnearket <a href="datasett/C16-01.xlsx"><code>C16-01.xlsx</code></a>. Som i de to foregående dataøvingene legger du denne filen i en mappe på maskinen din, og oppretter et tomt R-script der du lagrer koden for denne oppgaven.</p>
<p><strong>Oppgave 2.1:</strong> Kikk raskt på datasettet i Excel eller tilsvarende. Du ser at det er tre kolonner, en som angir ukenummer (<code>Week</code>, teller fra 1 til 205), en som angir ukentlig besøkstall på museet (<code>Museum</code>) og en som angir ukentlig besøkstall i fornøyelsesparken (<code>A-Park</code>). Legg merke til at besøkstallet i museet er null fra og med uke 33, til og med uke 179, som er perioden fra brannen til nyåpning.</p>
<p><strong>Oppgave 2.2:</strong> Last så datasettet inn i R som før ved hjelp av <code>read_excel()</code>-funksjonen. Gi det et passelig navn (f.eks <code>visits</code>), og sjekk raskt at det har gått bra ved å taste inn datanavnet i konsollen. Da skal det se omtrent slik ut:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>visits</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 205 × 3
    Week Museum `A-Park`
   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1     1    787     1379
 2     2   1179     1396
 3     3   4225     5332
 4     4   1336     1477
 5     5   2122     3717
 6     6   1136     1663
 7     7   2413     3573
 8     8   1399     2086
 9     9   1528     2503
10    10   1788     2553
# ℹ 195 more rows</code></pre>
</div>
</div>
<p>Legg merke til følgende:</p>
<ul>
<li>Observasjonene ser ut til å være de samme som vi så da vi kikket på selve regnearket. Det er alltid en god vane å forsikre seg om at R har lest inn datasettet på riktig måte.</li>
<li>Et av variabelnavnene har fått noen rare tødler rundt seg. Grunnen til det er at <code>A-park</code> inneholder en bindestrek, så for at R ikke skal tolke det tegnet som et minustegn (og dermed gi oss et mareritt med feilmeldinger), må vi alltid bruke disse tødlene når vi refererer til denne variabelen. (På tastaturet som forfatteren av disse ord skriver på, er det <code>Shift +</code> tasten til venstre for <code>Backspace</code>.</li>
</ul>
<p><strong>Oppgave 2.3:</strong> Før vi går videre, må vi få et bedre begrep om problemet ved å kikke grafisk på observasjonene. La oss plotte observasjonene i et linjeplott for å se hvordan de utvikler seg over tid, ved å ha ukenummer på <span class="math inline">\(x\)</span>-aksen og besøkstall på <span class="math inline">\(y\)</span>-aksen. Vi kan lage et enkelt plott for besøkstall for museet ved å skrive</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Laster først ggplot-pakken (det trenger vi bare gjøre en gang i skriptet)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)        </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Lager et enkelt linjeplott:</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits, <span class="fu">aes</span>(<span class="at">x =</span> Week, <span class="at">y =</span> Museum)) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Du kan legge til besøkstall for fornøyelsesparken ved å plusse på en ny linje med <code>geom_line()</code>, men da må du spesifisere <code>y</code>-variabelen på nytt. Hele plottekommandoen blir da:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(visits, <span class="fu">aes</span>(<span class="at">x =</span> Week, <span class="at">y =</span> Museum)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">A-Park</span><span class="st">`</span>))</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vi ser at det er en sterk sammenheng mellom besøkstallene til museet og parken, spesielt etter gjenåpningen i 1995, og det skal vi utnytte når vi senere skal beregne erstatningssummen.</p>
<p><strong>Oppgave 2.4:</strong> Juster på argumentene i <code>geom_line()</code>-funskjonene, og legg til flere “lag” på samme måte som vi gjorde for å pynte på figuren i oppgave 8 i kapittel <a href="01-intro-til-r.html#sec-r-ekstra" class="quarto-xref"><span>Seksjon 1.12</span></a> (det er 100% lov å Google). Dette ser bedre ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Oppgave 2.5:</strong> La oss nå ta utgangspunkt i forsikringsselskapets påstand: besøkstallet i perioden der museet er stengt skal beregnes ved hjelp av observasjonene <em>før brannen</em>. Vi estimerer parametrene i en enkel regresjonsmodell</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1x_i + \epsilon,\]</span> der responsvariabelen <span class="math inline">\(y_i\)</span> er besøkstallet på museet på dag nr. <em>i</em>, og <span class="math inline">\(x_i\)</span> er besøkstallet i fornøyelsesparken samme dag. Datasettet vi skal bruke er altså <em>de 32 første radene</em> i datasettet <code>visits</code>. Da kan vi enten lage en ny tabell som består av de 32 første radene (for eksempel ved hjelp av <code>filter(Week &lt;= 32)</code>), eller så kan vi bruket argumentet <code>subset</code> i <code>lm()</code>-funkesjonen til å spesifisere hvilke observasjoner som skal brukes for å estimere modellen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Museum <span class="sc">~</span> <span class="st">`</span><span class="at">A-Park</span><span class="st">`</span>, <span class="at">data =</span> visits, <span class="at">subset =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Oppgave 2.6:</strong> Pakken <code>stargazer</code> inneholder funksjoner for å lage pene regesjonstabeller automatisk fra regresjonsobjekter i R. Pakken må installeres og lastes på vanlig måte:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"stargazer"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Inne i <code>stargazer</code>-pakken er det en funksjon som også heter <code>stargazer()</code>. Hvis du ikke har sett den brukt før (f.eks i forelesning), kan du lese mer om den ved hjelp av hjelpefunksjonen: <code>?stargazer</code>. Bruk så <code>stargazer()</code> til å lage følgende regresjonsutskrift (hint: bruk argumentet <code>type = "text"</code>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                              Museum           
-----------------------------------------------
`A-Park`                     0.693***          
                              (0.018)          
                                               
Constant                      16.229           
                             (114.695)         
                                               
-----------------------------------------------
Observations                    32             
R2                             0.979           
Adjusted R2                    0.979           
Residual Std. Error      355.588 (df = 30)     
F Statistic          1,424.094*** (df = 1; 30) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p><strong>Oppgave 2.7:</strong> Lag tre diagnoseplott etter mal som er gitt i forelesningsnotatene: Et som viser residualene i regresjonsmodellen i et spredningsplott, et QQ-plott, og et histogram. Kan du gjøre en grov vurdering om hvorvidt forutsetningene for lineær regresjon er oppfylt?</p>
<p><strong>Oppgave 2.8:</strong> Bruk denne regresjonsmodellen til å beregne hva besøkstallet <em>hadde vært</em> dersom museet hadde vært åpent som vanlig. Dette kan vi gjøre ved å bruke <code>predict()</code>-funksjonen. Følg oppskriften under nå, så skal du prøve å gjøre det selv etterpå.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vi lager et nytt datasett bestående av de ukene der museet var stengt:</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>visits_pred <span class="ot">&lt;-</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  visits <span class="sc">%&gt;%</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Museum <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Week"</span>, <span class="st">"A-Park"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Bruker predict()-funksjonen til å predikere tilhørende y'er:</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>predicted_visits1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg1, <span class="at">newdata =</span> visits_pred)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Til slutt legger vi til de predikerte verdiene som en ny kolonne i visits_pred:</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>visits_pred<span class="sc">$</span>predikert1 <span class="ot">&lt;-</span> predicted_visits1</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>De predikerte besøkstallene er nå lagret som kolonne <code>predicted1</code> i datasettet <code>visits_pred</code>.</p>
<p><strong>Oppgave 2.9</strong> For å få bedre greie på hvordan prediksjonene egentlig ser ut kan vi legge dem til figuren vår fra over. La oss lage en blå stiplet linje, og det kan vi gjøre med å legge til enda et kall til <code>geom_lines()</code>. Denne gangen må vi bruke flere argumenter:</p>
<ul>
<li>Vi må bruke argumentet <code>data</code> til å si at tallene vi skal plotte for den nye linjen nå ligger i datasettet <code>visits_pred</code>, og ikke <code>visits</code>.</li>
<li>Vi må bruke argumentet <code>colour</code> til å fortelle hvilken farge vi skal ha på linjen.</li>
<li>Vi må bruke argumentet <code>linetype</code> til å fortelle at vi vil ha en stiplet linje.</li>
</ul>
<p>Ta for deg figuren du lagde i oppgave 2.4, og legg til følgende linjer (husk å få med en <code>+</code> mellom hvert lag):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> Week, <span class="at">y =</span> predikert1), </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> visits_pred, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">colour =</span> <span class="st">"blue"</span>, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">linetype =</span> <span class="st">"dashed"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Da blir figuren min seende slik ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Oppgave 2.10:</strong> Kommenter kort regresjonsutskriften fra oppgave 2.6 og figuren fra oppgave 2.9. Ser det fornuftig ut?</p>
<p><strong>Oppgave 2.11:</strong> Se på saken heller fra museets side. De mener at det er besøkstallene fra <em>etter</em> åpningen i 1995 som skal brukes til å estimere regresjonsmodellen. Det er lett å forstå hvorfor de ønsker det, for da ser det ut som at det er omtrent like mange besøkende på museet som i fornøyelsesparken.</p>
<p>Repeter oppgave 2.5, men nå bruker du altså besøkstallene fra etter åpningen til å estimere regresjonskoeffisientene. <strong>Hint 1:</strong> Det eneste du må endre er hva som skal inn i <code>subset</code>-argumentet. <strong>Hint 2:</strong> Stigningstallet i den nye modellen skal være 0.97.</p>
<p><strong>Oppgave 2.12:</strong> Beregn hvilke besøkstall museet hadde hatt i perioden det var stengt ved å legge til grunn den nye regresjonsmodellen etter mønster fra oppgave 2.8, og legg dem inn i figuren etter mønster fra oppgave 2.9. Figuren blir skal da se omtrent slik ut hvis vi bruker en finn grønnfarge (<code>forestgreen</code>) til den siste linjen:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Oppgave 2.13:</strong> Når vi ser hvor tett de to besøkstallene beveger seg etter nyåpningen er det ikke rart at de beregnede besøkstallene basert på den nye modellen (markert i grønt over) følger observasjoenen fra fornøyelsesparken.</p>
<p>Anta at hver billett til museet koster $6.99. Hvor stor er differansen mellom erstatningskravet til museet og tilbudet til forsikringsselskapet?</p>
<p><strong>Oppgave 2.14 (Diskusjon):</strong> Det er ganske stor forskjell mellom tilbud og krav, men hvis vi tenker oss om skjønner vi fort at begger parter befinner seg i en klassisk <em>catch-22</em>. Hvis den ene partens argument fører til en utbetaling som er for stor eller for liten fordi de tar utgangspunkt i slutten eller starten på en stigende utvikling, må nødvendigvis det motsatte standpunkt også være galt av nøyaktig samme grunn. Kan du foreslå et kompromiss?</p>
<!-- ### Oppgave 3: Rapporter basert på R-analyser -->
<!-- Ofte er det ønskelig å bruke resultater fra R inn i rapporter, artikler og foredrag. I MET4 skal du blant annet levere både en obligatorisk innlevering og en hjemmeksamen. Det er fullt mulig å åpne et hvilken som helst tekstdokument (f.eks Word) for så å belage seg på en 'klipp og lim'-tilnærming. I R-studio kan man lagre figurer ved å trykke på 'Export' fanen i vinduet nede til høyre og så 'Save as', eventuelt bruke `ggsave()`-funksjonen til å lagre plott laget med `ggplot2`. Disse kan så åpnes i det samme dokumentet.  -->
<!-- En klipp og lim-tilnærming kan være tidkrevende og det finnes verktøy som gjør det lett å lage ganske så elegante rapporter av R-analyser. I de følgende oppgavene gir vi to alternativer til å lage rapporter. Den første metoden er noe enklere enn den andre.  -->
<!-- **Oppgave 3.1:**  Rstudio kan lage en enkel rapport ut av .R filen din ved at du trykker **ctrl + shift + k** (**cmd + shift + K** på mac).  Prøv det med .R filen du laget i Oppgave 2. Første gang du gjør dette blir du bedt om å installere noen pakker og det aksepterer du. Du får så opp et vindu som ber deg velge format på rapporten: -->
<!-- ```{r, echo = FALSE} -->
<!-- knitr::include_graphics("bilder/compile.PNG") -->
<!-- ``` -->
<!-- Har du tilgang til 'Word' kan du velge 'MS word', hvis ikke velger du formatet HTML. For PDF format er du avhengig av å installere 'latex'. Rapporten vil da legge seg i mappen hvor du har lagret datasettet og .R filen. Fordelen med å velge 'MS word' formatet er at du kan bruke den samme word filen til å redigere og kommentere resultatene.      -->
<!-- **Oppgave 3.2 (litt mer krevende):** Man kan også lage rapporter ved å bruke et tekstformat kalt R Markdown. Dette er nok litt mer utfordrende enn tilnærmingen i oppgaven over, men vil gi svært pene raporter/dokumenter. Ønsker du å utforske denne muligheten så ta en titt på [denne videoguiden](https://www.youtube.com/watch?v=tKUufzpoHDE). -->
</section>
</section>
<section id="dataøving-4" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="dataøving-4"><span class="header-section-number">7.4</span> Dataøving 4</h2>
<p>En produsent som vil selge kraft til Nord Pool leverer salgsbud til kraftbørsen som spesifiserer, for hver time neste dag, hvor mange megawatt (MW) man er villig til å produsere til ulike priser. Fristen for å levere salgsbud er kl 12:00 dagen før produksjonen skal finne sted. For en vindkraftprodusent er det flere usikre faktorer man må ta stilling til når man skal levere salgsbud for neste dag:</p>
<ol type="1">
<li>Timeprisene i spotmarkedet (Euro/MW) er ukjente (blir ikke offentliggjort før kl 12:45).</li>
<li>For å vite hvor mange megawatt (MW) man kan produsere i en gitt time trenger man å vite vindstyrken. Selv med gode værprognoser vil det fremdeles være betydelig usikkerhet knyttet til vindstyrken i de ulike timene neste dag.</li>
<li>Dersom den faktiske produksjonen avviker fra det man har meldt inn vil det påløpe en straffekostnad. I timer med mye vind vil man måtte selge den overskytende produksjonen til en lavere pris enn spotprisen, og i timer med lite vind vil man måtte kompensere fleksible produsenter for å dekke opp for den manglende produksjonen. Straffekostnaden (Euro/MW) for over- eller underproduksjon er en ukjent størrelse på budgivningstidspunktet.</li>
</ol>
<p>I denne dataøvingen skal vi konsentrere oss om å lage prognoser for spotprisen. I case 3 i BED4 kommer dere også til å få bruk for vindstyrken og straffekostnadene, men å lage prognoser for disse vil kreve ferdigheter utover det som gjennomgås i MET4.</p>
<p>Hvis du ikke tar BED4 dette semesteret, så går det helt fint også. Dataøvingen står fint på egne bein, og du kan uansett komme tilbake til disse resultatene hvis du for eksempel skal ta BED4 på et senere tidspunkt.</p>
<p>Du har kanskje lagt merke til at R-kodingen i tidsrekkemodulen har en litt forskjellig stil fra det vi har gjort tidligere i kurset. I denne øvingen vil derfor størsteparten av koden blir oppgitt i oppgaveteksten. Din oppgave blir å kjøre koden, få ut figurer og resultater, samt å kommentere og tolke resultatene.</p>
<p>Vi starter med å laste inn noen pakker som vi kommer til å trenge. Som vanlig må du installere pakkene først dersom du ikke har gjort det allerede:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forecast' was built under R version 4.3.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="oppgave-1-last-inn-og-se-på-datasettet" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="oppgave-1-last-inn-og-se-på-datasettet"><span class="header-section-number">7.4.1</span> Oppgave 1: Last inn og se på datasettet</h3>
<p>Denne gang er datasettet pakket inn i en såkalt <code>.Rdata</code>-fil. Det er et enkelt filformat for å lagre R-objekter. Last ned <a href="datasett/p_da.Rdata">p_da.Rdata</a>, og last datasettet inn i R ved å kjøre følgende kommando (der du selvsagt har satt arbeidsmappen til der du har lagt datafilen):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"p_DA.Rdata"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du skal nå få to tidsrekker i minnet: <code>n03</code> og <code>no5</code>, som i figuren under:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bilder/environ.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
<p>Disse to tidsrekkene inneholder strømprisen i to prisområder i Norge hver time fra 1. januar 2022 til og med 21. september 2022. Tidsrekken <code>no3</code> inneholder prisen for Midt-Norge (NO3) og <code>no5</code> inneholder prisen for Vest-Norge (NO5).</p>
<p>Vi konsentrerer oss om NO3 i første omgang, og kikker raskt på datasettet ved å plotte tidsrekken direkte med <code>autoplot()</code>-funksjonen som vi finner i <code>forecast</code>-pakken:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(no3)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>På <span class="math inline">\(x\)</span>-aksen har vi antall dager siden 1. januar 2022. Skriv en kort kommentar der du peker på noen viktige karakteristikker ved denne tidsrekken. Du må gjerne bruke <code>xlim</code>-argumentet i <code>plot()</code>-funksjonen for å zoome inn og se på mindre tidsperioder. Ser tidsrekken ut til å være stasjonær?</p>
</section>
<section id="oppgave-2-gjem-bort-den-siste-dagen-slik-at-vi-kan-sjekke-prediksjonene-våre" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="oppgave-2-gjem-bort-den-siste-dagen-slik-at-vi-kan-sjekke-prediksjonene-våre"><span class="header-section-number">7.4.2</span> Oppgave 2: Gjem bort den siste dagen slik at vi kan sjekke prediksjonene våre</h3>
<p>For å kunne gjøre en vurdering av hvor gode prediksjonene våre er, deler vi nå datasettet vårt i to, der vi tar ut de siste 24 timene som vi kan bruke til å evaluere prediksjonene. Vi kaller disse to delene <code>no3_train</code>, som er den lange delen som vi skal bruke til å estimere en modell (<em>trene</em> en modell), og <code>no3_test</code> som er de siste 24 timene som vi skal bruke til å teste etterpå om modellen duger.</p>
<p>Vi bruker funksjonen <code>window()</code> til å hente ut deler av tidsrekken, der vi må spesifisere start- og sluttverdier som vektorer med to elementer; en for dag og en for time. Det er 264 dager i datasettet vårt, så da får vi:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>no3_train <span class="ot">&lt;-</span> <span class="fu">window</span>(no3, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">263</span>, <span class="dv">23</span>))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>no3_test  <span class="ot">&lt;-</span> <span class="fu">window</span>(no3, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">264</span>, <span class="dv">0</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">264</span>, <span class="dv">23</span>))</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du kan nå dobbelsjekke at du har fått ut en enkelt dag i <code>no3_test</code> ved å kjøre <code>autoplot(no3_test)</code>.</p>
</section>
<section id="oppgave-3-hent-ut-sesong-og-trend" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="oppgave-3-hent-ut-sesong-og-trend"><span class="header-section-number">7.4.3</span> Oppgave 3: Hent ut sesong og trend</h3>
<p>Vi har lært at et første steg i tidsrekkeanalyse er å hente ut eventuelle sesong og trendkomponenter. Vi har også sett at det er en enkel funksjon i R som kan gjøre dette for oss, nemlig <code>stl()</code>, slik vi så i <a href="#trend-og-sesong">seksjonen om trend og sesong</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>dekomponert <span class="ot">&lt;-</span> <span class="fu">stl</span>(no3_train, <span class="at">s.window =</span> <span class="st">"periodic"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(dekomponert)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Det var ikke så lett å se detaljer i sesongkomponenten i dette plottet, så vi zoomer inn på en mindre del av x-aksen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(dekomponert) <span class="sc">+</span> <span class="fu">xlim</span>(<span class="dv">245</span>, <span class="dv">260</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Gi en kort beskrivelse av de ulike komponentene i tidsrekken.</p>
</section>
<section id="oppgave-4-prediker-treningstidsrekken-24-steg-frem-og-visualiser-resultatene." class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="oppgave-4-prediker-treningstidsrekken-24-steg-frem-og-visualiser-resultatene."><span class="header-section-number">7.4.4</span> Oppgave 4: Prediker treningstidsrekken 24 steg frem og visualiser resultatene.</h3>
<p>Vi skal nå slippe veldig billig unna! Denne oppgaven består egentlig av flere steg:</p>
<ol type="1">
<li>Finn en statistisk modell for residualtidsrekken. Bruk for eksempel <code>auto.arima()</code> for å finne den ARIMA-modellen som passer best til treningsdatasettet.</li>
<li>Bruk denne modellen til å predikere residualtidsrekken 24 steg frem.</li>
<li>Skriv trendserien 24 steg frem. Her må vi ha en fornuftig måte å ekstrapolere som vi ikke har dekket eksplisitt i materialet vårt.</li>
<li>Hekt på en ny dag med den daglige sesongvariasjonen.</li>
<li>Legg sammen prediksjonene av residualene, trend- og sesongkomponenten for å lage en prediksjon av prisserien.</li>
</ol>
<p>Vi kunne godt satt oss ned for å programmere disse stegene hver for seg. Heldigvis har noen gjort dette før oss, gjennom funksjonen <code>forecast()</code> i <code>forecast</code>-pakken. For å lage en prognose må vi sende inn den dekomponerte tidsrekken, sammen med en spesifikasjon av hvilken type statistisk tidsrekkemodell vi ønsker å tilpasse til residualtidsrekken (vi velger ARIMA, for det er den modellen vi har lært om), og hvor mange steg frem vi ønsker å predikere. Vi kan også legge til signifikansnivået for et prediksjonsintervall som vi vil ha på 95%:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>prognose <span class="ot">&lt;-</span> <span class="fu">forecast</span>(dekomponert, <span class="at">method =</span> <span class="st">"arima"</span>, <span class="at">h =</span> <span class="dv">24</span>, <span class="at">level =</span> <span class="dv">95</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vi kan visualisere resultatet ved hjelp av <code>autoplot()</code>. For å kunne se noe fornuftig i plottet så tar vi bare med de 100 siste observerte tidsstegene i tillegg til de 24 prediksjonene:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(prognose, <span class="at">include =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Gi en kommentar til dette plottet.</p>
</section>
<section id="oppgave-5-sammenlign-prediksjonene-med-de-faktiske-observasjonene" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="oppgave-5-sammenlign-prediksjonene-med-de-faktiske-observasjonene"><span class="header-section-number">7.4.5</span> Oppgave 5: Sammenlign prediksjonene med de faktiske observasjonene</h3>
<p>Vi kan nå finne frem igjen <code>no3_test</code>, som er en tidsrekke som inneholder de faktiske observasjonene for dagen der vi har gjort prediksjoner. La oss sammenligne. En måte å visualisere dette på er å hente ut prediksjonene fra <code>prognose</code>-objektet (de ligger under <code>$mean</code>), og sette det sammen med de faktiske observasjonene (som vi har lagret i <code>no3_test</code>). Vi kan også hente ut prediksjonsintervallene, og sette alt inn i en data frame:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setter prediksjoner, intervaller og observasjoner inn i samme data frame.  </span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>prediksjoner <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>,                            <span class="co"># Timer i døgnet for x-aksen</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">prediksjon =</span> prognose<span class="sc">$</span>mean,          <span class="co"># Predikerte priser</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">nedre =</span> prognose<span class="sc">$</span>lower[,<span class="dv">1</span>],          <span class="co"># Nedre og øvre prediksjonsintervaller</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ovre =</span> prognose<span class="sc">$</span>upper[,<span class="dv">1</span>],</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">observert =</span> no3_test                 <span class="co"># De faktiske observasjonene</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Lager plott</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prediksjoner) <span class="sc">+</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> prediksjon), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span>    <span class="co"># Prediksjoner</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> nedre), <span class="at">colour =</span> <span class="st">"darkred"</span>) <span class="sc">+</span>          <span class="co"># Nedre grense</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> ovre), <span class="at">colour =</span> <span class="st">"darkred"</span>) <span class="sc">+</span>           <span class="co"># Øvre grense</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> observert), <span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span>         <span class="co"># Observert</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">""</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"24 timers prognose av strømpris"</span>) <span class="sc">+</span></span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I dette plottet er prediksjonene av strømprisen vist som en stiplet linje, mens de prisene som faktisk ble observert er vist som en tykk heltrukken linje. Kommenter plottet.</p>
</section>
<section id="oppgave-6-lag-prediksjoner-for-neste-dag" class="level3" data-number="7.4.6">
<h3 data-number="7.4.6" class="anchored" data-anchor-id="oppgave-6-lag-prediksjoner-for-neste-dag"><span class="header-section-number">7.4.6</span> Oppgave 6: Lag prediksjoner for neste dag</h3>
<p>Så langt har vi brukt alle dagene i datasettet vårt <em>bortsett fra den siste</em> til å predikere strømprisen på den siste dagen. Resultatene ser ut til å være gode. Du kan nå gjenta denne prosedyren, men i stedet for tidsrekken <code>no3_train</code> skal du nå bruke hele tidsrekken <code>no3</code> til å predikere prisen for dagen etter det – den 22. september 2022 – en dag der vi ikke har de faktisk realiserte prisene i datasettet vårt.</p>
<p>Du skal få et prediksjonsplott som ser slik ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Du kan så samle prediksjonene i en data frame som i forrige oppgave, men der vi selvsagt ikke kan ha med en kolonne med observerte priser, siden vi ikke har dem tilgjengelige. Den endelige tabellen med observasjoner skal se slik ut:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    x prediksjon       nedre      ovre
1   1   36.02709  12.1495723  59.90460
2   2   36.45012   3.3208432  69.57940
3   3   37.28821  -3.5736943  78.15012
4   4   38.53910  -7.6663095  84.74451
5   5   39.89017  -9.5638644  89.34420
6   6   42.27134  -9.0837471  93.62643
7   7   43.55218  -8.9521015  96.05647
8   8   49.43543  -3.8202856 102.69114
9   9   54.36794   0.5712673 108.16460
10 10   56.23131   2.0083818 110.45425
11 11   54.74981   0.1657312 109.33389
12 12   51.32547  -3.5811987 106.23213
13 13   49.64904  -5.5564816 104.85456
14 14   47.41288  -8.0764075 102.90216
15 15   46.22697  -9.5361822 101.99013
16 16   46.70673  -9.3236145 102.73708
17 17   46.61878  -9.6740934 102.91166
18 18   48.72382  -7.8282025 105.27583
19 19   50.11119  -6.6974082 106.91979
20 20   50.21319  -6.8499490 107.27634
21 21   50.04209  -7.2739046 107.35808
22 22   48.34032  -9.2270566 105.90769
23 23   45.94396 -11.8734681 103.76139
24 24   42.20995 -15.8563146 100.27621</code></pre>
</div>
</div>
<p>Kommenter.</p>
</section>
<section id="oppgave-7-lagre-prediksjonene-i-en-excel-fil." class="level3" data-number="7.4.7">
<h3 data-number="7.4.7" class="anchored" data-anchor-id="oppgave-7-lagre-prediksjonene-i-en-excel-fil."><span class="header-section-number">7.4.7</span> Oppgave 7: Lagre prediksjonene i en excel-fil.</h3>
<p>Hvis du tar BED4 dette semesteret (eller skal ta BED4 på et senere tidspunkt) så trenger du nå å eksportere disse prediksjonene til en Excel-fil. En pakke som kan gjøre dette er <code>writexl</code> (som du, igjen, er nødt til å installere før bruk: <code>install.packages("writexl")</code>). Hvis du har lagret prediksjonene i en data frame som heter <code>prediksjoner2</code>, så kan du skrive den ut i en Excel-fil på følgende måte:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_xlsx</span>(prediksjoner2, <span class="st">"no3_prediksjoner.xlsx"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du skal nå ha en Excel-fil med prediksjonene dine i filen <code>no3_prediksjoner.xlsx</code> i arbeidsmappen din.</p>
</section>
<section id="oppgave-8-gjør-det-samme-for-no5" class="level3" data-number="7.4.8">
<h3 data-number="7.4.8" class="anchored" data-anchor-id="oppgave-8-gjør-det-samme-for-no5"><span class="header-section-number">7.4.8</span> Oppgave 8: Gjør det samme for <code>no5</code></h3>
<p>Du kan nå gjenta øvelsen over for å få ut samme type prediksjoner for det andre prisområdet. Tidsrekken finner du i <code>no5</code> og prediksjonsplottet ser slik ut:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07-dataøvinger_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Data framen med prediksjonene skal se slik ut:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>prediksjoner3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>,                            <span class="co"># Timer i døgnet for x-aksen</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">prediksjon =</span> prognose3<span class="sc">$</span>mean,          <span class="co"># Predikerte priser</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nedre =</span> prognose3<span class="sc">$</span>lower[,<span class="dv">1</span>],          <span class="co"># Nedre og øvre prediksjonsintervaller</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ovre =</span> prognose3<span class="sc">$</span>upper[,<span class="dv">1</span>]</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>prediksjoner3</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    x prediksjon    nedre     ovre
1   1   346.3622 310.5934 382.1310
2   2   338.6796 286.6895 390.6698
3   3   344.5907 281.3350 407.8464
4   4   358.3632 286.3178 430.4086
5   5   378.5406 300.1708 456.9105
6   6   402.4033 319.0857 485.7209
7   7   424.7142 337.5252 511.9031
8   8   441.2872 350.5347 532.0397
9   9   441.0059 346.6958 535.3159
10 10   417.9910 319.6357 516.3462
11 11   393.0380 290.0513 496.0247
12 12   369.8592 261.5774 478.1409
13 13   352.9104 239.0015 466.8192
14 14   346.8510 227.3225 466.3794
15 15   350.4399 225.7535 475.1262
16 16   367.2739 238.1157 496.4321
17 17   390.4917 257.6416 523.3417
18 18   415.6232 279.7278 551.5187
19 19   433.2506 294.7538 571.7474
20 20   437.4176 296.4963 578.3390
21 21   429.5152 286.1074 572.9229
22 22   412.5279 266.3558 558.7000
23 23   390.6720 241.3325 540.0115
24 24   368.3594 215.4343 521.2845</code></pre>
</div>
</div>
<p>Du lagrer den som en Excel-fil slik:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_xlsx</span>(prediksjoner3, <span class="st">"no5_prediksjoner.xlsx"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du kan laste ned de ferdige Excel-filene her for å kontrollere at du har fått det til: <a href="no3_prediksjoner.xlsx"><code>no3_prediksjoner.xlsx</code></a> og <a href="no5_prediksjoner.xlsx"><code>no5_prediksjoner.xlsx</code></a>.</p>
</section>
</section>
<section id="dataøving-5" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="dataøving-5"><span class="header-section-number">7.5</span> Dataøving 5</h2>
<section id="oppgave-1-interaktiv-øvelse-1" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="oppgave-1-interaktiv-øvelse-1"><span class="header-section-number">7.5.1</span> Oppgave 1: Interaktiv øvelse</h3>
<p>Før vi tar fatt på dataanalysens begynner vi som vanlig med litt R-trening i swirl. Har du allerede installert pakken swirl (skriv <code>install.packages("swirl")</code> i konsoll hvis ikke) starter du opp swirl med å skrive følgende i konsollen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(swirl)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">swirl</span>()</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Du vil i starten bli bedt om å skrive inn ditt navn og så følger litt info om hvordan swirl fungerer. Du blir så bedt om å velge kurs. Her skal du først velge alternativet ‘R Programming’. Merk at du kanskje må trykke alternativet <strong>‘No.&nbsp;Let me start something new’</strong> for å komme tilbake til hovedmenyen etter å ha brukt swirl tidligere. Du får så se alle modulene dette kurset inneholder. I denne øvingen skal du prøve deg på modul 9 <strong>‘Functions’</strong>. I denne modulen vil du lære litt om funksjoner i R.</p>
<p>Merk at det helt til høyre vil står hvor langt du har kommet i prosent. Står du helt fast med et punkt kan du skrive <code>skip()</code> for å hoppe over dette punktet. Når du har fullført en modul blir du spurt om du vil motta ‘credit’ for å ha fullført modulen. Her kan du svare nei. Ønsker du å avbryte underveis skriver du <code>bye()</code>. Skriver du inn det samme navnet når du eventuelt starter swirl igjen kan du fortsette der du slapp. Husk å avslutt swirl (<code>esc</code>) før du begynner på del to av øvingen. Lykke til!</p>
</section>
<section id="oppgave-2---maskinlæring-logistisk-regresjon-og-k-nærmeste-naboer" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="oppgave-2---maskinlæring-logistisk-regresjon-og-k-nærmeste-naboer"><span class="header-section-number">7.5.2</span> Oppgave 2 - Maskinlæring: Logistisk regresjon og k nærmeste naboer</h3>
<p>I denne oppgaven skal vi se på de samme dataene som ble brukt i forelesningen om logistisk regresjon. Vi har data på 10000 kredittkortkunder og vi ønsker å kunne bygge og trene en best mulig modell til å predikere hvilke kunder som vil misligholde sin gjeld.</p>
<p><strong>Oppgave 2.1:</strong> Vi starter med å få tak i dataene. Disse er integrert i pakken <code>ISLR</code>. Last inn pakken og ta en titt på dataene ved bruk av følgende linjer (hvordan du kommenterer er opp til deg):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)       <span class="co"># Pakke som inneholder dataene     </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Default)       <span class="co"># Viser starten på dataframen</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Default)        <span class="co"># Viser hvilke typer variabler dataframen inneholder</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Responsvariabelen er
<ul>
<li>: Dette er en kategorisk variabel. Misligholdt kunden gjelden?</li>
</ul></li>
<li>Forklaringsvariabler:
<ul>
<li>: Kategorisk</li>
<li>: Kontinuerlig, størrelsen på gjelden ($)</li>
<li>: Kontinuerlig, kundens årlige inntekt ($)</li>
</ul></li>
</ul>
<p><strong>Oppgave 2.2:</strong> Det neste vi gjør er å visuelt undersøke avhengigheten mellom det å misligholde (<code>default</code>) og hvor stor gjeld (<code>balance</code>) kunden har . Vanligvis når vi visuelt skal inspisere sammenhengen mellom to variabler lager vi et spredningsplott. Men når den ene variabelen er kategorisk er det mer informativt å sammenligne to boksplott av den kontinuerlige variabelen for hver av gruppene den kategoriske variabelen representer. Dette kan gjøres på følgende måte:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(balance <span class="sc">~</span> default, <span class="at">data =</span> Default,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"balance"</span>, <span class="at">xlab =</span> <span class="st">"default"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Her er det formelen <code>balance ~ default</code> som gjør at <code>boxplot()</code> funksjonen lager to boksplott av <code>balance</code>; et for gruppen som misligholdt (“Yes”) og et for gruppen som ikke misligholdt (“No”). Reflekter over figuren og gjør deg opp en mening om sammenhengen mellom <code>default</code> og <code>balance</code>.</p>
<p><strong>Oppgave 2.3:</strong> Det er lurt å dele inn dataene i et treningssett og et testsett når vi driver med maskinlæring. Treningsettet bruker vi til å tilpasse (trene/lære) modellen, mens testsettet bruker vi til å se hvor godt forskjellige modeller presterer. Dette kan gjøres på flere måter, men vi velger her å bruke pakken <code>dplyr</code> som ble beskrevet i siste del av datalabb 2.</p>
<p>Først legger vi til en unik id til hver kunde. Vi lar id-nummeret være lik radnummeret til kunden og til dette bruker vi funksjonen <code>mutate</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> Default <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">row_number</span>()) </span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Siden vi nå skal trekke et utvalg av dataene våre kan det være lurt å sikre at resultatet er reprodusibelt ved å sette</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>foran koden som følger. Du kan gjerne velge et annet tall enn 123, men når en gjør dette i forkant av en tilfeldig trekning i R er trekningen bestemt.</p>
<p>Så trekker vi et treningssett bestående av 70 % av dataene ved bruk av funksjonen <code>sample_frac</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span>  </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_frac</span>(.<span class="dv">70</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>De resterende kundene bruker vi som testsett ved bruk av funksjonen <code>anti_join</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span>         <span class="co"># Treningssettet er da de resterende 30 % av dataene</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(train, <span class="at">by =</span> <span class="st">'id'</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Koden over trekker ut alle kunder som ikke har lik <code>id</code> som i treningssettet som derfor svarer til de resterende 30 % av dataene.</p>
<p><strong>Oppgave 2.4:</strong> Vi forklarer i denne oppgaven hvordan en logistisk regresjonsmodell kan estimeres, tolkes og brukes. Du vil måtte lage nye modeller med tilsvarende koder i oppgavene som følger.</p>
<p>Vi lager en modell hvor vi bruker variabelen <code>balance</code> (gjeld) som forklaringsvariabel. Vi bruker da funksjonen <code>glm</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> balance, <span class="at">data =</span> train,</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">family =</span> <span class="st">"binomial"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Syntaksen til <code>glm</code>-funksjonen er veldig lik den vi bruker i regresjon (<code>lm</code>-funksjonen) bortsett fra at vi må spesifisere argumentet <code>family = "binomial"</code> for at å fortelle <code>R</code> at vi ønsker å gjøre en logistisk regresjon. Merk at vi bruker treningssettet til å estimere (trene) modellen ved å spesifisere argumentet <code>data = train</code>.</p>
<p>Det kan være lurt å se om forklaringsvariabelen <code>balance</code> har en signifikant effekt på <code>default</code> ved å bruke <code>summary</code> funksjonen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For å tolke hvilken effekt <code>balance</code> (gjeld) har på <code>default</code> (mislighold) er det lurt å regne ut hva effekt en økning på 1 $ i <code>balance</code> har på oddsen for <code>default</code> (Se forelesning):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model1))</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)      balance 
2.205746e-05 1.005567e+00 </code></pre>
</div>
</div>
<p>Vi ser at oddsen for <code>default</code> øker med en faktor 1.0056 (en 0.56 % økning) dersom <code>balance</code> øker med 1 $.</p>
<p>Si at du ønsker å predikere sannsynligheten for hvorvidt to kunder med henholdsvis 1000 $ og 2000 $ i <code>balance</code> vil misligholde sitt lån. Da kan vi bruke <code>predict</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> på følgende måte:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>to_personer <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">balance =</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>))</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> to_personer, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>pred</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1           2 
0.005648303 0.593966756 </code></pre>
</div>
</div>
<p>Det første argumentet i funksjonen <code>predict</code> er hvilken modell vi skal bruke i prediksjonen (<code>model1</code>). Det andre argumentet <code>newdata</code> er hvilke kunder vi ønsker å predikere misligholdsannsynligheter for. Vi setter dette argumentet til <code>data.frame</code>’n vi har kalt <code>to_personer</code> hvor hver rad svarer til en kunde med et sett forklaringsvariabler (i dette tilfellet to kunder og derfor to rader). Det er viktig at den inneholder en (eller flere) kolonne(r) med kolonnenavn som svarer til navnet til forklaringsvariabelen(e) vi har brukt i modellen. Argumentet <code>type = "response"</code> gjør at vi får returnert sannsynligheten for mislighold og ikke bare verdien av det lineære leddet i modellen.</p>
<p>Hvis vi ut fra disse sannsynlighetene ønsker en klassifiseringsregel som klassifiserer om kunden vil misliholde eller ikke (“Yes/No”) er det naturlig å tildele kunden “Yes” hvis misligholdsannsynligheten overstiger en hvis grense og “No” hvis ikke. Det kan det tenkes at kredittgiver vil være enten konservativ (sette grensen lavt, si 0.3) eller liberal (sette grensen høyt, si 0.7), men i eksempelet under bruker vi en “nøytral” grense på 0.5:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(pred <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2 
 "No" "Yes" </code></pre>
</div>
</div>
<p>Som navnet tilsier, vurderer <code>ifelse</code> funksjonen en logisk test i første argumentet (<code>pred &gt; 0.5</code> hvor <code>pred</code> er misligholdsannsynlighetene vi predikerte) og hvis testen har verdi <code>TRUE</code> gir den ut det du skriver i det andre argumentet (<code>"Yes"</code>), og det tredje argumentet (<code>"No"</code>) ellers. Vi ser at individet med 1000 $ i gjeld blir klassifisert som “No”, mens individet med 2000 $ i gjeld blir klassifisert som “Yes”.</p>
<p><strong>Oppgave 2.5:</strong> Lag en ny modell ved navn <code>model2</code> hvor du bruker den kategoriske variabelen <code>student</code> som forklaringsvariabel.</p>
<ul>
<li>Hvilken effekt har det å være student på for oddsen for mislighold?</li>
<li>Prediker sannsynligheten for at en student og en ikke-student misligholder gjelden sin.</li>
</ul>
<p><strong>Oppgave 2.6:</strong> Lag en tredje model ved navn <code>model3</code> hvor du bruker alle forklaringsvariablene.</p>
<ul>
<li>Hvilken effekt har det å være student på for oddsen for mislighold nå? Sammenlign med forrige oppgave.</li>
<li>Undersøk visuelt om det er en sammenheng mellom <code>student</code> og <code>balance</code> med å lage et boxplot over <code>balance</code> for studenter og et for ikke-studenter (hint: se Oppgave 2.2).</li>
<li>Prediker sannsynligheten for mislighold for en ikke-student og en student med lik <code>balance</code> og <code>income</code> på henholdsvis 1500 $ og 10000 $. Sammenlign med prediksjonen du gjorde i Oppgav 2.4. Basert på <code>model2</code> og <code>model3</code>, hvordan skal kredittgiver forholde seg til en student versus en ikke-student dersom a) Ingen informasjon om <code>balance</code> eller <code>income</code> er oppgitt og b) dersom en vet <code>balance</code> og <code>income</code>?</li>
</ul>
<p><strong>Oppgave 2.7:</strong> I denne oppgaven skal vi trene opp en knn (k-nærmeste-naboer) modell til å gjøre en tilsvarende klassifisering som den logistiske regresjonsmodellen gjorde over. Funksjonen <code>train</code> som vi trenger er inneholdt i pakken <code>caret</code> (som må installeres ved hjelp av <code>install.packages("caret")</code>). Vi velger å tilpasse en modell hvor antall naboer “k” velges automatisk med kryssvalidering vi argumentet “`trControl”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co"># R-kode dersom vi vil velge k automatisk</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">200</span>)</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>trControl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method  =</span> <span class="st">"cv"</span>, <span class="co"># 5-fold kryssvalidering</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">number  =</span> <span class="dv">5</span>)</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Tilpasser modellen</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">train</span>(default <span class="sc">~</span> balance <span class="sc">+</span> income <span class="sc">+</span> student,</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> train,</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">trControl  =</span> trControl,</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">metric     =</span> <span class="st">"Accuracy"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vi kan sjekke hvilken k som ble valgt på følgende måte (siden kryssvalidering bruker tilfeldige trekninger kan resultatet bli noe foreskjellig fra gang til gang, selv om datasettet er det samme):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hvilken k valgte kryssvalideringen?</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> model4<span class="sc">$</span>finalModel<span class="sc">$</span>k</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>k</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>Som for de andre modellene bruker vi funksjonen <code>predict</code> når vi skal predikere og syntaksen er helt lik:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>to_kunder <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">balance =</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>), <span class="at">income =</span> <span class="dv">10000</span>, <span class="at">student =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model4, <span class="at">newdata =</span> to_kunder)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] No  Yes
Levels: No Yes</code></pre>
</div>
</div>
<p>Merk at i motsetning til de logistiske regresjonsmodellene som predikerte sannsynligheter klassifiserer knn modellen kundene direkte som “Yes”/“No”.</p>
<p><strong>Oppgave 2.8:</strong> Vi ønsker å vurdere hvilken av <code>model3</code> (logistisk regresjon) og <code>model4</code> (knn) som er best. Vi kan da sjekke hvor godt de klarer å klassifisere testsettet vårt hvor vi vet hvem som har misligholdt lånene sine. Vi starter med å hente ut de sanne verdiene av <code>default</code> i treningssettet:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>sann <span class="ot">&lt;-</span> test<span class="sc">$</span>default  <span class="co"># Den sanne verdien av default i testdataene</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Disse skal vi så sammenligne med hvordan modellene klassifiserer de samme kundene basert på de andre variablene. Vi gjør først klassifiseringen med den logistiske regresjonsmodellen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>pred_logreg <span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>) <span class="co"># Predikert sannsynlighet</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>klass_logreg <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_logreg <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)            <span class="co"># Klassifisering av kundene</span></span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En oversikt over hvor mange riktige/feil klassifiseringer modellen gjør kan lett oppsummeres med en kontigenstabell. For å lage en kontigenstabell i R bruker vi funksjonen <code>table</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>logreg_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(sann, klass_logreg) <span class="co"># Kontigenstabell</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>logreg_tab</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     klass_logreg
sann    No  Yes
  No  2889   11
  Yes   70   30</code></pre>
</div>
</div>
<p>Her kan vi f.eks se at 2889 kunder blir riktig klassifisert som “No”, dvs at de ikke misligholdt lånet og modellen spår at de ikke vil misligholde lånet. Merk at diagonalen (2889 og 30) representerer korrekte klassifiseringer, mens av-diagonal (11 og 70) representer feil klassifiseringer.</p>
<p>Det kan være en fordel å dele kontigenstabellen over med totalt antall kunder for å få andelel i stedet. Funksjonen <code>prop.table</code> gjør nettopp dette:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>logreg_tab_norm <span class="ot">&lt;-</span> logreg_tab <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  prop.table <span class="sc">%&gt;%</span>  <span class="co"># normaliser</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)        <span class="co"># rund av til 3 desimaler</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>logreg_tab_norm</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     klass_logreg
sann     No   Yes
  No  0.963 0.004
  Yes 0.023 0.010</code></pre>
</div>
</div>
<p>Summen av diagonalen på denne tabellen (0.963 og 0.01) gir da totalt andel korrekt klassifiseringer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>logreg_tot <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(logreg_tab_norm))               <span class="co"># Total andel korrekt klassfisering</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>logreg_tot</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.973</code></pre>
</div>
</div>
<p><strong>Oppgave 2.9:</strong> Gjør en tilsvarende klassifisering av kundene i testsettet med knn modellen <code>model4</code> og sammenlign med resultatet over. Hvilken modell foretrekker du? Hvilke egenskaper ved klassifisering tror du kredittgiver vektlegger?</p>
<hr>
</section>
<section id="oppgave-3-paneldata-iskaffe-og-varme-dager" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="oppgave-3-paneldata-iskaffe-og-varme-dager"><span class="header-section-number">7.5.3</span> Oppgave 3 – Paneldata: Iskaffe og varme dager</h3>
<p>I denne oppgaven skal vi jobbe med et simulert paneldatasett. En kaffebarkjede har data fra 150 kaffebarer, observert månedlig over tre år (januar 2021 – desember 2023). For hver kaffebar og måned har vi informasjon om antall iskaffe solgt (<code>iskaffe_salg</code>) og antall dager den måneden med temperatur over 20°C (<code>varme_dager</code>). Kjeden ønsker å vite: Hvor mange ekstra iskaffe selger en typisk bar per ekstra varm dag?</p>
<p>Datasettet er simulert med en <em>kjent, sann effekt</em> – men denne røper vi ikke ennå. Last ned datasettet:</p>
<p><a href="datasett/kaffebar_panel.csv">kaffebar_panel.csv</a></p>
<p><strong>Oppgave 3.1</strong></p>
<p>Les inn datasettet og gjør deg kjent med strukturen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>kaffebar <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"kaffebar_panel.csv"</span>)</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kaffebar)</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(kaffebar)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Hvor mange kaffebarer er det i datasettet?</li>
<li>Hvor mange måneder er det observasjoner for?</li>
<li>Er panelet balansert (like mange observasjoner per bar)? Bruk gjerne <code>count()</code> og <code>summarise()</code> til å sjekke dette.</li>
</ul>
<p><strong>Oppgave 3.2</strong></p>
<p>Vi skal nå utforske datasettet visuelt. Begynn med å beregne gjennomsnittlig iskaffe-salg per måned (over alle barer), og lag et linjeplott:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="co"># beregne gjennomsnitt per måned</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>gj_snitt <span class="ot">&lt;-</span> kaffebar <span class="sc">%&gt;%</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(maaned_nr) <span class="sc">%&gt;%</span></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">snitt_salg =</span> <span class="fu">mean</span>(iskaffe_salg))</span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gj_snitt, <span class="fu">aes</span>(<span class="at">x =</span> maaned_nr, <span class="at">y =</span> snitt_salg)) <span class="sc">+</span></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">13</span>, <span class="dv">19</span>, <span class="dv">25</span>, <span class="dv">31</span>),</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Jan 2021"</span>, <span class="st">"Juli 2021"</span>, <span class="st">"Jan 2022"</span>, <span class="st">"Juli 2022"</span>, <span class="st">"Jan 2023"</span>, <span class="st">"Juli 2023"</span>)</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maaned"</span>, <span class="at">y =</span> <span class="st">"Gjennomsnittlig iskaffe-salg"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Beskriv hva du ser. Er mønsteret som forventet?</p>
<p>Lag deretter et plott der du velger ut 5 tilfeldige kaffebarer og fargelegger etter <code>kaffebar_id</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>utvalgte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">unique</span>(kaffebar<span class="sc">$</span>kaffebar_id), <span class="dv">5</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>kaffebar_utvalg <span class="ot">&lt;-</span> kaffebar <span class="sc">%&gt;%</span> <span class="fu">filter</span>(kaffebar_id <span class="sc">%in%</span> utvalgte)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kaffebar_utvalg, <span class="fu">aes</span>(<span class="at">x =</span> maaned_nr, <span class="at">y =</span> iskaffe_salg, <span class="at">color =</span> <span class="fu">factor</span>(kaffebar_id))) <span class="sc">+</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">7</span>, <span class="dv">13</span>, <span class="dv">19</span>, <span class="dv">25</span>, <span class="dv">31</span>),</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Jan 2021"</span>, <span class="st">"Juli 2021"</span>, <span class="st">"Jan 2022"</span>, <span class="st">"Juli 2022"</span>, <span class="st">"Jan 2023"</span>, <span class="st">"Juli 2023"</span>)</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maaned"</span>, <span class="at">y =</span> <span class="st">"Iskaffe solgt"</span>, <span class="at">color =</span> <span class="st">"Kaffebar"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Hva legger du merke til? Følger barene det samme mønsteret? Ligger de på samme nivå?</p>
<p><strong>Oppgave 3.3</strong></p>
<p>Estimer en enkel regresjonsmodell (pooled OLS, dvs. uten faste effekter) der <code>iskaffe_salg</code> er utfallsvariabel og <code>varme_dager</code> er forklaringsvariabel. Vi bruker <code>feols</code> fra <code>fixest</code>-pakken fordi vi skal bygge videre med faste effekter i neste deloppgave:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">feols</span>(iskaffe_salg <span class="sc">~</span> varme_dager, <span class="at">data =</span> kaffebar)</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pooled)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Tolk koeffisienten på <code>varme_dager</code>.</li>
<li>Tenk tilbake på plottene du laget i 3.2. Kan du se noen grunn til at denne koeffisienten over- eller underestimerer den faktiske effekten av varme dager?</li>
</ul>
<p><strong>Oppgave 3.4</strong></p>
<p>Estimer nå modellen med faste effekter for kaffebar:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>fe <span class="ot">&lt;-</span> <span class="fu">feols</span>(iskaffe_salg <span class="sc">~</span> varme_dager <span class="sc">|</span> kaffebar_id, <span class="at">data =</span> kaffebar)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(pooled, fe)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Hva har skjedd med koeffisienten?</li>
<li>Hva kontrollerer kaffebar-faste effekter for? Tenk på hva du så i plottet med de 5 utvalgte barene.</li>
<li>Hvorfor endrer estimatet seg?</li>
</ul>
<p><strong>Oppgave 3.5</strong></p>
<p>Legg til tidsfaste effekter (for <code>maaned_nr</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>fe_tw <span class="ot">&lt;-</span> <span class="fu">feols</span>(iskaffe_salg <span class="sc">~</span> varme_dager <span class="sc">|</span> kaffebar_id <span class="sc">+</span> maaned_nr, <span class="at">data =</span> kaffebar)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(pooled, fe, fe_tw)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Sammenlign koeffisientene fra de tre modellene.</li>
<li>Hva kan tidsfaste effekter fange opp i denne sammenhengen? Tenk på sesongmønsteret du så i oppgave 3.2.</li>
</ul>
<p><strong>Oppgave 3.6</strong></p>
<p>Datasettet er simulert med en sann effekt lik <span class="math inline">\(\beta_1 = 5\)</span>: Hver ekstra varm dag gir i gjennomsnitt 5 ekstra iskaffe solgt.</p>
<p>Sammenlign denne sanne verdien med estimatene fra de tre modellene. Hvilken modell kom nærmest, og hvorfor bommer de andre?</p>
</section>
<section id="oppgave-4-kausal-identifikasjon-ølskatt-og-trafikkdødsfall" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="oppgave-4-kausal-identifikasjon-ølskatt-og-trafikkdødsfall"><span class="header-section-number">7.5.4</span> Oppgave 4 – Kausal identifikasjon: Ølskatt og trafikkdødsfall</h3>
<p>I denne oppgaven bruker vi et ekte datasett med årlige observasjoner for 48 amerikanske delstater fra 1982 til 1988. Datasettet inneholder blant annet informasjon om ølskatt og trafikkdødsfall, og vi ønsker å undersøke sammenhengen mellom disse.</p>
<p><strong>Oppgave 4.1</strong></p>
<p>Installer (om nødvendig) og last inn pakken <code>AER</code>, og last inn datasettet <code>Fatalities</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Fatalities"</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Utforsk datasettet med <code>head()</code>, <code>dim()</code> og <code>str()</code>.</p>
<ul>
<li>Hvor mange observasjoner er det?</li>
<li>Identifiser variablene <code>state</code> og <code>year</code> som definerer panelstrukturen. Hvor mange delstater og år er det?</li>
<li>Er panelet balansert?</li>
</ul>
<p>Vi skal jobbe med dødsraten per innbygger, ikke det absolutte antallet dødsfall. Variablene <code>fatal</code> (antall trafikkdødsfall) og <code>pop</code> (befolkning) finnes i datasettet. Lag en ny variabel <code>frate</code> som måler antall trafikkdødsfall per 10 000 innbyggere:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>Fatalities <span class="ot">&lt;-</span> Fatalities <span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">frate =</span> fatal <span class="sc">/</span> pop <span class="sc">*</span> <span class="dv">10000</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Oppgave 4.2</strong></p>
<p>Lag et spredningsplott med <code>beertax</code> (ølskatt i dollar per kasse) på x-aksen og <code>frate</code> (dødsrate) på y-aksen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Fatalities, <span class="fu">aes</span>(<span class="at">x =</span> beertax, <span class="at">y =</span> frate)) <span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Olskatt (dollar per kasse)"</span>, <span class="at">y =</span> <span class="st">"Trafikkdodsfall per 10 000 innb."</span>)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Hva slags sammenheng ser du? Stemmer dette med hva du ville forventet?</p>
<p><strong>Oppgave 4.3</strong></p>
<p>Estimer en pooled OLS-regresjon:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">feols</span>(frate <span class="sc">~</span> beertax, <span class="at">data =</span> Fatalities)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pooled)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Tolk koeffisienten. Hva sier den om sammenhengen mellom ølskatt og trafikkdødsfall?</li>
<li>Gir fortegnet mening? Hva kan forklare resultatet?</li>
</ul>
<p><strong>Oppgave 4.4</strong></p>
<p>Estimer modellen med faste effekter for delstat:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>fe_state <span class="ot">&lt;-</span> <span class="fu">feols</span>(frate <span class="sc">~</span> beertax <span class="sc">|</span> state, <span class="at">data =</span> Fatalities)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(pooled, fe_state)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Hva har skjedd med fortegnet på koeffisienten?</li>
<li>Forklar hva delstatsfaste effekter kontrollerer for. Hva slags forskjeller mellom stater kan ha drevet det positive estimatet i pooled OLS?</li>
<li>Hva er forskjellen på å sammenligne stater <em>med hverandre</em> (pooled OLS) og å se på endringer <em>innad i</em> samme stat over tid (faste effekter)?</li>
</ul>
<p><strong>Oppgave 4.5</strong></p>
<p>Legg til tidsfaste effekter:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>fe_tw <span class="ot">&lt;-</span> <span class="fu">feols</span>(frate <span class="sc">~</span> beertax <span class="sc">|</span> state <span class="sc">+</span> year, <span class="at">data =</span> Fatalities)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(pooled, fe_state, fe_tw)</span></code></pre></div><button title="Kopier til utklipstavle" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Sammenlign de tre modellene.</li>
<li>Hva kan tidsfaste effekter fange opp her? Tenk på nasjonale trender i perioden 1982–1988.</li>
</ul>
<p><strong>Oppgave 4.6</strong></p>
<p>Refleksjonsoppgave: Er det rimelig å tolke koeffisienten fra modellen med toveis faste effekter som den <em>kausale</em> effekten av ølskatt på trafikkdødsfall? Hva kan eventuelt gjenstå i restleddet som truer en slik tolkning?</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>David W. Roubik: <em>The value of bees to the coffee harvest</em>. Nature (2002)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Funksjonen <code>predict</code> er satt opp med litt forskjellige argumenter alt ettersom hvilken type modell vi bruker. Du kan lese dokumentasjonen <code>?predict.glm</code> for å se hvordan den er satt opp for <code>glm</code> objekter<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-avansert-regresjon-og-maskinlaering.html" class="pagination-link" aria-label="Avansert regresjon og maskinlæring">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Avansert regresjon og maskinlæring</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-seminaroppgaver.html" class="pagination-link" aria-label="Seminaroppgaver">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Seminaroppgaver</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>MET4 – Empiriske Metoder, NHH</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">
<p>Håkon Otneim</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">
<p>Geir Drage Berentsen</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>