<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.2 Inferens om en populasjon | MET4 - Empiriske Metoder - høst 2026</title>
  <meta name="description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="3.2 Inferens om en populasjon | MET4 - Empiriske Metoder - høst 2026" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.2 Inferens om en populasjon | MET4 - Empiriske Metoder - høst 2026" />
  
  <meta name="twitter:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

<meta name="author" content="Geir Drage Berentsen, Håkon Otneim og Maren Holthe Hedne" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="generelt-om-hypotesetesting.html"/>
<link rel="next" href="inferens-om-to-populasjoner.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<link rel="apple-touch-icon" sizes="180x180" href="/met4/icon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/met4/icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/met4/icon/favicon-16x16.png">
<link rel="manifest" href="/met4/icon/site.webmanifest">
<link rel="mask-icon" href="/met4/icon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/met4/icon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/met4/icon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://www.nhh.no/"><img src="bilder/nhh.png" width="240"></a>
<li><a href="./index.html">MET4 - EMPIRISKE METODER</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Innledning</a></li>
<li class="chapter" data-level="1" data-path="introduksjon-til-r.html"><a href="introduksjon-til-r.html"><i class="fa fa-check"></i><b>1</b> Introduksjon til R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="en-gjennomgang-av-rstudio.html"><a href="en-gjennomgang-av-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> En gjennomgang av RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="enkle-beregninger-og-variabler.html"><a href="enkle-beregninger-og-variabler.html"><i class="fa fa-check"></i><b>1.2</b> Enkle beregninger og variabler</a></li>
<li class="chapter" data-level="1.3" data-path="vektorer.html"><a href="vektorer.html"><i class="fa fa-check"></i><b>1.3</b> Vektorer</a></li>
<li class="chapter" data-level="1.4" data-path="pakker.html"><a href="pakker.html"><i class="fa fa-check"></i><b>1.4</b> Pakker</a></li>
<li class="chapter" data-level="1.5" data-path="mappesti.html"><a href="mappesti.html"><i class="fa fa-check"></i><b>1.5</b> Mappesti</a></li>
<li class="chapter" data-level="1.6" data-path="innlesing-av-data.html"><a href="innlesing-av-data.html"><i class="fa fa-check"></i><b>1.6</b> Innlesing av data</a></li>
<li class="chapter" data-level="1.7" data-path="statistiske-analyser.html"><a href="statistiske-analyser.html"><i class="fa fa-check"></i><b>1.7</b> Statistiske analyser</a></li>
<li class="chapter" data-level="1.8" data-path="r-plotting.html"><a href="r-plotting.html"><i class="fa fa-check"></i><b>1.8</b> Plotting</a></li>
<li class="chapter" data-level="1.9" data-path="script.html"><a href="script.html"><i class="fa fa-check"></i><b>1.9</b> Script</a></li>
<li class="chapter" data-level="1.10" data-path="pipe.html"><a href="pipe.html"><i class="fa fa-check"></i><b>1.10</b> Pipe-operatoren <code>%&gt;%</code> og enkel datavask</a></li>
<li class="chapter" data-level="1.11" data-path="ki-og-programmering.html"><a href="ki-og-programmering.html"><i class="fa fa-check"></i><b>1.11</b> KI og programmering</a></li>
<li class="chapter" data-level="1.12" data-path="r-ekstra.html"><a href="r-ekstra.html"><i class="fa fa-check"></i><b>1.12</b> Oppgaver</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="grunnleggende-statistikk.html"><a href="grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>2</b> Grunnleggende statistikk</a>
<ul>
<li class="chapter" data-level="2.1" data-path="deskriptiv-statistikk.html"><a href="deskriptiv-statistikk.html"><i class="fa fa-check"></i><b>2.1</b> Deskriptiv statistikk</a></li>
<li class="chapter" data-level="2.2" data-path="utvalg-og-estimering.html"><a href="utvalg-og-estimering.html"><i class="fa fa-check"></i><b>2.2</b> Utvalg og estimering</a></li>
<li class="chapter" data-level="2.3" data-path="oppgaverdeskriptiv.html"><a href="oppgaverdeskriptiv.html"><i class="fa fa-check"></i><b>2.3</b> Oppgaver</a></li>
<li class="chapter" data-level="2.4" data-path="relevant-r-grunnleggende.html"><a href="relevant-r-grunnleggende.html"><i class="fa fa-check"></i><b>2.4</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hypotesetesting.html"><a href="hypotesetesting.html"><i class="fa fa-check"></i><b>3</b> Hypotesetesting</a>
<ul>
<li class="chapter" data-level="3.1" data-path="generelt-om-hypotesetesting.html"><a href="generelt-om-hypotesetesting.html"><i class="fa fa-check"></i><b>3.1</b> Generelt om hypotesetesting</a></li>
<li class="chapter" data-level="3.2" data-path="enpop.html"><a href="enpop.html"><i class="fa fa-check"></i><b>3.2</b> Inferens om en populasjon</a></li>
<li class="chapter" data-level="3.3" data-path="inferens-om-to-populasjoner.html"><a href="inferens-om-to-populasjoner.html"><i class="fa fa-check"></i><b>3.3</b> Inferens om to populasjoner</a></li>
<li class="chapter" data-level="3.4" data-path="kjikvadrattester.html"><a href="kjikvadrattester.html"><i class="fa fa-check"></i><b>3.4</b> Kjikvadrattester</a></li>
<li class="chapter" data-level="3.5" data-path="oppgaver.html"><a href="oppgaver.html"><i class="fa fa-check"></i><b>3.5</b> Oppgaver</a></li>
<li class="chapter" data-level="3.6" data-path="relevante-r-testing.html"><a href="relevante-r-testing.html"><i class="fa fa-check"></i><b>3.6</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regresjon.html"><a href="regresjon.html"><i class="fa fa-check"></i><b>4</b> Regresjon</a>
<ul>
<li class="chapter" data-level="4.1" data-path="enkel-regresjon.html"><a href="enkel-regresjon.html"><i class="fa fa-check"></i><b>4.1</b> Enkel regresjon</a></li>
<li class="chapter" data-level="4.2" data-path="multippel-regresjon.html"><a href="multippel-regresjon.html"><i class="fa fa-check"></i><b>4.2</b> Multippel regresjon</a></li>
<li class="chapter" data-level="4.3" data-path="modellbygging.html"><a href="modellbygging.html"><i class="fa fa-check"></i><b>4.3</b> Modellbygging</a></li>
<li class="chapter" data-level="4.4" data-path="oppgaver-1.html"><a href="oppgaver-1.html"><i class="fa fa-check"></i><b>4.4</b> Oppgaver</a></li>
<li class="chapter" data-level="4.5" data-path="relevante-r-regresjon.html"><a href="relevante-r-regresjon.html"><i class="fa fa-check"></i><b>4.5</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tidsrekker.html"><a href="tidsrekker.html"><i class="fa fa-check"></i><b>5</b> Tidsrekker</a>
<ul>
<li class="chapter" data-level="5.1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>5.1</b> Introduksjon til tidsrekker</a></li>
<li class="chapter" data-level="5.2" data-path="trend-og-sesong.html"><a href="trend-og-sesong.html"><i class="fa fa-check"></i><b>5.2</b> Trend og sesong</a></li>
<li class="chapter" data-level="5.3" data-path="ar.html"><a href="ar.html"><i class="fa fa-check"></i><b>5.3</b> AR(p)</a></li>
<li class="chapter" data-level="5.4" data-path="stasjonaritet.html"><a href="stasjonaritet.html"><i class="fa fa-check"></i><b>5.4</b> Stasjonaritet</a></li>
<li class="chapter" data-level="5.5" data-path="autokorrelasjon.html"><a href="autokorrelasjon.html"><i class="fa fa-check"></i><b>5.5</b> Autokorrelasjon</a></li>
<li class="chapter" data-level="5.6" data-path="ma.html"><a href="ma.html"><i class="fa fa-check"></i><b>5.6</b> MA(q)</a></li>
<li class="chapter" data-level="5.7" data-path="arma-arima.html"><a href="arma-arima.html"><i class="fa fa-check"></i><b>5.7</b> ARMA og ARIMA</a></li>
<li class="chapter" data-level="5.8" data-path="modellbygging-1.html"><a href="modellbygging-1.html"><i class="fa fa-check"></i><b>5.8</b> Modellbygging</a></li>
<li class="chapter" data-level="5.9" data-path="oppgaver-2.html"><a href="oppgaver-2.html"><i class="fa fa-check"></i><b>5.9</b> Oppgaver</a></li>
<li class="chapter" data-level="5.10" data-path="relevante-r-tidsrekker.html"><a href="relevante-r-tidsrekker.html"><i class="fa fa-check"></i><b>5.10</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="avansert-regresjon-og-maskinlring.html"><a href="avansert-regresjon-og-maskinlring.html"><i class="fa fa-check"></i><b>6</b> Avansert regresjon og maskinlæring</a>
<ul>
<li class="chapter" data-level="6.1" data-path="logistisk-regresjon.html"><a href="logistisk-regresjon.html"><i class="fa fa-check"></i><b>6.1</b> Logistisk regresjon</a></li>
<li class="chapter" data-level="6.2" data-path="introduksjon-til-maskinlring-med-knn.html"><a href="introduksjon-til-maskinlring-med-knn.html"><i class="fa fa-check"></i><b>6.2</b> Introduksjon til maskinlæring med kNN</a></li>
<li class="chapter" data-level="6.3" data-path="paneldata.html"><a href="paneldata.html"><i class="fa fa-check"></i><b>6.3</b> Paneldata</a></li>
<li class="chapter" data-level="6.4" data-path="identifikasjon-og-kausalitet.html"><a href="identifikasjon-og-kausalitet.html"><i class="fa fa-check"></i><b>6.4</b> Identifikasjon og kausalitet</a></li>
<li class="chapter" data-level="6.5" data-path="oppgaver-3.html"><a href="oppgaver-3.html"><i class="fa fa-check"></i><b>6.5</b> Oppgaver</a></li>
<li class="chapter" data-level="6.6" data-path="relevante-r-avansert-regresjon.html"><a href="relevante-r-avansert-regresjon.html"><i class="fa fa-check"></i><b>6.6</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datavinger.html"><a href="datavinger.html"><i class="fa fa-check"></i><b>7</b> Dataøvinger</a>
<ul>
<li class="chapter" data-level="7.1" data-path="dataving-1---grunnleggende-statistikk.html"><a href="dataving-1---grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>7.1</b> Dataøving 1 - Grunnleggende statistikk</a></li>
<li class="chapter" data-level="7.2" data-path="dataving-2.html"><a href="dataving-2.html"><i class="fa fa-check"></i><b>7.2</b> Dataøving 2</a></li>
<li class="chapter" data-level="7.3" data-path="dataving-3.html"><a href="dataving-3.html"><i class="fa fa-check"></i><b>7.3</b> Dataøving 3</a></li>
<li class="chapter" data-level="7.4" data-path="dataving-4.html"><a href="dataving-4.html"><i class="fa fa-check"></i><b>7.4</b> Dataøving 4</a></li>
<li class="chapter" data-level="7.5" data-path="dataving-5.html"><a href="dataving-5.html"><i class="fa fa-check"></i><b>7.5</b> Dataøving 5</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="seminar.html"><a href="seminar.html"><i class="fa fa-check"></i><b>8</b> Seminaroppgaver</a>
<ul>
<li class="chapter" data-level="8.1" data-path="seminar-1---grunnleggende-statistikk.html"><a href="seminar-1---grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>8.1</b> Seminar 1 - Grunnleggende statistikk</a></li>
<li class="chapter" data-level="8.2" data-path="seminar-2---hypotesetesting.html"><a href="seminar-2---hypotesetesting.html"><i class="fa fa-check"></i><b>8.2</b> Seminar 2 - Hypotesetesting</a></li>
<li class="chapter" data-level="8.3" data-path="seminar-3---regresjon-i.html"><a href="seminar-3---regresjon-i.html"><i class="fa fa-check"></i><b>8.3</b> Seminar 3 - Regresjon I</a></li>
<li class="chapter" data-level="8.4" data-path="seminar-4---regresjon-ii.html"><a href="seminar-4---regresjon-ii.html"><i class="fa fa-check"></i><b>8.4</b> Seminar 4 - Regresjon II</a></li>
<li class="chapter" data-level="8.5" data-path="seminar-5---tidsrekker.html"><a href="seminar-5---tidsrekker.html"><i class="fa fa-check"></i><b>8.5</b> Seminar 5 - Tidsrekker</a></li>
<li class="chapter" data-level="8.6" data-path="seminar-6---avansert-regresjon-og-maskinlring.html"><a href="seminar-6---avansert-regresjon-og-maskinlring.html"><i class="fa fa-check"></i><b>8.6</b> Seminar 6 - Avansert regresjon og maskinlæring</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="eksamensoppgaver.html"><a href="eksamensoppgaver.html"><i class="fa fa-check"></i><b>9</b> Eksamensoppgaver</a>
<ul>
<li class="chapter" data-level="9.1" data-path="skoleeksamen.html"><a href="skoleeksamen.html"><i class="fa fa-check"></i><b>9.1</b> Tidligere skoleeksamener</a></li>
<li class="chapter" data-level="9.2" data-path="tidligere-hjemmeeksamen.html"><a href="tidligere-hjemmeeksamen.html"><i class="fa fa-check"></i><b>9.2</b> Tidligere hjemmeeksamen</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">Håkon Otneim</a></li>
<li><a href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">Geir Drage Berentsen</a></li>
<li><a href="https://github.com/rstudio/bookdown">Publisert ved hjelp av bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MET4 - Empiriske Metoder - høst 2026</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="enpop" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Inferens om en populasjon<a href="enpop.html#enpop" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="videoforelesninger-3" class="section level3 unnumbered hasAnchor">
<h3>Videoforelesninger<a href="enpop.html#videoforelesninger-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div style="padding:74.93% 0 0 0;position:relative;">
<iframe src="https://vimeo.com/showcase/7780035/embed" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;">
</iframe>
</div>
</div>
<div id="hvilke-strrelser-kan-vi-teste" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Hvilke størrelser kan vi teste?<a href="enpop.html#hvilke-strrelser-kan-vi-teste" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Å gjøre inferens om <em>én</em> populasjon vil si å teste en hypotese om en enkelt ukjent parameter i populasjonen. Framgangsmåten er alltid den samme femstegsoppskriften fra forrige delkapittel; det som skifter fra test til test, er <em>hvilken</em> testobservator vi bruker, og <em>hvilken fordeling</em> den har under <span class="math inline">\(H_0\)</span>. De tre størrelsene vi oftest tester, er:</p>
<ul>
<li><strong>forventningen</strong> <span class="math inline">\(\mu\)</span> (populasjonsgjennomsnittet),</li>
<li>en <strong>andel</strong> <span class="math inline">\(p\)</span>, og</li>
<li><strong>standardavviket</strong> <span class="math inline">\(\sigma\)</span> (eller variansen <span class="math inline">\(\sigma^2\)</span>), altså spredningen.</li>
</ul>
<p>Vi går gjennom de tre i tur og orden. For hver av dem viser vi først hvordan testen gjøres <em>manuelt</em>, steg for steg med en kritisk verdi, og deretter hvordan R kan utføre hele testen direkte fra dataene.</p>
</div>
<div id="inferens-om-et-gjennomsnitt" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Inferens om et gjennomsnitt<a href="enpop.html#inferens-om-et-gjennomsnitt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vi vil teste om populasjonsgjennomsnittet er lik en bestemt verdi, altså <span class="math inline">\(H_0: \mu = \mu_0\)</span>. Fra samplingfordelingen til et gjennomsnitt (modul 2) vet vi at <span class="math inline">\(\overline{X}\)</span> har forventning <span class="math inline">\(\mu\)</span> og standardavvik <span class="math inline">\(\sigma/\sqrt{n}\)</span>. Dersom vi <em>kjente</em> <span class="math inline">\(\sigma\)</span>, kunne vi brukt testobservatoren</p>
<p><span class="math display">\[Z = \frac{\overline{X} - \mu_0}{\sigma/\sqrt{n}},\]</span></p>
<p>som er standardnormalfordelt når <span class="math inline">\(H_0\)</span> er sann. I praksis kjenner vi sjelden det sanne standardavviket, så vi må estimere det med utvalgsstandardavviket <span class="math inline">\(s\)</span>. Denne ekstra usikkerheten gjør at testobservatoren</p>
<p><span class="math display">\[T = \frac{\overline{X} - \mu_0}{s/\sqrt{n}}\]</span></p>
<p>ikke lenger er normalfordelt, men <strong>t-fordelt med <span class="math inline">\(n-1\)</span> frihetsgrader</strong>. Testobservatoren måler hvor mange (estimerte) standardfeil utvalgsgjennomsnittet ligger unna verdien <span class="math inline">\(\mu_0\)</span> som nullhypotesen påstår. Ligger den langt unna null, taler dataene mot <span class="math inline">\(H_0\)</span>. Den kritiske verdien henter vi fra t-fordelingen (<code>qt()</code> i R). Testen kalles gjerne en <strong>t-test</strong>, og den hviler på at observasjonene kommer fra en tilnærmet normalfordelt populasjon, eller at <span class="math inline">\(n\)</span> er stor nok til at sentralgrenseteoremet slår inn.</p>
<p><strong>Eksempel.</strong> NHHs karrieresenter oppgir at gjennomsnittlig startlønn for nyutdannede masterstudenter er 620 000 kr. En studentforening mistenker at den egentlig er høyere, og gjennomfører en spørreundersøkelse. Vi følger de fem stegene:</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er den forventede startlønnen høyere enn 620 000 kr?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: \mu = 620\,000\)</span> mot <span class="math inline">\(H_A: \mu &gt; 620\,000\)</span> (ensidig). Vi bestemmer <em>på forhånd</em>, før vi ser på dataene, at vi vil bruke et signifikansnivå på <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> Vi spør 40 tilfeldig valgte nyutdannede om startlønnen deres. Vi simulerer svarene, så du kan kjøre koden og få de samme tallene:</li>
</ol>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="enpop.html#cb46-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb46-2"><a href="enpop.html#cb46-2" tabindex="-1"></a>lonn <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean =</span> <span class="dv">636000</span>, <span class="at">sd =</span> <span class="dv">52000</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Testobservator:</strong> Vi kjenner ikke det sanne standardavviket, så vi bruker <span class="math inline">\(T = (\overline{X} - \mu_0)/(s/\sqrt{n})\)</span>, og regner den ut manuelt med R som kalkulator:</li>
</ol>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="enpop.html#cb47-1" tabindex="-1"></a>gj.snitt <span class="ot">&lt;-</span> <span class="fu">mean</span>(lonn)     <span class="co"># utvalgsgjennomsnittet</span></span>
<span id="cb47-2"><a href="enpop.html#cb47-2" tabindex="-1"></a>s        <span class="ot">&lt;-</span> <span class="fu">sd</span>(lonn)       <span class="co"># utvalgsstandardavviket</span></span>
<span id="cb47-3"><a href="enpop.html#cb47-3" tabindex="-1"></a>n        <span class="ot">&lt;-</span> <span class="fu">length</span>(lonn)   <span class="co"># antall observasjoner</span></span>
<span id="cb47-4"><a href="enpop.html#cb47-4" tabindex="-1"></a>mu0      <span class="ot">&lt;-</span> <span class="dv">620000</span>         <span class="co"># verdien fra nullhypotesen</span></span>
<span id="cb47-5"><a href="enpop.html#cb47-5" tabindex="-1"></a></span>
<span id="cb47-6"><a href="enpop.html#cb47-6" tabindex="-1"></a>T_obs <span class="ot">&lt;-</span> (gj.snitt <span class="sc">-</span> mu0)<span class="sc">/</span>(s<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb47-7"><a href="enpop.html#cb47-7" tabindex="-1"></a>T_obs</span></code></pre></div>
<pre><code>## [1] 2.306861</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> Testobservatoren er t-fordelt med <span class="math inline">\(n - 1 = 39\)</span> frihetsgrader. For en ensidig test på 5 %-nivå er den kritiske verdien 95-prosentilen <span class="math inline">\(t_{0.95,\,39}\)</span> (se avsnittet om kritiske verdier i <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="enpop.html#cb49-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 1.684875</code></pre>
<p>Testobservatoren (2.31) er større enn den kritiske verdien (1.69), så den lander i forkastningsområdet. Vi forkaster <span class="math inline">\(H_0\)</span> og konkluderer med at den forventede startlønnen er høyere enn 620 000 kr.</p>
<p>Over gjorde vi testen manuelt, steg for steg. <strong>I R</strong> kan vi i stedet la <code>t.test()</code> gjøre hele jobben direkte fra dataene:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="enpop.html#cb51-1" tabindex="-1"></a><span class="fu">t.test</span>(lonn, <span class="at">mu =</span> <span class="dv">620000</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  lonn
## t = 2.3069, df = 39, p-value = 0.01323
## alternative hypothesis: true mean is greater than 620000
## 95 percent confidence interval:
##  625682.2      Inf
## sample estimates:
## mean of x 
##  641074.7</code></pre>
<p>I utskriften er det særlig <strong>p-verdien</strong> du skal se på: er den mindre enn signifikansnivået vi valgte på forhånd (<span class="math inline">\(\alpha = 0.05\)</span>), forkaster vi <span class="math inline">\(H_0\)</span>. Her er p-verdien 0.013, altså under 0.05, så vi forkaster, akkurat som med den kritiske verdien. Utskriften gir også selve testobservatoren (<code>t</code>), antall frihetsgrader (<code>df</code>) og et konfidensintervall for den forventede startlønnen.</p>
</div>
<div id="inferens-om-en-andel" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Inferens om en andel<a href="enpop.html#inferens-om-en-andel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ofte er størrelsen vi er ute etter, en <strong>andel</strong> <span class="math inline">\(p\)</span>, for eksempel andelen kunder som misligholder et lån, eller andelen defekte enheter i en produksjon. Vi tester da <span class="math inline">\(H_0: p = p_0\)</span>. Fra samplingfordelingen til en andel (modul 2) vet vi at den observerte andelen <span class="math inline">\(\widehat{p}\)</span> er tilnærmet normalfordelt for store utvalg. Under nullhypotesen er <span class="math inline">\(p = p_0\)</span>, så testobservatoren blir</p>
<p><span class="math display">\[Z = \frac{\widehat{p} - p_0}{\sqrt{p_0(1-p_0)/n}},\]</span></p>
<p>som er tilnærmet standardnormalfordelt når <span class="math inline">\(H_0\)</span> er sann. Legg merke til at vi setter inn <span class="math inline">\(p_0\)</span> (verdien fra nullhypotesen), <em>ikke</em> <span class="math inline">\(\widehat{p}\)</span>, i nevneren: standardfeilen regnes ut under forutsetning av at <span class="math inline">\(H_0\)</span> er sann. Den kritiske verdien henter vi fra standardnormalfordelingen (<code>qnorm()</code>). Tilnærmingen er god når både <span class="math inline">\(np_0\)</span> og <span class="math inline">\(n(1-p_0)\)</span> er større enn omtrent 5.</p>
<p><strong>Eksempel.</strong> En bank hevder at høyst 5 % av forbrukslånene deres blir misligholdt. En tilsynsmyndighet vil undersøke om den sanne misligholdsandelen er høyere.</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er den sanne misligholdsandelen <span class="math inline">\(p\)</span> større enn 0.05?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: p = 0.05\)</span> mot <span class="math inline">\(H_A: p &gt; 0.05\)</span> (ensidig). Vi velger på forhånd et signifikansnivå på <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> Tilsynet trekker 400 tilfeldige lån og finner at 30 av dem er misligholdt. Den observerte andelen er <span class="math inline">\(\widehat{p} = 30/400 = 0.075\)</span>.</li>
<li><strong>Testobservator:</strong> Under <span class="math inline">\(H_0\)</span> er <span class="math inline">\(p_0 = 0.05\)</span>, så</li>
</ol>
<p><span class="math display">\[Z = \frac{\widehat{p} - p_0}{\sqrt{p_0(1-p_0)/n}} = \frac{0.075 - 0.05}{\sqrt{0.05 \cdot 0.95/400}} \approx 2.29.\]</span></p>
<p>Regnet ut manuelt i R:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="enpop.html#cb53-1" tabindex="-1"></a>p.hatt <span class="ot">&lt;-</span> <span class="dv">30</span><span class="sc">/</span><span class="dv">400</span></span>
<span id="cb53-2"><a href="enpop.html#cb53-2" tabindex="-1"></a>p0     <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb53-3"><a href="enpop.html#cb53-3" tabindex="-1"></a>n      <span class="ot">&lt;-</span> <span class="dv">400</span></span>
<span id="cb53-4"><a href="enpop.html#cb53-4" tabindex="-1"></a>(p.hatt <span class="sc">-</span> p0)<span class="sc">/</span><span class="fu">sqrt</span>(p0<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p0)<span class="sc">/</span>n)</span></code></pre></div>
<pre><code>## [1] 2.294157</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> Testobservatoren er tilnærmet standardnormalfordelt. For en ensidig test på 5 %-nivå er den kritiske verdien <span class="math inline">\(z_{0.95}\)</span> (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="enpop.html#cb55-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<p>Siden testobservatoren (2.29) er større enn den kritiske verdien (1.645), forkaster vi <span class="math inline">\(H_0\)</span>: misligholdsandelen ser ut til å være høyere enn 5 %.</p>
<p>Over gjorde vi testen manuelt. <strong>I R</strong> kan vi bruke <code>prop.test()</code> direkte, med antall misligholdte lån, antall lån, verdien under <span class="math inline">\(H_0\)</span> og retningen på testen:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="enpop.html#cb57-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">30</span>, <span class="dv">400</span>, <span class="at">p =</span> <span class="fl">0.05</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  30 out of 400, null probability 0.05
## X-squared = 5.2632, df = 1, p-value = 0.01089
## alternative hypothesis: true p is greater than 0.05
## 95 percent confidence interval:
##  0.05607821 1.00000000
## sample estimates:
##     p 
## 0.075</code></pre>
<p>Igjen er det <strong>p-verdien</strong> du skal se på. Den er 0.011, altså under <span class="math inline">\(\alpha = 0.05\)</span>, så vi forkaster <span class="math inline">\(H_0\)</span>. (<code>prop.test()</code> rapporterer en <code>X-squared</code>-verdi som rett og slett er <span class="math inline">\(Z^2\)</span>. Vi bruker <code>correct = FALSE</code> for å få nøyaktig samme test som den vi regnet ut for hånd.)</p>
</div>
<div id="inferens-om-et-standardavvik" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Inferens om et standardavvik<a href="enpop.html#inferens-om-et-standardavvik" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Noen ganger er det <em>spredningen</em> i seg selv vi vil teste, for eksempel om risikoen i en avkastningsserie er større enn en tillatt grense. Vi tester da <span class="math inline">\(H_0: \sigma = \sigma_0\)</span> (likeverdig med <span class="math inline">\(\sigma^2 = \sigma_0^2\)</span>), og bruker testobservatoren</p>
<p><span class="math display">\[\chi^2 = \frac{(n-1)s^2}{\sigma_0^2},\]</span></p>
<p>som under <span class="math inline">\(H_0\)</span> følger en <strong>kji-kvadratfordeling</strong> (<span class="math inline">\(\chi^2\)</span>-fordeling) med <span class="math inline">\(n-1\)</span> frihetsgrader. En viktig forskjell fra <span class="math inline">\(Z\)</span> og <span class="math inline">\(T\)</span> er at kji-kvadratfordelingen ikke er symmetrisk: den lever bare på positive verdier og har en lang høyre hale. Derfor er de kritiske verdiene forskjellige i øvre og nedre hale, og vi må være ekstra nøye med hvilken hale forkastningsområdet skal ligge i. Kritiske verdier henter vi fra <code>qchisq()</code>. Denne testen er følsom for brudd på antakelsen om at populasjonen er normalfordelt.</p>
<p><strong>Eksempel.</strong> Et aksjefond markedsfører seg med at risikoen, målt ved standardavviket til den månedlige avkastningen, er høyst 4 %. En analytiker vil teste om risikoen egentlig er høyere.</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er standardavviket <span class="math inline">\(\sigma\)</span> til den månedlige avkastningen større enn 4 %?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: \sigma = 4\)</span> mot <span class="math inline">\(H_A: \sigma &gt; 4\)</span> (ensidig). Vi velger på forhånd et signifikansnivå på <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> Analytikeren ser på de månedlige avkastningene (i prosent) fra de siste 30 månedene (simulert):</li>
</ol>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="enpop.html#cb59-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb59-2"><a href="enpop.html#cb59-2" tabindex="-1"></a>avkastning <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fl">0.8</span>, <span class="at">sd =</span> <span class="fl">5.6</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Testobservator:</strong> Vi bruker <span class="math inline">\(\chi^2 = (n-1)s^2/\sigma_0^2\)</span> med <span class="math inline">\(\sigma_0 = 4\)</span>, og regner den ut manuelt i R:</li>
</ol>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="enpop.html#cb60-1" tabindex="-1"></a>s      <span class="ot">&lt;-</span> <span class="fu">sd</span>(avkastning)       <span class="co"># utvalgsstandardavviket</span></span>
<span id="cb60-2"><a href="enpop.html#cb60-2" tabindex="-1"></a>n      <span class="ot">&lt;-</span> <span class="fu">length</span>(avkastning)   <span class="co"># antall observasjoner</span></span>
<span id="cb60-3"><a href="enpop.html#cb60-3" tabindex="-1"></a>sigma0 <span class="ot">&lt;-</span> <span class="dv">4</span>                    <span class="co"># standardavviket under H_0</span></span>
<span id="cb60-4"><a href="enpop.html#cb60-4" tabindex="-1"></a></span>
<span id="cb60-5"><a href="enpop.html#cb60-5" tabindex="-1"></a>chikvadrat <span class="ot">&lt;-</span> (n <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>s<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>sigma0<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb60-6"><a href="enpop.html#cb60-6" tabindex="-1"></a>chikvadrat</span></code></pre></div>
<pre><code>## [1] 48.54132</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> Testobservatoren er kji-kvadratfordelt med <span class="math inline">\(n - 1 = 29\)</span> frihetsgrader. Siden alternativet er <span class="math inline">\(\sigma &gt; 4\)</span>, ligger forkastningsområdet i <em>øvre</em> hale, og den kritiske verdien er 95-prosentilen (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="enpop.html#cb62-1" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 42.55697</code></pre>
<p>Testobservatoren (48.5) er større enn den kritiske verdien (42.6), så vi forkaster <span class="math inline">\(H_0\)</span>: risikoen ser ut til å være høyere enn de annonserte 4 %.</p>
<p><strong>I R</strong> finnes det ingen ferdig funksjon for denne testen slik som <code>t.test()</code> og <code>prop.test()</code>, så vi gjør den manuelt i R slik vi nettopp gjorde, direkte fra dataene. Vil du heller ha p-verdien enn å sammenligne med en kritisk verdi, finner du den som arealet i øvre hale med <code>pchisq()</code>:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="enpop.html#cb64-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(chikvadrat, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.01290658</code></pre>
<p>p-verdien er 0.013, altså under <span class="math inline">\(\alpha = 0.05\)</span>, så konklusjonen er den samme: vi forkaster <span class="math inline">\(H_0\)</span>.</p>
</div>
<div id="kontrollsprsmal-3" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Kontrollspørsmål<a href="enpop.html#kontrollsprsmal-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Hva tester vi i en ett-utvalgs t-test, og hvilke forutsetninger hviler den på?</li>
<li>Hvorfor bruker vi t-fordelingen og ikke normalfordelingen når vi tester et gjennomsnitt uten å kjenne <span class="math inline">\(\sigma\)</span>?</li>
<li>Hvorfor setter vi inn <span class="math inline">\(p_0\)</span> og ikke <span class="math inline">\(\widehat{p}\)</span> i nevneren til testobservatoren for en andel?</li>
<li>Hvorfor må vi være ekstra nøye med øvre og nedre kritisk verdi i en kji-kvadrattest for et standardavvik?</li>
</ol>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="generelt-om-hypotesetesting.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inferens-om-to-populasjoner.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "toc_depth": 4
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
