<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.3 Inferens om to populasjoner | MET4 - Empiriske Metoder - høst 2026</title>
  <meta name="description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="3.3 Inferens om to populasjoner | MET4 - Empiriske Metoder - høst 2026" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.3 Inferens om to populasjoner | MET4 - Empiriske Metoder - høst 2026" />
  
  <meta name="twitter:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

<meta name="author" content="Geir Drage Berentsen, Håkon Otneim og Maren Holthe Hedne" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="enpop.html"/>
<link rel="next" href="kjikvadrattester.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<link rel="apple-touch-icon" sizes="180x180" href="/met4/icon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/met4/icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/met4/icon/favicon-16x16.png">
<link rel="manifest" href="/met4/icon/site.webmanifest">
<link rel="mask-icon" href="/met4/icon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/met4/icon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/met4/icon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://www.nhh.no/"><img src="bilder/nhh.png" width="240"></a>
<li><a href="./index.html">MET4 - EMPIRISKE METODER</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Innledning</a></li>
<li class="chapter" data-level="1" data-path="introduksjon-til-r.html"><a href="introduksjon-til-r.html"><i class="fa fa-check"></i><b>1</b> Introduksjon til R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="en-gjennomgang-av-rstudio.html"><a href="en-gjennomgang-av-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> En gjennomgang av RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="enkle-beregninger-og-variabler.html"><a href="enkle-beregninger-og-variabler.html"><i class="fa fa-check"></i><b>1.2</b> Enkle beregninger og variabler</a></li>
<li class="chapter" data-level="1.3" data-path="vektorer.html"><a href="vektorer.html"><i class="fa fa-check"></i><b>1.3</b> Vektorer</a></li>
<li class="chapter" data-level="1.4" data-path="pakker.html"><a href="pakker.html"><i class="fa fa-check"></i><b>1.4</b> Pakker</a></li>
<li class="chapter" data-level="1.5" data-path="mappesti.html"><a href="mappesti.html"><i class="fa fa-check"></i><b>1.5</b> Mappesti</a></li>
<li class="chapter" data-level="1.6" data-path="innlesing-av-data.html"><a href="innlesing-av-data.html"><i class="fa fa-check"></i><b>1.6</b> Innlesing av data</a></li>
<li class="chapter" data-level="1.7" data-path="statistiske-analyser.html"><a href="statistiske-analyser.html"><i class="fa fa-check"></i><b>1.7</b> Statistiske analyser</a></li>
<li class="chapter" data-level="1.8" data-path="r-plotting.html"><a href="r-plotting.html"><i class="fa fa-check"></i><b>1.8</b> Plotting</a></li>
<li class="chapter" data-level="1.9" data-path="script.html"><a href="script.html"><i class="fa fa-check"></i><b>1.9</b> Script</a></li>
<li class="chapter" data-level="1.10" data-path="pipe.html"><a href="pipe.html"><i class="fa fa-check"></i><b>1.10</b> Pipe-operatoren <code>%&gt;%</code> og enkel datavask</a></li>
<li class="chapter" data-level="1.11" data-path="ki-og-programmering.html"><a href="ki-og-programmering.html"><i class="fa fa-check"></i><b>1.11</b> KI og programmering</a></li>
<li class="chapter" data-level="1.12" data-path="r-ekstra.html"><a href="r-ekstra.html"><i class="fa fa-check"></i><b>1.12</b> Oppgaver</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="grunnleggende-statistikk.html"><a href="grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>2</b> Grunnleggende statistikk</a>
<ul>
<li class="chapter" data-level="2.1" data-path="deskriptiv-statistikk.html"><a href="deskriptiv-statistikk.html"><i class="fa fa-check"></i><b>2.1</b> Deskriptiv statistikk</a></li>
<li class="chapter" data-level="2.2" data-path="utvalg-og-estimering.html"><a href="utvalg-og-estimering.html"><i class="fa fa-check"></i><b>2.2</b> Utvalg og estimering</a></li>
<li class="chapter" data-level="2.3" data-path="oppgaverdeskriptiv.html"><a href="oppgaverdeskriptiv.html"><i class="fa fa-check"></i><b>2.3</b> Oppgaver</a></li>
<li class="chapter" data-level="2.4" data-path="relevant-r-grunnleggende.html"><a href="relevant-r-grunnleggende.html"><i class="fa fa-check"></i><b>2.4</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hypotesetesting.html"><a href="hypotesetesting.html"><i class="fa fa-check"></i><b>3</b> Hypotesetesting</a>
<ul>
<li class="chapter" data-level="3.1" data-path="generelt-om-hypotesetesting.html"><a href="generelt-om-hypotesetesting.html"><i class="fa fa-check"></i><b>3.1</b> Generelt om hypotesetesting</a></li>
<li class="chapter" data-level="3.2" data-path="enpop.html"><a href="enpop.html"><i class="fa fa-check"></i><b>3.2</b> Inferens om en populasjon</a></li>
<li class="chapter" data-level="3.3" data-path="inferens-om-to-populasjoner.html"><a href="inferens-om-to-populasjoner.html"><i class="fa fa-check"></i><b>3.3</b> Inferens om to populasjoner</a></li>
<li class="chapter" data-level="3.4" data-path="kjikvadrattester.html"><a href="kjikvadrattester.html"><i class="fa fa-check"></i><b>3.4</b> Kjikvadrattester</a></li>
<li class="chapter" data-level="3.5" data-path="oppgaver.html"><a href="oppgaver.html"><i class="fa fa-check"></i><b>3.5</b> Oppgaver</a></li>
<li class="chapter" data-level="3.6" data-path="relevante-r-testing.html"><a href="relevante-r-testing.html"><i class="fa fa-check"></i><b>3.6</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regresjon.html"><a href="regresjon.html"><i class="fa fa-check"></i><b>4</b> Regresjon</a>
<ul>
<li class="chapter" data-level="4.1" data-path="enkel-regresjon.html"><a href="enkel-regresjon.html"><i class="fa fa-check"></i><b>4.1</b> Enkel regresjon</a></li>
<li class="chapter" data-level="4.2" data-path="multippel-regresjon.html"><a href="multippel-regresjon.html"><i class="fa fa-check"></i><b>4.2</b> Multippel regresjon</a></li>
<li class="chapter" data-level="4.3" data-path="modellbygging.html"><a href="modellbygging.html"><i class="fa fa-check"></i><b>4.3</b> Modellbygging</a></li>
<li class="chapter" data-level="4.4" data-path="oppgaver-1.html"><a href="oppgaver-1.html"><i class="fa fa-check"></i><b>4.4</b> Oppgaver</a></li>
<li class="chapter" data-level="4.5" data-path="relevante-r-regresjon.html"><a href="relevante-r-regresjon.html"><i class="fa fa-check"></i><b>4.5</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tidsrekker.html"><a href="tidsrekker.html"><i class="fa fa-check"></i><b>5</b> Tidsrekker</a>
<ul>
<li class="chapter" data-level="5.1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>5.1</b> Introduksjon til tidsrekker</a></li>
<li class="chapter" data-level="5.2" data-path="trend-og-sesong.html"><a href="trend-og-sesong.html"><i class="fa fa-check"></i><b>5.2</b> Trend og sesong</a></li>
<li class="chapter" data-level="5.3" data-path="ar.html"><a href="ar.html"><i class="fa fa-check"></i><b>5.3</b> AR(p)</a></li>
<li class="chapter" data-level="5.4" data-path="stasjonaritet.html"><a href="stasjonaritet.html"><i class="fa fa-check"></i><b>5.4</b> Stasjonaritet</a></li>
<li class="chapter" data-level="5.5" data-path="autokorrelasjon.html"><a href="autokorrelasjon.html"><i class="fa fa-check"></i><b>5.5</b> Autokorrelasjon</a></li>
<li class="chapter" data-level="5.6" data-path="ma.html"><a href="ma.html"><i class="fa fa-check"></i><b>5.6</b> MA(q)</a></li>
<li class="chapter" data-level="5.7" data-path="arma-arima.html"><a href="arma-arima.html"><i class="fa fa-check"></i><b>5.7</b> ARMA og ARIMA</a></li>
<li class="chapter" data-level="5.8" data-path="modellbygging-1.html"><a href="modellbygging-1.html"><i class="fa fa-check"></i><b>5.8</b> Modellbygging</a></li>
<li class="chapter" data-level="5.9" data-path="oppgaver-2.html"><a href="oppgaver-2.html"><i class="fa fa-check"></i><b>5.9</b> Oppgaver</a></li>
<li class="chapter" data-level="5.10" data-path="relevante-r-tidsrekker.html"><a href="relevante-r-tidsrekker.html"><i class="fa fa-check"></i><b>5.10</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="avansert-regresjon-og-maskinlring.html"><a href="avansert-regresjon-og-maskinlring.html"><i class="fa fa-check"></i><b>6</b> Avansert regresjon og maskinlæring</a>
<ul>
<li class="chapter" data-level="6.1" data-path="logistisk-regresjon.html"><a href="logistisk-regresjon.html"><i class="fa fa-check"></i><b>6.1</b> Logistisk regresjon</a></li>
<li class="chapter" data-level="6.2" data-path="introduksjon-til-maskinlring-med-knn.html"><a href="introduksjon-til-maskinlring-med-knn.html"><i class="fa fa-check"></i><b>6.2</b> Introduksjon til maskinlæring med kNN</a></li>
<li class="chapter" data-level="6.3" data-path="paneldata.html"><a href="paneldata.html"><i class="fa fa-check"></i><b>6.3</b> Paneldata</a></li>
<li class="chapter" data-level="6.4" data-path="identifikasjon-og-kausalitet.html"><a href="identifikasjon-og-kausalitet.html"><i class="fa fa-check"></i><b>6.4</b> Identifikasjon og kausalitet</a></li>
<li class="chapter" data-level="6.5" data-path="oppgaver-3.html"><a href="oppgaver-3.html"><i class="fa fa-check"></i><b>6.5</b> Oppgaver</a></li>
<li class="chapter" data-level="6.6" data-path="relevante-r-avansert-regresjon.html"><a href="relevante-r-avansert-regresjon.html"><i class="fa fa-check"></i><b>6.6</b> Relevante R-kommandoer</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datavinger.html"><a href="datavinger.html"><i class="fa fa-check"></i><b>7</b> Dataøvinger</a>
<ul>
<li class="chapter" data-level="7.1" data-path="dataving-1---grunnleggende-statistikk.html"><a href="dataving-1---grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>7.1</b> Dataøving 1 - Grunnleggende statistikk</a></li>
<li class="chapter" data-level="7.2" data-path="dataving-2.html"><a href="dataving-2.html"><i class="fa fa-check"></i><b>7.2</b> Dataøving 2</a></li>
<li class="chapter" data-level="7.3" data-path="dataving-3.html"><a href="dataving-3.html"><i class="fa fa-check"></i><b>7.3</b> Dataøving 3</a></li>
<li class="chapter" data-level="7.4" data-path="dataving-4.html"><a href="dataving-4.html"><i class="fa fa-check"></i><b>7.4</b> Dataøving 4</a></li>
<li class="chapter" data-level="7.5" data-path="dataving-5.html"><a href="dataving-5.html"><i class="fa fa-check"></i><b>7.5</b> Dataøving 5</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="seminar.html"><a href="seminar.html"><i class="fa fa-check"></i><b>8</b> Seminaroppgaver</a>
<ul>
<li class="chapter" data-level="8.1" data-path="seminar-1---grunnleggende-statistikk.html"><a href="seminar-1---grunnleggende-statistikk.html"><i class="fa fa-check"></i><b>8.1</b> Seminar 1 - Grunnleggende statistikk</a></li>
<li class="chapter" data-level="8.2" data-path="seminar-2---hypotesetesting.html"><a href="seminar-2---hypotesetesting.html"><i class="fa fa-check"></i><b>8.2</b> Seminar 2 - Hypotesetesting</a></li>
<li class="chapter" data-level="8.3" data-path="seminar-3---regresjon-i.html"><a href="seminar-3---regresjon-i.html"><i class="fa fa-check"></i><b>8.3</b> Seminar 3 - Regresjon I</a></li>
<li class="chapter" data-level="8.4" data-path="seminar-4---regresjon-ii.html"><a href="seminar-4---regresjon-ii.html"><i class="fa fa-check"></i><b>8.4</b> Seminar 4 - Regresjon II</a></li>
<li class="chapter" data-level="8.5" data-path="seminar-5---tidsrekker.html"><a href="seminar-5---tidsrekker.html"><i class="fa fa-check"></i><b>8.5</b> Seminar 5 - Tidsrekker</a></li>
<li class="chapter" data-level="8.6" data-path="seminar-6---avansert-regresjon-og-maskinlring.html"><a href="seminar-6---avansert-regresjon-og-maskinlring.html"><i class="fa fa-check"></i><b>8.6</b> Seminar 6 - Avansert regresjon og maskinlæring</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="eksamensoppgaver.html"><a href="eksamensoppgaver.html"><i class="fa fa-check"></i><b>9</b> Eksamensoppgaver</a>
<ul>
<li class="chapter" data-level="9.1" data-path="skoleeksamen.html"><a href="skoleeksamen.html"><i class="fa fa-check"></i><b>9.1</b> Tidligere skoleeksamener</a></li>
<li class="chapter" data-level="9.2" data-path="tidligere-hjemmeeksamen.html"><a href="tidligere-hjemmeeksamen.html"><i class="fa fa-check"></i><b>9.2</b> Tidligere hjemmeeksamen</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">Håkon Otneim</a></li>
<li><a href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">Geir Drage Berentsen</a></li>
<li><a href="https://github.com/rstudio/bookdown">Publisert ved hjelp av bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MET4 - Empiriske Metoder - høst 2026</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inferens-om-to-populasjoner" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Inferens om to populasjoner<a href="inferens-om-to-populasjoner.html#inferens-om-to-populasjoner" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="videoforelesninger-4" class="section level3 unnumbered hasAnchor">
<h3>Videoforelesninger<a href="inferens-om-to-populasjoner.html#videoforelesninger-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div style="padding:74.64% 0 0 0;position:relative;">
<iframe src="https://vimeo.com/showcase/7780048/embed" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;">
</iframe>
</div>
</div>
<div id="hvilke-sammenligninger-kan-vi-gjre" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Hvilke sammenligninger kan vi gjøre?<a href="inferens-om-to-populasjoner.html#hvilke-sammenligninger-kan-vi-gjre" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ofte er vi ikke ute etter én populasjon, men vil <em>sammenligne to</em>: er avkastningen høyere i det ene fondet enn i det andre? Solgte vi mer etter en ombygging enn før? Framgangsmåten er den samme femstegsoppskriften som før, og igjen er det bare testobservatoren og fordelingen dens som skifter. De fire sammenligningene vi ser på, er:</p>
<ul>
<li>to <strong>forventninger</strong> fra <em>uavhengige</em> utvalg (to-utvalgs t-test),</li>
<li>to forventninger fra <em>matchede par</em> (paret t-test),</li>
<li>to <strong>andeler</strong>, og</li>
<li>to <strong>standardavvik</strong>.</li>
</ul>
<p>Som i forrige delkapittel viser vi for hver test først hvordan den gjøres manuelt, steg for steg med en kritisk verdi, og deretter hvordan R kan utføre hele testen direkte fra dataene.</p>
</div>
<div id="to-utvalgs-t-test" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> To-utvalgs t-test<a href="inferens-om-to-populasjoner.html#to-utvalgs-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Når vi vil sammenligne forventningene i to <em>uavhengige</em> grupper, tester vi <span class="math inline">\(H_0: \mu_1 = \mu_2\)</span>, altså at differansen <span class="math inline">\(\mu_1 - \mu_2\)</span> er null. Testobservatoren er differansen mellom de to utvalgsgjennomsnittene, delt på standardfeilen til denne differansen:</p>
<p><span class="math display">\[T = \frac{\overline{X}_1 - \overline{X}_2}{SE},\]</span></p>
<p>og den er t-fordelt når <span class="math inline">\(H_0\)</span> er sann. Dersom vi antar at de to populasjonene har <em>lik</em> varians, slår vi sammen (pooler) de to utvalgsvariansene til et felles estimat <span class="math inline">\(s_p^2\)</span>, og</p>
<p><span class="math display">\[SE = s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}, \qquad s_p^2 = \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2},\]</span></p>
<p>med <span class="math inline">\(n_1 + n_2 - 2\)</span> frihetsgrader. Antar vi <em>ikke</em> lik varians, bruker vi i stedet <span class="math inline">\(SE = \sqrt{s_1^2/n_1 + s_2^2/n_2}\)</span>. Dette kalles Welchs test, og er det R gjør som standard. Intuisjonen er den samme som før: ligger de to gjennomsnittene mange standardfeil fra hverandre, taler det mot at populasjonene har samme forventning.</p>
<p><strong>Eksempel.</strong> En nettbutikk tester to versjoner (A og B) av forsiden, og måler ordreverdien (i kr) til kundene som ser hver versjon. Gir versjon B høyere gjennomsnittlig ordreverdi?</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er den forventede ordreverdien høyere for versjon B enn for versjon A?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: \mu_B = \mu_A\)</span> mot <span class="math inline">\(H_A: \mu_B &gt; \mu_A\)</span> (ensidig). En Type I-feil ville være å rulle ut versjon B i troen på at den er bedre, uten at den egentlig er det. Konsekvensen er begrenset, så vi velger <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> 50 kunder ser hver versjon. Vi simulerer ordreverdiene:</li>
</ol>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="inferens-om-to-populasjoner.html#cb67-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb67-2"><a href="inferens-om-to-populasjoner.html#cb67-2" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">480</span>, <span class="at">sd =</span> <span class="dv">110</span>)</span>
<span id="cb67-3"><a href="inferens-om-to-populasjoner.html#cb67-3" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean =</span> <span class="dv">530</span>, <span class="at">sd =</span> <span class="dv">110</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Testobservator:</strong> Vi antar lik varians i de to gruppene og bruker den poolede testobservatoren. Vi lar R regne:</li>
</ol>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="inferens-om-to-populasjoner.html#cb68-1" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(B)</span>
<span id="cb68-2"><a href="inferens-om-to-populasjoner.html#cb68-2" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">length</span>(A)</span>
<span id="cb68-3"><a href="inferens-om-to-populasjoner.html#cb68-3" tabindex="-1"></a>s_p <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(((n1 <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span><span class="fu">var</span>(B) <span class="sc">+</span> (n2 <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span><span class="fu">var</span>(A))<span class="sc">/</span>(n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb68-4"><a href="inferens-om-to-populasjoner.html#cb68-4" tabindex="-1"></a></span>
<span id="cb68-5"><a href="inferens-om-to-populasjoner.html#cb68-5" tabindex="-1"></a>T_obs <span class="ot">&lt;-</span> (<span class="fu">mean</span>(B) <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">/</span>(s_p<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>n1 <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>n2))</span>
<span id="cb68-6"><a href="inferens-om-to-populasjoner.html#cb68-6" tabindex="-1"></a>T_obs</span></code></pre></div>
<pre><code>## [1] 2.611099</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> Testobservatoren er t-fordelt med <span class="math inline">\(n_1 + n_2 - 2 = 98\)</span> frihetsgrader. Kritisk verdi for en ensidig test på 5 %-nivå er 95-prosentilen <span class="math inline">\(t_{0.95,\,98}\)</span> (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="inferens-om-to-populasjoner.html#cb70-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.660551</code></pre>
<p>Testobservatoren (2.61) er større enn den kritiske verdien (1.66), så vi forkaster <span class="math inline">\(H_0\)</span>: versjon B ser ut til å gi høyere ordreverdi.</p>
<p>Over gjorde vi testen manuelt. <strong>I R</strong> gjør <code>t.test()</code> hele jobben direkte fra dataene. Vi setter <code>var.equal = TRUE</code> fordi vi antok lik varians (uten det argumentet gjør R en Welch-test som <em>ikke</em> antar lik varians):</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="inferens-om-to-populasjoner.html#cb72-1" tabindex="-1"></a><span class="fu">t.test</span>(B, A, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  B and A
## t = 2.6111, df = 98, p-value = 0.005221
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  18.87795      Inf
## sample estimates:
## mean of x mean of y 
##  542.9059  491.0493</code></pre>
<p>Se på <strong>p-verdien</strong>: den er 0.005, altså under 0.05, så vi forkaster <span class="math inline">\(H_0\)</span>. Merk at <code>t.test()</code> alltid ser på differansen mellom <em>første</em> og <em>andre</em> argument, så rekkefølgen (<code>B, A</code>) avgjør hva <code>alternative = "greater"</code> betyr.</p>
</div>
<div id="t-test-for-matchede-par" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> t-test for matchede par<a href="inferens-om-to-populasjoner.html#t-test-for-matchede-par" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Noen ganger er de to utvalgene <em>ikke</em> uavhengige, men naturlig <em>paret</em>: vi måler den samme enheten to ganger (for eksempel før og etter et tiltak), eller vi matcher enheter parvis. Da ville en vanlig to-utvalgs t-test kaste bort informasjonen som ligger i paringen. I stedet ser vi på <em>differansen</em> innenfor hvert par, <span class="math inline">\(d_i = x_i - y_i\)</span>, og gjør en helt vanlig ett-utvalgs t-test på differansene: <span class="math inline">\(H_0: \mu_d = 0\)</span>. Testobservatoren er</p>
<p><span class="math display">\[T = \frac{\overline{d}}{s_d/\sqrt{n}},\]</span></p>
<p>t-fordelt med <span class="math inline">\(n-1\)</span> frihetsgrader, der <span class="math inline">\(n\)</span> er antall par. Nøkkelspørsmålet er alltid: er de to måltallene paret (avhengige) eller uavhengige? Er de paret, bruker vi den parede testen.</p>
<p><strong>Eksempel.</strong> En butikkjede bygger om 12 av butikkene sine og vil vite om ombyggingen økte ukesomsetningen. For hver butikk har vi omsetningen (i 1000 kr) <em>før</em> og <em>etter</em> ombyggingen. Siden det er de <em>samme</em> butikkene som måles to ganger, er dataene paret.</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Økte den forventede omsetningen etter ombyggingen?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> La $d = $ etter <span class="math inline">\(-\)</span> før. <span class="math inline">\(H_0: \mu_d = 0\)</span> mot <span class="math inline">\(H_A: \mu_d &gt; 0\)</span> (ensidig). En Type I-feil ville være å tro at ombyggingen virket, og bygge om alle butikkene, uten at den egentlig hjelper. Vi velger <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> (simulert, én verdi før og én etter for hver av de 12 butikkene):</li>
</ol>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="inferens-om-to-populasjoner.html#cb74-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb74-2"><a href="inferens-om-to-populasjoner.html#cb74-2" tabindex="-1"></a>for_ombygging   <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">12</span>, <span class="at">mean =</span> <span class="dv">200</span>, <span class="at">sd =</span> <span class="dv">50</span>)</span>
<span id="cb74-3"><a href="inferens-om-to-populasjoner.html#cb74-3" tabindex="-1"></a>etter_ombygging <span class="ot">&lt;-</span> for_ombygging <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">12</span>, <span class="at">mean =</span> <span class="dv">15</span>, <span class="at">sd =</span> <span class="dv">18</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Testobservator:</strong> Vi regner ut de parvise differansene og gjør en ett-utvalgs t-test på dem:</li>
</ol>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="inferens-om-to-populasjoner.html#cb75-1" tabindex="-1"></a>d     <span class="ot">&lt;-</span> etter_ombygging <span class="sc">-</span> for_ombygging</span>
<span id="cb75-2"><a href="inferens-om-to-populasjoner.html#cb75-2" tabindex="-1"></a>T_obs <span class="ot">&lt;-</span> <span class="fu">mean</span>(d)<span class="sc">/</span>(<span class="fu">sd</span>(d)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(d)))</span>
<span id="cb75-3"><a href="inferens-om-to-populasjoner.html#cb75-3" tabindex="-1"></a>T_obs</span></code></pre></div>
<pre><code>## [1] 2.665354</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> Differansene gir <span class="math inline">\(n - 1 = 11\)</span> frihetsgrader. Kritisk verdi for en ensidig test på 5 %-nivå er <span class="math inline">\(t_{0.95,\,11}\)</span> (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="inferens-om-to-populasjoner.html#cb77-1" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>, <span class="at">df =</span> <span class="fu">length</span>(d) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 1.795885</code></pre>
<p>Testobservatoren (2.67) er større enn den kritiske verdien (1.80), så vi forkaster <span class="math inline">\(H_0\)</span>: ombyggingen ser ut til å ha økt omsetningen.</p>
<p>Over gjorde vi testen manuelt på differansene. <strong>I R</strong> setter vi bare <code>paired = TRUE</code> i <code>t.test()</code>, så gjør den nøyaktig dette direkte fra de to seriene:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="inferens-om-to-populasjoner.html#cb79-1" tabindex="-1"></a><span class="fu">t.test</span>(etter_ombygging, for_ombygging, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  etter_ombygging and for_ombygging
## t = 2.6654, df = 11, p-value = 0.01099
## alternative hypothesis: true mean difference is greater than 0
## 95 percent confidence interval:
##  5.075764      Inf
## sample estimates:
## mean difference 
##        15.55973</code></pre>
<p><strong>p-verdien</strong> er 0.011, under 0.05, så vi forkaster <span class="math inline">\(H_0\)</span>. Hadde vi (feilaktig) brukt en vanlig to-utvalgs t-test her, ville vi kastet bort styrken som ligger i at de samme butikkene sammenlignes med seg selv.</p>
</div>
<div id="sammenligning-av-to-andeler" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Sammenligning av to andeler<a href="inferens-om-to-populasjoner.html#sammenligning-av-to-andeler" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vil vi sammenligne to <em>andeler</em>, for eksempel konverteringsraten for to annonser, tester vi <span class="math inline">\(H_0: p_1 = p_2\)</span>. Under nullhypotesen er de to andelene like, så vi slår sammen (pooler) dataene til ett felles estimat <span class="math inline">\(\widehat{p} = (x_1 + x_2)/(n_1 + n_2)\)</span>, der <span class="math inline">\(x_1\)</span> og <span class="math inline">\(x_2\)</span> er antall «suksesser» i de to gruppene. Testobservatoren er</p>
<p><span class="math display">\[Z = \frac{\widehat{p}_1 - \widehat{p}_2}{\sqrt{\widehat{p}(1-\widehat{p})\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}},\]</span></p>
<p>som er tilnærmet standardnormalfordelt når <span class="math inline">\(H_0\)</span> er sann.</p>
<p><strong>Eksempel.</strong> Et selskap kjører to annonsekampanjer, A og B, og vil vite om B gir høyere konverteringsrate (andelen som handler). Av 500 som så kampanje A, handlet 45; av 500 som så kampanje B, handlet 68.</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er den sanne konverteringsraten høyere for B enn for A?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: p_A = p_B\)</span> mot <span class="math inline">\(H_A: p_B &gt; p_A\)</span> (ensidig). En Type I-feil ville være å satse videre på kampanje B i troen på at den er bedre, uten at den egentlig er det. Vi velger <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> <span class="math inline">\(\widehat{p}_A = 45/500 = 0.09\)</span> og <span class="math inline">\(\widehat{p}_B = 68/500 = 0.136\)</span>.</li>
<li><strong>Testobservator:</strong> Under <span class="math inline">\(H_0\)</span> pooler vi andelene: <span class="math inline">\(\widehat{p} = (45 + 68)/(500 + 500) = 0.113\)</span>. Regnet ut manuelt i R:</li>
</ol>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="inferens-om-to-populasjoner.html#cb81-1" tabindex="-1"></a>xA <span class="ot">&lt;-</span> <span class="dv">45</span>; nA <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb81-2"><a href="inferens-om-to-populasjoner.html#cb81-2" tabindex="-1"></a>xB <span class="ot">&lt;-</span> <span class="dv">68</span>; nB <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb81-3"><a href="inferens-om-to-populasjoner.html#cb81-3" tabindex="-1"></a>p.pool <span class="ot">&lt;-</span> (xA <span class="sc">+</span> xB)<span class="sc">/</span>(nA <span class="sc">+</span> nB)</span>
<span id="cb81-4"><a href="inferens-om-to-populasjoner.html#cb81-4" tabindex="-1"></a></span>
<span id="cb81-5"><a href="inferens-om-to-populasjoner.html#cb81-5" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (xB<span class="sc">/</span>nB <span class="sc">-</span> xA<span class="sc">/</span>nA)<span class="sc">/</span><span class="fu">sqrt</span>(p.pool<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p.pool)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span>nA <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>nB))</span>
<span id="cb81-6"><a href="inferens-om-to-populasjoner.html#cb81-6" tabindex="-1"></a>Z</span></code></pre></div>
<pre><code>## [1] 2.297348</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> For en ensidig test på 5 %-nivå er den kritiske verdien <span class="math inline">\(z_{0.95}\)</span> (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="inferens-om-to-populasjoner.html#cb83-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<p>Siden testobservatoren (2.30) er større enn den kritiske verdien (1.645), forkaster vi <span class="math inline">\(H_0\)</span>: kampanje B ser ut til å ha høyere konverteringsrate.</p>
<p>Over gjorde vi testen manuelt. <strong>I R</strong> kan vi bruke <code>prop.test()</code> med <em>vektorer</em> av antall suksesser og antall forsøk:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="inferens-om-to-populasjoner.html#cb85-1" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(xB, xA), <span class="fu">c</span>(nB, nA), <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity correction
## 
## data:  c(xB, xA) out of c(nB, nA)
## X-squared = 5.2778, df = 1, p-value = 0.0108
## alternative hypothesis: greater
## 95 percent confidence interval:
##  0.01315198 1.00000000
## sample estimates:
## prop 1 prop 2 
##  0.136  0.090</code></pre>
<p><strong>p-verdien</strong> er 0.011, under 0.05, så vi forkaster <span class="math inline">\(H_0\)</span>. (Igjen er <code>X-squared</code> lik <span class="math inline">\(Z^2\)</span>, og <code>correct = FALSE</code> gir samme test som håndregningen.)</p>
</div>
<div id="sammenligning-av-to-standardavvik" class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Sammenligning av to standardavvik<a href="inferens-om-to-populasjoner.html#sammenligning-av-to-standardavvik" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Endelig kan vi sammenligne <em>spredningen</em> i to populasjoner, altså teste <span class="math inline">\(H_0: \sigma_1 = \sigma_2\)</span>. Her bruker vi <em>forholdet</em> mellom de to utvalgsvariansene som testobservator:</p>
<p><span class="math display">\[F = \frac{s_1^2}{s_2^2},\]</span></p>
<p>som under <span class="math inline">\(H_0\)</span> følger en <strong>F-fordeling</strong> med <span class="math inline">\((n_1 - 1, n_2 - 1)\)</span> frihetsgrader. Er de to variansene like, ligger <span class="math inline">\(F\)</span> nær 1; er <span class="math inline">\(s_1^2\)</span> mye større enn <span class="math inline">\(s_2^2\)</span>, blir <span class="math inline">\(F\)</span> stor. Som kji-kvadratfordelingen er F-fordelingen asymmetrisk og lever bare på positive verdier.</p>
<p><strong>Eksempel.</strong> En investor vil vite om det ene av to fond har høyere risiko, målt ved standardavviket til den månedlige avkastningen, enn det andre. Vi har 30 månedlige avkastninger (i prosent) fra hvert fond.</p>
<ol style="list-style-type: decimal">
<li><strong>Spørsmål:</strong> Er standardavviket i avkastning større for fond 1 enn for fond 2?</li>
<li><strong>Hypoteser og signifikansnivå:</strong> <span class="math inline">\(H_0: \sigma_1 = \sigma_2\)</span> mot <span class="math inline">\(H_A: \sigma_1 &gt; \sigma_2\)</span> (ensidig). En Type I-feil ville være å velge bort fond 1 som «for risikofylt» uten grunnlag. Vi velger <span class="math inline">\(\alpha = 5\,\%\)</span>.</li>
<li><strong>Data:</strong> (simulert):</li>
</ol>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="inferens-om-to-populasjoner.html#cb87-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb87-2"><a href="inferens-om-to-populasjoner.html#cb87-2" tabindex="-1"></a>fond1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fl">0.8</span>, <span class="at">sd =</span> <span class="fl">5.5</span>)</span>
<span id="cb87-3"><a href="inferens-om-to-populasjoner.html#cb87-3" tabindex="-1"></a>fond2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="fl">0.9</span>, <span class="at">sd =</span> <span class="fl">3.6</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Testobservator:</strong> <span class="math inline">\(F = s_1^2/s_2^2\)</span>:</li>
</ol>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="inferens-om-to-populasjoner.html#cb88-1" tabindex="-1"></a>F_obs <span class="ot">&lt;-</span> <span class="fu">var</span>(fond1)<span class="sc">/</span><span class="fu">var</span>(fond2)</span>
<span id="cb88-2"><a href="inferens-om-to-populasjoner.html#cb88-2" tabindex="-1"></a>F_obs</span></code></pre></div>
<pre><code>## [1] 2.443238</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Kritisk verdi og konklusjon:</strong> <span class="math inline">\(F\)</span> er F-fordelt med <span class="math inline">\((n_1 - 1, n_2 - 1) = (29, 29)\)</span> frihetsgrader. Kritisk verdi for en ensidig test på 5 %-nivå er 95-prosentilen i F-fordelingen (se <a href="relevante-r-testing.html#relevante-r-testing">3.6</a>):</li>
</ol>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="inferens-om-to-populasjoner.html#cb90-1" tabindex="-1"></a><span class="fu">qf</span>(<span class="fl">0.95</span>, <span class="at">df1 =</span> <span class="dv">29</span>, <span class="at">df2 =</span> <span class="dv">29</span>)</span></code></pre></div>
<pre><code>## [1] 1.860811</code></pre>
<p>Testobservatoren (2.44) er større enn den kritiske verdien (1.86), så vi forkaster <span class="math inline">\(H_0\)</span>: fond 1 ser ut til å ha høyere risiko enn fond 2.</p>
<p>Over gjorde vi testen manuelt. <strong>I R</strong> gjør <code>var.test()</code> hele jobben direkte fra dataene:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="inferens-om-to-populasjoner.html#cb92-1" tabindex="-1"></a><span class="fu">var.test</span>(fond1, fond2, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  fond1 and fond2
## F = 2.4432, num df = 29, denom df = 29, p-value = 0.009461
## alternative hypothesis: true ratio of variances is greater than 1
## 95 percent confidence interval:
##  1.312996      Inf
## sample estimates:
## ratio of variances 
##           2.443238</code></pre>
<p><strong>p-verdien</strong> er 0.009, under 0.05, så vi forkaster <span class="math inline">\(H_0\)</span>. Utskriften gir også selve <span class="math inline">\(F\)</span>-verdien og et konfidensintervall for forholdet mellom variansene.</p>
</div>
<div id="kontrollsprsmal-4" class="section level3 hasAnchor" number="3.3.6">
<h3><span class="header-section-number">3.3.6</span> Kontrollspørsmål<a href="inferens-om-to-populasjoner.html#kontrollsprsmal-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Når bruker vi en to-utvalgs t-test, og når en paret t-test?</li>
<li>Hva er forskjellen på å anta lik og ulik varians i en to-utvalgs t-test, og hva gjør R som standard?</li>
<li>Hvorfor slår vi sammen (pooler) de to andelene under <span class="math inline">\(H_0\)</span> når vi sammenligner to andeler?</li>
<li>Hvilken fordeling bruker vi når vi sammenligner to standardavvik, og hvordan ser testobservatoren ut?</li>
</ol>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="enpop.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="kjikvadrattester.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "toc_depth": 4
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
